/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser.
 * Use it to get access to models, enums, and input types.
 *
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from "./internal/prismaNamespaceBrowser";
export { Prisma };
export * as $Enums from "./enums";
export * from "./enums";
/**
 * Model User
 *
 */
export type User = Prisma.UserModel;
/**
 * Model Organization
 *
 */
export type Organization = Prisma.OrganizationModel;
/**
 * Model Team
 *
 */
export type Team = Prisma.TeamModel;
/**
 * Model TeamRepository
 *
 */
export type TeamRepository = Prisma.TeamRepositoryModel;
/**
 * Model TeamProject
 *
 */
export type TeamProject = Prisma.TeamProjectModel;
/**
 * Model Repository
 *
 */
export type Repository = Prisma.RepositoryModel;
/**
 * Model Contributor
 *
 */
export type Contributor = Prisma.ContributorModel;
/**
 * Model Commit
 *
 */
export type Commit = Prisma.CommitModel;
/**
 * Model PullRequest
 *
 */
export type PullRequest = Prisma.PullRequestModel;
/**
 * Model PullRequestReview
 *
 */
export type PullRequestReview = Prisma.PullRequestReviewModel;
/**
 * Model Pipeline
 *
 */
export type Pipeline = Prisma.PipelineModel;
/**
 * Model PipelineRun
 *
 */
export type PipelineRun = Prisma.PipelineRunModel;
/**
 * Model PipelineStage
 *
 */
export type PipelineStage = Prisma.PipelineStageModel;
/**
 * Model QualityScan
 *
 */
export type QualityScan = Prisma.QualityScanModel;
/**
 * Model CoverageMetric
 *
 */
export type CoverageMetric = Prisma.CoverageMetricModel;
/**
 * Model SecurityVulnerability
 *
 */
export type SecurityVulnerability = Prisma.SecurityVulnerabilityModel;
/**
 * Model SonarQubeProjectMapping
 *
 */
export type SonarQubeProjectMapping = Prisma.SonarQubeProjectMappingModel;
/**
 * Model Project
 *
 */
export type Project = Prisma.ProjectModel;
/**
 * Model Board
 *
 */
export type Board = Prisma.BoardModel;
/**
 * Model Sprint
 *
 */
export type Sprint = Prisma.SprintModel;
/**
 * Model Issue
 *
 */
export type Issue = Prisma.IssueModel;
/**
 * Model IssueStatusTransition
 *
 */
export type IssueStatusTransition = Prisma.IssueStatusTransitionModel;
/**
 * Model DataSource
 *
 */
export type DataSource = Prisma.DataSourceModel;
/**
 * Model DataSourceConfig
 *
 */
export type DataSourceConfig = Prisma.DataSourceConfigModel;
/**
 * Model ImportBatch
 *
 */
export type ImportBatch = Prisma.ImportBatchModel;
/**
 * Model DataSourceRun
 *
 */
export type DataSourceRun = Prisma.DataSourceRunModel;
/**
 * Model ImportLog
 *
 */
export type ImportLog = Prisma.ImportLogModel;
