
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

export * as $Enums from './enums'
export * from "./enums"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Users
 * const users = await prisma.user.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Organization
 * 
 */
export type Organization = Prisma.OrganizationModel
/**
 * Model Team
 * 
 */
export type Team = Prisma.TeamModel
/**
 * Model TeamRepository
 * 
 */
export type TeamRepository = Prisma.TeamRepositoryModel
/**
 * Model TeamProject
 * 
 */
export type TeamProject = Prisma.TeamProjectModel
/**
 * Model Repository
 * 
 */
export type Repository = Prisma.RepositoryModel
/**
 * Model Contributor
 * 
 */
export type Contributor = Prisma.ContributorModel
/**
 * Model Commit
 * 
 */
export type Commit = Prisma.CommitModel
/**
 * Model PullRequest
 * 
 */
export type PullRequest = Prisma.PullRequestModel
/**
 * Model PullRequestReview
 * 
 */
export type PullRequestReview = Prisma.PullRequestReviewModel
/**
 * Model Pipeline
 * 
 */
export type Pipeline = Prisma.PipelineModel
/**
 * Model PipelineRun
 * 
 */
export type PipelineRun = Prisma.PipelineRunModel
/**
 * Model PipelineStage
 * 
 */
export type PipelineStage = Prisma.PipelineStageModel
/**
 * Model QualityScan
 * 
 */
export type QualityScan = Prisma.QualityScanModel
/**
 * Model CoverageMetric
 * 
 */
export type CoverageMetric = Prisma.CoverageMetricModel
/**
 * Model SecurityVulnerability
 * 
 */
export type SecurityVulnerability = Prisma.SecurityVulnerabilityModel
/**
 * Model SonarQubeProjectMapping
 * 
 */
export type SonarQubeProjectMapping = Prisma.SonarQubeProjectMappingModel
/**
 * Model Project
 * 
 */
export type Project = Prisma.ProjectModel
/**
 * Model Board
 * 
 */
export type Board = Prisma.BoardModel
/**
 * Model Sprint
 * 
 */
export type Sprint = Prisma.SprintModel
/**
 * Model Issue
 * 
 */
export type Issue = Prisma.IssueModel
/**
 * Model IssueStatusTransition
 * 
 */
export type IssueStatusTransition = Prisma.IssueStatusTransitionModel
/**
 * Model DataSource
 * 
 */
export type DataSource = Prisma.DataSourceModel
/**
 * Model DataSourceConfig
 * 
 */
export type DataSourceConfig = Prisma.DataSourceConfigModel
/**
 * Model ImportBatch
 * 
 */
export type ImportBatch = Prisma.ImportBatchModel
/**
 * Model DataSourceRun
 * 
 */
export type DataSourceRun = Prisma.DataSourceRunModel
/**
 * Model ImportLog
 * 
 */
export type ImportLog = Prisma.ImportLogModel
