/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import type * as runtime from "@prisma/client/runtime/client";
import * as $Enums from "./enums";
import type * as Prisma from "./internal/prismaNamespace";

export type StringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  mode?: Prisma.QueryMode;
  not?: Prisma.NestedStringFilter<$PrismaModel> | string;
};

export type StringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null;
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null;
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null;
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  mode?: Prisma.QueryMode;
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null;
};

export type EnumUserRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.UserRole | Prisma.EnumUserRoleFieldRefInput<$PrismaModel>;
  in?: $Enums.UserRole[] | Prisma.ListEnumUserRoleFieldRefInput<$PrismaModel>;
  notIn?: $Enums.UserRole[] | Prisma.ListEnumUserRoleFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumUserRoleFilter<$PrismaModel> | $Enums.UserRole;
};

export type DateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string;
};

export type SortOrderInput = {
  sort: Prisma.SortOrder;
  nulls?: Prisma.NullsOrder;
};

export type StringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  mode?: Prisma.QueryMode;
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedStringFilter<$PrismaModel>;
  _max?: Prisma.NestedStringFilter<$PrismaModel>;
};

export type StringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null;
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null;
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null;
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  mode?: Prisma.QueryMode;
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null;
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>;
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>;
};

export type EnumUserRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.UserRole | Prisma.EnumUserRoleFieldRefInput<$PrismaModel>;
  in?: $Enums.UserRole[] | Prisma.ListEnumUserRoleFieldRefInput<$PrismaModel>;
  notIn?: $Enums.UserRole[] | Prisma.ListEnumUserRoleFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumUserRoleWithAggregatesFilter<$PrismaModel> | $Enums.UserRole;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumUserRoleFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumUserRoleFilter<$PrismaModel>;
};

export type DateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>;
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>;
};

export type BoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean;
};

export type DateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null;
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null;
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null;
};

export type BoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedBoolFilter<$PrismaModel>;
  _max?: Prisma.NestedBoolFilter<$PrismaModel>;
};

export type DateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null;
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null;
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null;
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>;
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>;
};

export type EnumVcsProviderFilter<$PrismaModel = never> = {
  equals?: $Enums.VcsProvider | Prisma.EnumVcsProviderFieldRefInput<$PrismaModel>;
  in?: $Enums.VcsProvider[] | Prisma.ListEnumVcsProviderFieldRefInput<$PrismaModel>;
  notIn?: $Enums.VcsProvider[] | Prisma.ListEnumVcsProviderFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumVcsProviderFilter<$PrismaModel> | $Enums.VcsProvider;
};

export type IntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>;
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>;
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedIntFilter<$PrismaModel> | number;
};

export type EnumVcsProviderWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.VcsProvider | Prisma.EnumVcsProviderFieldRefInput<$PrismaModel>;
  in?: $Enums.VcsProvider[] | Prisma.ListEnumVcsProviderFieldRefInput<$PrismaModel>;
  notIn?: $Enums.VcsProvider[] | Prisma.ListEnumVcsProviderFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumVcsProviderWithAggregatesFilter<$PrismaModel> | $Enums.VcsProvider;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumVcsProviderFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumVcsProviderFilter<$PrismaModel>;
};

export type IntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>;
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>;
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>;
  _sum?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedIntFilter<$PrismaModel>;
  _max?: Prisma.NestedIntFilter<$PrismaModel>;
};

export type EnumPullRequestStateFilter<$PrismaModel = never> = {
  equals?: $Enums.PullRequestState | Prisma.EnumPullRequestStateFieldRefInput<$PrismaModel>;
  in?: $Enums.PullRequestState[] | Prisma.ListEnumPullRequestStateFieldRefInput<$PrismaModel>;
  notIn?: $Enums.PullRequestState[] | Prisma.ListEnumPullRequestStateFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumPullRequestStateFilter<$PrismaModel> | $Enums.PullRequestState;
};

export type EnumPullRequestStateWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.PullRequestState | Prisma.EnumPullRequestStateFieldRefInput<$PrismaModel>;
  in?: $Enums.PullRequestState[] | Prisma.ListEnumPullRequestStateFieldRefInput<$PrismaModel>;
  notIn?: $Enums.PullRequestState[] | Prisma.ListEnumPullRequestStateFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumPullRequestStateWithAggregatesFilter<$PrismaModel> | $Enums.PullRequestState;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumPullRequestStateFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumPullRequestStateFilter<$PrismaModel>;
};

export type EnumReviewStateFilter<$PrismaModel = never> = {
  equals?: $Enums.ReviewState | Prisma.EnumReviewStateFieldRefInput<$PrismaModel>;
  in?: $Enums.ReviewState[] | Prisma.ListEnumReviewStateFieldRefInput<$PrismaModel>;
  notIn?: $Enums.ReviewState[] | Prisma.ListEnumReviewStateFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumReviewStateFilter<$PrismaModel> | $Enums.ReviewState;
};

export type EnumReviewStateWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ReviewState | Prisma.EnumReviewStateFieldRefInput<$PrismaModel>;
  in?: $Enums.ReviewState[] | Prisma.ListEnumReviewStateFieldRefInput<$PrismaModel>;
  notIn?: $Enums.ReviewState[] | Prisma.ListEnumReviewStateFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumReviewStateWithAggregatesFilter<$PrismaModel> | $Enums.ReviewState;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumReviewStateFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumReviewStateFilter<$PrismaModel>;
};

export type EnumCiProviderFilter<$PrismaModel = never> = {
  equals?: $Enums.CiProvider | Prisma.EnumCiProviderFieldRefInput<$PrismaModel>;
  in?: $Enums.CiProvider[] | Prisma.ListEnumCiProviderFieldRefInput<$PrismaModel>;
  notIn?: $Enums.CiProvider[] | Prisma.ListEnumCiProviderFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumCiProviderFilter<$PrismaModel> | $Enums.CiProvider;
};

export type EnumCiProviderWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CiProvider | Prisma.EnumCiProviderFieldRefInput<$PrismaModel>;
  in?: $Enums.CiProvider[] | Prisma.ListEnumCiProviderFieldRefInput<$PrismaModel>;
  notIn?: $Enums.CiProvider[] | Prisma.ListEnumCiProviderFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumCiProviderWithAggregatesFilter<$PrismaModel> | $Enums.CiProvider;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumCiProviderFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumCiProviderFilter<$PrismaModel>;
};

export type EnumPipelineStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.PipelineStatus | Prisma.EnumPipelineStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.PipelineStatus[] | Prisma.ListEnumPipelineStatusFieldRefInput<$PrismaModel>;
  notIn?: $Enums.PipelineStatus[] | Prisma.ListEnumPipelineStatusFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumPipelineStatusFilter<$PrismaModel> | $Enums.PipelineStatus;
};

export type IntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null;
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null;
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null;
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null;
};

export type EnumPipelineStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.PipelineStatus | Prisma.EnumPipelineStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.PipelineStatus[] | Prisma.ListEnumPipelineStatusFieldRefInput<$PrismaModel>;
  notIn?: $Enums.PipelineStatus[] | Prisma.ListEnumPipelineStatusFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumPipelineStatusWithAggregatesFilter<$PrismaModel> | $Enums.PipelineStatus;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumPipelineStatusFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumPipelineStatusFilter<$PrismaModel>;
};

export type IntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null;
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null;
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null;
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedIntNullableWithAggregatesFilter<$PrismaModel> | number | null;
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>;
  _sum?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _min?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _max?: Prisma.NestedIntNullableFilter<$PrismaModel>;
};

export type FloatNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null;
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null;
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null;
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedFloatNullableFilter<$PrismaModel> | number | null;
};

export type FloatNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null;
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null;
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null;
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedFloatNullableWithAggregatesFilter<$PrismaModel> | number | null;
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>;
  _sum?: Prisma.NestedFloatNullableFilter<$PrismaModel>;
  _min?: Prisma.NestedFloatNullableFilter<$PrismaModel>;
  _max?: Prisma.NestedFloatNullableFilter<$PrismaModel>;
};

export type FloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>;
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>;
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number;
};

export type FloatWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>;
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>;
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedFloatWithAggregatesFilter<$PrismaModel> | number;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>;
  _sum?: Prisma.NestedFloatFilter<$PrismaModel>;
  _min?: Prisma.NestedFloatFilter<$PrismaModel>;
  _max?: Prisma.NestedFloatFilter<$PrismaModel>;
};

export type EnumVulnerabilitySeverityFilter<$PrismaModel = never> = {
  equals?: $Enums.VulnerabilitySeverity | Prisma.EnumVulnerabilitySeverityFieldRefInput<$PrismaModel>;
  in?: $Enums.VulnerabilitySeverity[] | Prisma.ListEnumVulnerabilitySeverityFieldRefInput<$PrismaModel>;
  notIn?: $Enums.VulnerabilitySeverity[] | Prisma.ListEnumVulnerabilitySeverityFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumVulnerabilitySeverityFilter<$PrismaModel> | $Enums.VulnerabilitySeverity;
};

export type EnumVulnerabilityStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.VulnerabilityStatus | Prisma.EnumVulnerabilityStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.VulnerabilityStatus[] | Prisma.ListEnumVulnerabilityStatusFieldRefInput<$PrismaModel>;
  notIn?: $Enums.VulnerabilityStatus[] | Prisma.ListEnumVulnerabilityStatusFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumVulnerabilityStatusFilter<$PrismaModel> | $Enums.VulnerabilityStatus;
};

export type EnumVulnerabilitySeverityWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.VulnerabilitySeverity | Prisma.EnumVulnerabilitySeverityFieldRefInput<$PrismaModel>;
  in?: $Enums.VulnerabilitySeverity[] | Prisma.ListEnumVulnerabilitySeverityFieldRefInput<$PrismaModel>;
  notIn?: $Enums.VulnerabilitySeverity[] | Prisma.ListEnumVulnerabilitySeverityFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumVulnerabilitySeverityWithAggregatesFilter<$PrismaModel> | $Enums.VulnerabilitySeverity;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumVulnerabilitySeverityFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumVulnerabilitySeverityFilter<$PrismaModel>;
};

export type EnumVulnerabilityStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.VulnerabilityStatus | Prisma.EnumVulnerabilityStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.VulnerabilityStatus[] | Prisma.ListEnumVulnerabilityStatusFieldRefInput<$PrismaModel>;
  notIn?: $Enums.VulnerabilityStatus[] | Prisma.ListEnumVulnerabilityStatusFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumVulnerabilityStatusWithAggregatesFilter<$PrismaModel> | $Enums.VulnerabilityStatus;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumVulnerabilityStatusFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumVulnerabilityStatusFilter<$PrismaModel>;
};

export type EnumProjectProviderFilter<$PrismaModel = never> = {
  equals?: $Enums.ProjectProvider | Prisma.EnumProjectProviderFieldRefInput<$PrismaModel>;
  in?: $Enums.ProjectProvider[] | Prisma.ListEnumProjectProviderFieldRefInput<$PrismaModel>;
  notIn?: $Enums.ProjectProvider[] | Prisma.ListEnumProjectProviderFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumProjectProviderFilter<$PrismaModel> | $Enums.ProjectProvider;
};

export type EnumProjectProviderWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ProjectProvider | Prisma.EnumProjectProviderFieldRefInput<$PrismaModel>;
  in?: $Enums.ProjectProvider[] | Prisma.ListEnumProjectProviderFieldRefInput<$PrismaModel>;
  notIn?: $Enums.ProjectProvider[] | Prisma.ListEnumProjectProviderFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumProjectProviderWithAggregatesFilter<$PrismaModel> | $Enums.ProjectProvider;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumProjectProviderFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumProjectProviderFilter<$PrismaModel>;
};

export type EnumIssueTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.IssueType | Prisma.EnumIssueTypeFieldRefInput<$PrismaModel>;
  in?: $Enums.IssueType[] | Prisma.ListEnumIssueTypeFieldRefInput<$PrismaModel>;
  notIn?: $Enums.IssueType[] | Prisma.ListEnumIssueTypeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumIssueTypeFilter<$PrismaModel> | $Enums.IssueType;
};

export type EnumIssueStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.IssueStatus | Prisma.EnumIssueStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.IssueStatus[] | Prisma.ListEnumIssueStatusFieldRefInput<$PrismaModel>;
  notIn?: $Enums.IssueStatus[] | Prisma.ListEnumIssueStatusFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumIssueStatusFilter<$PrismaModel> | $Enums.IssueStatus;
};

export type EnumIssuePriorityFilter<$PrismaModel = never> = {
  equals?: $Enums.IssuePriority | Prisma.EnumIssuePriorityFieldRefInput<$PrismaModel>;
  in?: $Enums.IssuePriority[] | Prisma.ListEnumIssuePriorityFieldRefInput<$PrismaModel>;
  notIn?: $Enums.IssuePriority[] | Prisma.ListEnumIssuePriorityFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumIssuePriorityFilter<$PrismaModel> | $Enums.IssuePriority;
};

export type EnumIssueTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.IssueType | Prisma.EnumIssueTypeFieldRefInput<$PrismaModel>;
  in?: $Enums.IssueType[] | Prisma.ListEnumIssueTypeFieldRefInput<$PrismaModel>;
  notIn?: $Enums.IssueType[] | Prisma.ListEnumIssueTypeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumIssueTypeWithAggregatesFilter<$PrismaModel> | $Enums.IssueType;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumIssueTypeFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumIssueTypeFilter<$PrismaModel>;
};

export type EnumIssueStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.IssueStatus | Prisma.EnumIssueStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.IssueStatus[] | Prisma.ListEnumIssueStatusFieldRefInput<$PrismaModel>;
  notIn?: $Enums.IssueStatus[] | Prisma.ListEnumIssueStatusFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumIssueStatusWithAggregatesFilter<$PrismaModel> | $Enums.IssueStatus;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumIssueStatusFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumIssueStatusFilter<$PrismaModel>;
};

export type EnumIssuePriorityWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.IssuePriority | Prisma.EnumIssuePriorityFieldRefInput<$PrismaModel>;
  in?: $Enums.IssuePriority[] | Prisma.ListEnumIssuePriorityFieldRefInput<$PrismaModel>;
  notIn?: $Enums.IssuePriority[] | Prisma.ListEnumIssuePriorityFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumIssuePriorityWithAggregatesFilter<$PrismaModel> | $Enums.IssuePriority;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumIssuePriorityFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumIssuePriorityFilter<$PrismaModel>;
};

export type EnumDataSourceProviderFilter<$PrismaModel = never> = {
  equals?: $Enums.DataSourceProvider | Prisma.EnumDataSourceProviderFieldRefInput<$PrismaModel>;
  in?: $Enums.DataSourceProvider[] | Prisma.ListEnumDataSourceProviderFieldRefInput<$PrismaModel>;
  notIn?: $Enums.DataSourceProvider[] | Prisma.ListEnumDataSourceProviderFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumDataSourceProviderFilter<$PrismaModel> | $Enums.DataSourceProvider;
};

export type EnumDataSourceProviderWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DataSourceProvider | Prisma.EnumDataSourceProviderFieldRefInput<$PrismaModel>;
  in?: $Enums.DataSourceProvider[] | Prisma.ListEnumDataSourceProviderFieldRefInput<$PrismaModel>;
  notIn?: $Enums.DataSourceProvider[] | Prisma.ListEnumDataSourceProviderFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumDataSourceProviderWithAggregatesFilter<$PrismaModel> | $Enums.DataSourceProvider;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumDataSourceProviderFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumDataSourceProviderFilter<$PrismaModel>;
};

export type EnumDataSourceRunStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.DataSourceRunStatus | Prisma.EnumDataSourceRunStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.DataSourceRunStatus[] | Prisma.ListEnumDataSourceRunStatusFieldRefInput<$PrismaModel>;
  notIn?: $Enums.DataSourceRunStatus[] | Prisma.ListEnumDataSourceRunStatusFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumDataSourceRunStatusFilter<$PrismaModel> | $Enums.DataSourceRunStatus;
};

export type EnumDataSourceRunStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DataSourceRunStatus | Prisma.EnumDataSourceRunStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.DataSourceRunStatus[] | Prisma.ListEnumDataSourceRunStatusFieldRefInput<$PrismaModel>;
  notIn?: $Enums.DataSourceRunStatus[] | Prisma.ListEnumDataSourceRunStatusFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumDataSourceRunStatusWithAggregatesFilter<$PrismaModel> | $Enums.DataSourceRunStatus;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumDataSourceRunStatusFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumDataSourceRunStatusFilter<$PrismaModel>;
};

export type EnumImportLogLevelFilter<$PrismaModel = never> = {
  equals?: $Enums.ImportLogLevel | Prisma.EnumImportLogLevelFieldRefInput<$PrismaModel>;
  in?: $Enums.ImportLogLevel[] | Prisma.ListEnumImportLogLevelFieldRefInput<$PrismaModel>;
  notIn?: $Enums.ImportLogLevel[] | Prisma.ListEnumImportLogLevelFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumImportLogLevelFilter<$PrismaModel> | $Enums.ImportLogLevel;
};

export type EnumImportLogLevelWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ImportLogLevel | Prisma.EnumImportLogLevelFieldRefInput<$PrismaModel>;
  in?: $Enums.ImportLogLevel[] | Prisma.ListEnumImportLogLevelFieldRefInput<$PrismaModel>;
  notIn?: $Enums.ImportLogLevel[] | Prisma.ListEnumImportLogLevelFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumImportLogLevelWithAggregatesFilter<$PrismaModel> | $Enums.ImportLogLevel;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumImportLogLevelFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumImportLogLevelFilter<$PrismaModel>;
};

export type NestedStringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedStringFilter<$PrismaModel> | string;
};

export type NestedStringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null;
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null;
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null;
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null;
};

export type NestedEnumUserRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.UserRole | Prisma.EnumUserRoleFieldRefInput<$PrismaModel>;
  in?: $Enums.UserRole[] | Prisma.ListEnumUserRoleFieldRefInput<$PrismaModel>;
  notIn?: $Enums.UserRole[] | Prisma.ListEnumUserRoleFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumUserRoleFilter<$PrismaModel> | $Enums.UserRole;
};

export type NestedDateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string;
};

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedStringFilter<$PrismaModel>;
  _max?: Prisma.NestedStringFilter<$PrismaModel>;
};

export type NestedIntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>;
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>;
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedIntFilter<$PrismaModel> | number;
};

export type NestedStringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null;
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null;
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null;
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null;
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>;
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>;
};

export type NestedIntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null;
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null;
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null;
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null;
};

export type NestedEnumUserRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.UserRole | Prisma.EnumUserRoleFieldRefInput<$PrismaModel>;
  in?: $Enums.UserRole[] | Prisma.ListEnumUserRoleFieldRefInput<$PrismaModel>;
  notIn?: $Enums.UserRole[] | Prisma.ListEnumUserRoleFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumUserRoleWithAggregatesFilter<$PrismaModel> | $Enums.UserRole;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumUserRoleFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumUserRoleFilter<$PrismaModel>;
};

export type NestedDateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>;
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>;
};

export type NestedBoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean;
};

export type NestedDateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null;
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null;
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null;
};

export type NestedBoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedBoolFilter<$PrismaModel>;
  _max?: Prisma.NestedBoolFilter<$PrismaModel>;
};

export type NestedDateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null;
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null;
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null;
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null;
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>;
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>;
};

export type NestedEnumVcsProviderFilter<$PrismaModel = never> = {
  equals?: $Enums.VcsProvider | Prisma.EnumVcsProviderFieldRefInput<$PrismaModel>;
  in?: $Enums.VcsProvider[] | Prisma.ListEnumVcsProviderFieldRefInput<$PrismaModel>;
  notIn?: $Enums.VcsProvider[] | Prisma.ListEnumVcsProviderFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumVcsProviderFilter<$PrismaModel> | $Enums.VcsProvider;
};

export type NestedEnumVcsProviderWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.VcsProvider | Prisma.EnumVcsProviderFieldRefInput<$PrismaModel>;
  in?: $Enums.VcsProvider[] | Prisma.ListEnumVcsProviderFieldRefInput<$PrismaModel>;
  notIn?: $Enums.VcsProvider[] | Prisma.ListEnumVcsProviderFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumVcsProviderWithAggregatesFilter<$PrismaModel> | $Enums.VcsProvider;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumVcsProviderFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumVcsProviderFilter<$PrismaModel>;
};

export type NestedIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>;
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>;
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>;
  _sum?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedIntFilter<$PrismaModel>;
  _max?: Prisma.NestedIntFilter<$PrismaModel>;
};

export type NestedFloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>;
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>;
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number;
};

export type NestedEnumPullRequestStateFilter<$PrismaModel = never> = {
  equals?: $Enums.PullRequestState | Prisma.EnumPullRequestStateFieldRefInput<$PrismaModel>;
  in?: $Enums.PullRequestState[] | Prisma.ListEnumPullRequestStateFieldRefInput<$PrismaModel>;
  notIn?: $Enums.PullRequestState[] | Prisma.ListEnumPullRequestStateFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumPullRequestStateFilter<$PrismaModel> | $Enums.PullRequestState;
};

export type NestedEnumPullRequestStateWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.PullRequestState | Prisma.EnumPullRequestStateFieldRefInput<$PrismaModel>;
  in?: $Enums.PullRequestState[] | Prisma.ListEnumPullRequestStateFieldRefInput<$PrismaModel>;
  notIn?: $Enums.PullRequestState[] | Prisma.ListEnumPullRequestStateFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumPullRequestStateWithAggregatesFilter<$PrismaModel> | $Enums.PullRequestState;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumPullRequestStateFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumPullRequestStateFilter<$PrismaModel>;
};

export type NestedEnumReviewStateFilter<$PrismaModel = never> = {
  equals?: $Enums.ReviewState | Prisma.EnumReviewStateFieldRefInput<$PrismaModel>;
  in?: $Enums.ReviewState[] | Prisma.ListEnumReviewStateFieldRefInput<$PrismaModel>;
  notIn?: $Enums.ReviewState[] | Prisma.ListEnumReviewStateFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumReviewStateFilter<$PrismaModel> | $Enums.ReviewState;
};

export type NestedEnumReviewStateWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ReviewState | Prisma.EnumReviewStateFieldRefInput<$PrismaModel>;
  in?: $Enums.ReviewState[] | Prisma.ListEnumReviewStateFieldRefInput<$PrismaModel>;
  notIn?: $Enums.ReviewState[] | Prisma.ListEnumReviewStateFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumReviewStateWithAggregatesFilter<$PrismaModel> | $Enums.ReviewState;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumReviewStateFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumReviewStateFilter<$PrismaModel>;
};

export type NestedEnumCiProviderFilter<$PrismaModel = never> = {
  equals?: $Enums.CiProvider | Prisma.EnumCiProviderFieldRefInput<$PrismaModel>;
  in?: $Enums.CiProvider[] | Prisma.ListEnumCiProviderFieldRefInput<$PrismaModel>;
  notIn?: $Enums.CiProvider[] | Prisma.ListEnumCiProviderFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumCiProviderFilter<$PrismaModel> | $Enums.CiProvider;
};

export type NestedEnumCiProviderWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CiProvider | Prisma.EnumCiProviderFieldRefInput<$PrismaModel>;
  in?: $Enums.CiProvider[] | Prisma.ListEnumCiProviderFieldRefInput<$PrismaModel>;
  notIn?: $Enums.CiProvider[] | Prisma.ListEnumCiProviderFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumCiProviderWithAggregatesFilter<$PrismaModel> | $Enums.CiProvider;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumCiProviderFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumCiProviderFilter<$PrismaModel>;
};

export type NestedEnumPipelineStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.PipelineStatus | Prisma.EnumPipelineStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.PipelineStatus[] | Prisma.ListEnumPipelineStatusFieldRefInput<$PrismaModel>;
  notIn?: $Enums.PipelineStatus[] | Prisma.ListEnumPipelineStatusFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumPipelineStatusFilter<$PrismaModel> | $Enums.PipelineStatus;
};

export type NestedEnumPipelineStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.PipelineStatus | Prisma.EnumPipelineStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.PipelineStatus[] | Prisma.ListEnumPipelineStatusFieldRefInput<$PrismaModel>;
  notIn?: $Enums.PipelineStatus[] | Prisma.ListEnumPipelineStatusFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumPipelineStatusWithAggregatesFilter<$PrismaModel> | $Enums.PipelineStatus;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumPipelineStatusFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumPipelineStatusFilter<$PrismaModel>;
};

export type NestedIntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null;
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null;
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null;
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedIntNullableWithAggregatesFilter<$PrismaModel> | number | null;
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>;
  _sum?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _min?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _max?: Prisma.NestedIntNullableFilter<$PrismaModel>;
};

export type NestedFloatNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null;
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null;
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null;
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedFloatNullableFilter<$PrismaModel> | number | null;
};

export type NestedFloatNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null;
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null;
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null;
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedFloatNullableWithAggregatesFilter<$PrismaModel> | number | null;
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>;
  _sum?: Prisma.NestedFloatNullableFilter<$PrismaModel>;
  _min?: Prisma.NestedFloatNullableFilter<$PrismaModel>;
  _max?: Prisma.NestedFloatNullableFilter<$PrismaModel>;
};

export type NestedFloatWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>;
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>;
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedFloatWithAggregatesFilter<$PrismaModel> | number;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>;
  _sum?: Prisma.NestedFloatFilter<$PrismaModel>;
  _min?: Prisma.NestedFloatFilter<$PrismaModel>;
  _max?: Prisma.NestedFloatFilter<$PrismaModel>;
};

export type NestedEnumVulnerabilitySeverityFilter<$PrismaModel = never> = {
  equals?: $Enums.VulnerabilitySeverity | Prisma.EnumVulnerabilitySeverityFieldRefInput<$PrismaModel>;
  in?: $Enums.VulnerabilitySeverity[] | Prisma.ListEnumVulnerabilitySeverityFieldRefInput<$PrismaModel>;
  notIn?: $Enums.VulnerabilitySeverity[] | Prisma.ListEnumVulnerabilitySeverityFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumVulnerabilitySeverityFilter<$PrismaModel> | $Enums.VulnerabilitySeverity;
};

export type NestedEnumVulnerabilityStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.VulnerabilityStatus | Prisma.EnumVulnerabilityStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.VulnerabilityStatus[] | Prisma.ListEnumVulnerabilityStatusFieldRefInput<$PrismaModel>;
  notIn?: $Enums.VulnerabilityStatus[] | Prisma.ListEnumVulnerabilityStatusFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumVulnerabilityStatusFilter<$PrismaModel> | $Enums.VulnerabilityStatus;
};

export type NestedEnumVulnerabilitySeverityWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.VulnerabilitySeverity | Prisma.EnumVulnerabilitySeverityFieldRefInput<$PrismaModel>;
  in?: $Enums.VulnerabilitySeverity[] | Prisma.ListEnumVulnerabilitySeverityFieldRefInput<$PrismaModel>;
  notIn?: $Enums.VulnerabilitySeverity[] | Prisma.ListEnumVulnerabilitySeverityFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumVulnerabilitySeverityWithAggregatesFilter<$PrismaModel> | $Enums.VulnerabilitySeverity;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumVulnerabilitySeverityFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumVulnerabilitySeverityFilter<$PrismaModel>;
};

export type NestedEnumVulnerabilityStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.VulnerabilityStatus | Prisma.EnumVulnerabilityStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.VulnerabilityStatus[] | Prisma.ListEnumVulnerabilityStatusFieldRefInput<$PrismaModel>;
  notIn?: $Enums.VulnerabilityStatus[] | Prisma.ListEnumVulnerabilityStatusFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumVulnerabilityStatusWithAggregatesFilter<$PrismaModel> | $Enums.VulnerabilityStatus;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumVulnerabilityStatusFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumVulnerabilityStatusFilter<$PrismaModel>;
};

export type NestedEnumProjectProviderFilter<$PrismaModel = never> = {
  equals?: $Enums.ProjectProvider | Prisma.EnumProjectProviderFieldRefInput<$PrismaModel>;
  in?: $Enums.ProjectProvider[] | Prisma.ListEnumProjectProviderFieldRefInput<$PrismaModel>;
  notIn?: $Enums.ProjectProvider[] | Prisma.ListEnumProjectProviderFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumProjectProviderFilter<$PrismaModel> | $Enums.ProjectProvider;
};

export type NestedEnumProjectProviderWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ProjectProvider | Prisma.EnumProjectProviderFieldRefInput<$PrismaModel>;
  in?: $Enums.ProjectProvider[] | Prisma.ListEnumProjectProviderFieldRefInput<$PrismaModel>;
  notIn?: $Enums.ProjectProvider[] | Prisma.ListEnumProjectProviderFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumProjectProviderWithAggregatesFilter<$PrismaModel> | $Enums.ProjectProvider;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumProjectProviderFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumProjectProviderFilter<$PrismaModel>;
};

export type NestedEnumIssueTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.IssueType | Prisma.EnumIssueTypeFieldRefInput<$PrismaModel>;
  in?: $Enums.IssueType[] | Prisma.ListEnumIssueTypeFieldRefInput<$PrismaModel>;
  notIn?: $Enums.IssueType[] | Prisma.ListEnumIssueTypeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumIssueTypeFilter<$PrismaModel> | $Enums.IssueType;
};

export type NestedEnumIssueStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.IssueStatus | Prisma.EnumIssueStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.IssueStatus[] | Prisma.ListEnumIssueStatusFieldRefInput<$PrismaModel>;
  notIn?: $Enums.IssueStatus[] | Prisma.ListEnumIssueStatusFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumIssueStatusFilter<$PrismaModel> | $Enums.IssueStatus;
};

export type NestedEnumIssuePriorityFilter<$PrismaModel = never> = {
  equals?: $Enums.IssuePriority | Prisma.EnumIssuePriorityFieldRefInput<$PrismaModel>;
  in?: $Enums.IssuePriority[] | Prisma.ListEnumIssuePriorityFieldRefInput<$PrismaModel>;
  notIn?: $Enums.IssuePriority[] | Prisma.ListEnumIssuePriorityFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumIssuePriorityFilter<$PrismaModel> | $Enums.IssuePriority;
};

export type NestedEnumIssueTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.IssueType | Prisma.EnumIssueTypeFieldRefInput<$PrismaModel>;
  in?: $Enums.IssueType[] | Prisma.ListEnumIssueTypeFieldRefInput<$PrismaModel>;
  notIn?: $Enums.IssueType[] | Prisma.ListEnumIssueTypeFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumIssueTypeWithAggregatesFilter<$PrismaModel> | $Enums.IssueType;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumIssueTypeFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumIssueTypeFilter<$PrismaModel>;
};

export type NestedEnumIssueStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.IssueStatus | Prisma.EnumIssueStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.IssueStatus[] | Prisma.ListEnumIssueStatusFieldRefInput<$PrismaModel>;
  notIn?: $Enums.IssueStatus[] | Prisma.ListEnumIssueStatusFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumIssueStatusWithAggregatesFilter<$PrismaModel> | $Enums.IssueStatus;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumIssueStatusFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumIssueStatusFilter<$PrismaModel>;
};

export type NestedEnumIssuePriorityWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.IssuePriority | Prisma.EnumIssuePriorityFieldRefInput<$PrismaModel>;
  in?: $Enums.IssuePriority[] | Prisma.ListEnumIssuePriorityFieldRefInput<$PrismaModel>;
  notIn?: $Enums.IssuePriority[] | Prisma.ListEnumIssuePriorityFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumIssuePriorityWithAggregatesFilter<$PrismaModel> | $Enums.IssuePriority;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumIssuePriorityFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumIssuePriorityFilter<$PrismaModel>;
};

export type NestedEnumDataSourceProviderFilter<$PrismaModel = never> = {
  equals?: $Enums.DataSourceProvider | Prisma.EnumDataSourceProviderFieldRefInput<$PrismaModel>;
  in?: $Enums.DataSourceProvider[] | Prisma.ListEnumDataSourceProviderFieldRefInput<$PrismaModel>;
  notIn?: $Enums.DataSourceProvider[] | Prisma.ListEnumDataSourceProviderFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumDataSourceProviderFilter<$PrismaModel> | $Enums.DataSourceProvider;
};

export type NestedEnumDataSourceProviderWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DataSourceProvider | Prisma.EnumDataSourceProviderFieldRefInput<$PrismaModel>;
  in?: $Enums.DataSourceProvider[] | Prisma.ListEnumDataSourceProviderFieldRefInput<$PrismaModel>;
  notIn?: $Enums.DataSourceProvider[] | Prisma.ListEnumDataSourceProviderFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumDataSourceProviderWithAggregatesFilter<$PrismaModel> | $Enums.DataSourceProvider;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumDataSourceProviderFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumDataSourceProviderFilter<$PrismaModel>;
};

export type NestedEnumDataSourceRunStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.DataSourceRunStatus | Prisma.EnumDataSourceRunStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.DataSourceRunStatus[] | Prisma.ListEnumDataSourceRunStatusFieldRefInput<$PrismaModel>;
  notIn?: $Enums.DataSourceRunStatus[] | Prisma.ListEnumDataSourceRunStatusFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumDataSourceRunStatusFilter<$PrismaModel> | $Enums.DataSourceRunStatus;
};

export type NestedEnumDataSourceRunStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.DataSourceRunStatus | Prisma.EnumDataSourceRunStatusFieldRefInput<$PrismaModel>;
  in?: $Enums.DataSourceRunStatus[] | Prisma.ListEnumDataSourceRunStatusFieldRefInput<$PrismaModel>;
  notIn?: $Enums.DataSourceRunStatus[] | Prisma.ListEnumDataSourceRunStatusFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumDataSourceRunStatusWithAggregatesFilter<$PrismaModel> | $Enums.DataSourceRunStatus;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumDataSourceRunStatusFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumDataSourceRunStatusFilter<$PrismaModel>;
};

export type NestedEnumImportLogLevelFilter<$PrismaModel = never> = {
  equals?: $Enums.ImportLogLevel | Prisma.EnumImportLogLevelFieldRefInput<$PrismaModel>;
  in?: $Enums.ImportLogLevel[] | Prisma.ListEnumImportLogLevelFieldRefInput<$PrismaModel>;
  notIn?: $Enums.ImportLogLevel[] | Prisma.ListEnumImportLogLevelFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumImportLogLevelFilter<$PrismaModel> | $Enums.ImportLogLevel;
};

export type NestedEnumImportLogLevelWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ImportLogLevel | Prisma.EnumImportLogLevelFieldRefInput<$PrismaModel>;
  in?: $Enums.ImportLogLevel[] | Prisma.ListEnumImportLogLevelFieldRefInput<$PrismaModel>;
  notIn?: $Enums.ImportLogLevel[] | Prisma.ListEnumImportLogLevelFieldRefInput<$PrismaModel>;
  not?: Prisma.NestedEnumImportLogLevelWithAggregatesFilter<$PrismaModel> | $Enums.ImportLogLevel;
  _count?: Prisma.NestedIntFilter<$PrismaModel>;
  _min?: Prisma.NestedEnumImportLogLevelFilter<$PrismaModel>;
  _max?: Prisma.NestedEnumImportLogLevelFilter<$PrismaModel>;
};
