
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserRole = {
  ADMIN: 'ADMIN',
  USER: 'USER'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]


export const VcsProvider = {
  GITHUB: 'GITHUB',
  GITLAB: 'GITLAB',
  BITBUCKET: 'BITBUCKET',
  AZURE_DEVOPS: 'AZURE_DEVOPS',
  JIRA: 'JIRA'
} as const

export type VcsProvider = (typeof VcsProvider)[keyof typeof VcsProvider]


export const PullRequestState = {
  OPEN: 'OPEN',
  MERGED: 'MERGED',
  CLOSED: 'CLOSED',
  DRAFT: 'DRAFT'
} as const

export type PullRequestState = (typeof PullRequestState)[keyof typeof PullRequestState]


export const ReviewState = {
  APPROVED: 'APPROVED',
  CHANGES_REQUESTED: 'CHANGES_REQUESTED',
  COMMENTED: 'COMMENTED',
  DISMISSED: 'DISMISSED'
} as const

export type ReviewState = (typeof ReviewState)[keyof typeof ReviewState]


export const CiProvider = {
  GITHUB_ACTIONS: 'GITHUB_ACTIONS',
  GITLAB_CI: 'GITLAB_CI',
  JENKINS: 'JENKINS',
  CIRCLECI: 'CIRCLECI',
  TRAVIS_CI: 'TRAVIS_CI',
  AZURE_PIPELINES: 'AZURE_PIPELINES'
} as const

export type CiProvider = (typeof CiProvider)[keyof typeof CiProvider]


export const PipelineStatus = {
  PENDING: 'PENDING',
  RUNNING: 'RUNNING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  SKIPPED: 'SKIPPED'
} as const

export type PipelineStatus = (typeof PipelineStatus)[keyof typeof PipelineStatus]


export const VulnerabilitySeverity = {
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
  INFORMATIONAL: 'INFORMATIONAL'
} as const

export type VulnerabilitySeverity = (typeof VulnerabilitySeverity)[keyof typeof VulnerabilitySeverity]


export const VulnerabilityStatus = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  WONT_FIX: 'WONT_FIX',
  FALSE_POSITIVE: 'FALSE_POSITIVE'
} as const

export type VulnerabilityStatus = (typeof VulnerabilityStatus)[keyof typeof VulnerabilityStatus]


export const ProjectProvider = {
  JIRA: 'JIRA',
  TRELLO: 'TRELLO',
  ASANA: 'ASANA',
  LINEAR: 'LINEAR',
  GITHUB: 'GITHUB',
  GITLAB: 'GITLAB'
} as const

export type ProjectProvider = (typeof ProjectProvider)[keyof typeof ProjectProvider]


export const IssuePriority = {
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
  TRIVIAL: 'TRIVIAL'
} as const

export type IssuePriority = (typeof IssuePriority)[keyof typeof IssuePriority]


export const IssueStatus = {
  TODO: 'TODO',
  IN_PROGRESS: 'IN_PROGRESS',
  IN_REVIEW: 'IN_REVIEW',
  BLOCKED: 'BLOCKED',
  DONE: 'DONE',
  CANCELLED: 'CANCELLED'
} as const

export type IssueStatus = (typeof IssueStatus)[keyof typeof IssueStatus]


export const IssueType = {
  BUG: 'BUG',
  FEATURE: 'FEATURE',
  TASK: 'TASK',
  STORY: 'STORY',
  EPIC: 'EPIC',
  SUBTASK: 'SUBTASK'
} as const

export type IssueType = (typeof IssueType)[keyof typeof IssueType]


export const DataSourceProvider = {
  GITHUB: 'GITHUB',
  GITLAB: 'GITLAB',
  BITBUCKET: 'BITBUCKET',
  AZURE_DEVOPS: 'AZURE_DEVOPS',
  JIRA: 'JIRA',
  TRELLO: 'TRELLO',
  ASANA: 'ASANA',
  LINEAR: 'LINEAR',
  JENKINS: 'JENKINS',
  CIRCLECI: 'CIRCLECI',
  GITHUB_ACTIONS: 'GITHUB_ACTIONS',
  GITLAB_CI: 'GITLAB_CI',
  SONARQUBE: 'SONARQUBE',
  SNYK: 'SNYK',
  DEPENDABOT: 'DEPENDABOT'
} as const

export type DataSourceProvider = (typeof DataSourceProvider)[keyof typeof DataSourceProvider]


export const DataSourceRunStatus = {
  PENDING: 'PENDING',
  RUNNING: 'RUNNING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
} as const

export type DataSourceRunStatus = (typeof DataSourceRunStatus)[keyof typeof DataSourceRunStatus]


export const ImportLogLevel = {
  INFO: 'INFO',
  WARNING: 'WARNING',
  ERROR: 'ERROR',
  DEBUG: 'DEBUG'
} as const

export type ImportLogLevel = (typeof ImportLogLevel)[keyof typeof ImportLogLevel]
