/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `CoverageMetric` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums";
import type * as Prisma from "../internal/prismaNamespace";

/**
 * Model CoverageMetric
 *
 */
export type CoverageMetricModel = runtime.Types.Result.DefaultSelection<Prisma.$CoverageMetricPayload>;

export type AggregateCoverageMetric = {
  _count: CoverageMetricCountAggregateOutputType | null;
  _avg: CoverageMetricAvgAggregateOutputType | null;
  _sum: CoverageMetricSumAggregateOutputType | null;
  _min: CoverageMetricMinAggregateOutputType | null;
  _max: CoverageMetricMaxAggregateOutputType | null;
};

export type CoverageMetricAvgAggregateOutputType = {
  coveragePercent: number | null;
  linesCovered: number | null;
  linesTotal: number | null;
  branchesPercent: number | null;
};

export type CoverageMetricSumAggregateOutputType = {
  coveragePercent: number | null;
  linesCovered: number | null;
  linesTotal: number | null;
  branchesPercent: number | null;
};

export type CoverageMetricMinAggregateOutputType = {
  id: string | null;
  qualityScanId: string | null;
  moduleOrPackage: string | null;
  coveragePercent: number | null;
  linesCovered: number | null;
  linesTotal: number | null;
  branchesPercent: number | null;
  createdAt: Date | null;
  updatedAt: Date | null;
};

export type CoverageMetricMaxAggregateOutputType = {
  id: string | null;
  qualityScanId: string | null;
  moduleOrPackage: string | null;
  coveragePercent: number | null;
  linesCovered: number | null;
  linesTotal: number | null;
  branchesPercent: number | null;
  createdAt: Date | null;
  updatedAt: Date | null;
};

export type CoverageMetricCountAggregateOutputType = {
  id: number;
  qualityScanId: number;
  moduleOrPackage: number;
  coveragePercent: number;
  linesCovered: number;
  linesTotal: number;
  branchesPercent: number;
  createdAt: number;
  updatedAt: number;
  _all: number;
};

export type CoverageMetricAvgAggregateInputType = {
  coveragePercent?: true;
  linesCovered?: true;
  linesTotal?: true;
  branchesPercent?: true;
};

export type CoverageMetricSumAggregateInputType = {
  coveragePercent?: true;
  linesCovered?: true;
  linesTotal?: true;
  branchesPercent?: true;
};

export type CoverageMetricMinAggregateInputType = {
  id?: true;
  qualityScanId?: true;
  moduleOrPackage?: true;
  coveragePercent?: true;
  linesCovered?: true;
  linesTotal?: true;
  branchesPercent?: true;
  createdAt?: true;
  updatedAt?: true;
};

export type CoverageMetricMaxAggregateInputType = {
  id?: true;
  qualityScanId?: true;
  moduleOrPackage?: true;
  coveragePercent?: true;
  linesCovered?: true;
  linesTotal?: true;
  branchesPercent?: true;
  createdAt?: true;
  updatedAt?: true;
};

export type CoverageMetricCountAggregateInputType = {
  id?: true;
  qualityScanId?: true;
  moduleOrPackage?: true;
  coveragePercent?: true;
  linesCovered?: true;
  linesTotal?: true;
  branchesPercent?: true;
  createdAt?: true;
  updatedAt?: true;
  _all?: true;
};

export type CoverageMetricAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CoverageMetric to aggregate.
   */
  where?: Prisma.CoverageMetricWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of CoverageMetrics to fetch.
   */
  orderBy?: Prisma.CoverageMetricOrderByWithRelationInput | Prisma.CoverageMetricOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.CoverageMetricWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` CoverageMetrics from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` CoverageMetrics.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned CoverageMetrics
   **/
  _count?: true | CoverageMetricCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: CoverageMetricAvgAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: CoverageMetricSumAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: CoverageMetricMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: CoverageMetricMaxAggregateInputType;
};

export type GetCoverageMetricAggregateType<T extends CoverageMetricAggregateArgs> = {
  [P in keyof T & keyof AggregateCoverageMetric]: P extends "_count" | "count"
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCoverageMetric[P]>
    : Prisma.GetScalarType<T[P], AggregateCoverageMetric[P]>;
};

export type CoverageMetricGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CoverageMetricWhereInput;
  orderBy?: Prisma.CoverageMetricOrderByWithAggregationInput | Prisma.CoverageMetricOrderByWithAggregationInput[];
  by: Prisma.CoverageMetricScalarFieldEnum[] | Prisma.CoverageMetricScalarFieldEnum;
  having?: Prisma.CoverageMetricScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: CoverageMetricCountAggregateInputType | true;
  _avg?: CoverageMetricAvgAggregateInputType;
  _sum?: CoverageMetricSumAggregateInputType;
  _min?: CoverageMetricMinAggregateInputType;
  _max?: CoverageMetricMaxAggregateInputType;
};

export type CoverageMetricGroupByOutputType = {
  id: string;
  qualityScanId: string;
  moduleOrPackage: string;
  coveragePercent: number;
  linesCovered: number;
  linesTotal: number;
  branchesPercent: number | null;
  createdAt: Date;
  updatedAt: Date;
  _count: CoverageMetricCountAggregateOutputType | null;
  _avg: CoverageMetricAvgAggregateOutputType | null;
  _sum: CoverageMetricSumAggregateOutputType | null;
  _min: CoverageMetricMinAggregateOutputType | null;
  _max: CoverageMetricMaxAggregateOutputType | null;
};

type GetCoverageMetricGroupByPayload<T extends CoverageMetricGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CoverageMetricGroupByOutputType, T["by"]> & {
      [P in keyof T & keyof CoverageMetricGroupByOutputType]: P extends "_count"
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<T[P], CoverageMetricGroupByOutputType[P]>
        : Prisma.GetScalarType<T[P], CoverageMetricGroupByOutputType[P]>;
    }
  >
>;

export type CoverageMetricWhereInput = {
  AND?: Prisma.CoverageMetricWhereInput | Prisma.CoverageMetricWhereInput[];
  OR?: Prisma.CoverageMetricWhereInput[];
  NOT?: Prisma.CoverageMetricWhereInput | Prisma.CoverageMetricWhereInput[];
  id?: Prisma.StringFilter<"CoverageMetric"> | string;
  qualityScanId?: Prisma.StringFilter<"CoverageMetric"> | string;
  moduleOrPackage?: Prisma.StringFilter<"CoverageMetric"> | string;
  coveragePercent?: Prisma.FloatFilter<"CoverageMetric"> | number;
  linesCovered?: Prisma.IntFilter<"CoverageMetric"> | number;
  linesTotal?: Prisma.IntFilter<"CoverageMetric"> | number;
  branchesPercent?: Prisma.FloatNullableFilter<"CoverageMetric"> | number | null;
  createdAt?: Prisma.DateTimeFilter<"CoverageMetric"> | Date | string;
  updatedAt?: Prisma.DateTimeFilter<"CoverageMetric"> | Date | string;
  qualityScan?: Prisma.XOR<Prisma.QualityScanScalarRelationFilter, Prisma.QualityScanWhereInput>;
};

export type CoverageMetricOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  qualityScanId?: Prisma.SortOrder;
  moduleOrPackage?: Prisma.SortOrder;
  coveragePercent?: Prisma.SortOrder;
  linesCovered?: Prisma.SortOrder;
  linesTotal?: Prisma.SortOrder;
  branchesPercent?: Prisma.SortOrderInput | Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  qualityScan?: Prisma.QualityScanOrderByWithRelationInput;
};

export type CoverageMetricWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string;
    AND?: Prisma.CoverageMetricWhereInput | Prisma.CoverageMetricWhereInput[];
    OR?: Prisma.CoverageMetricWhereInput[];
    NOT?: Prisma.CoverageMetricWhereInput | Prisma.CoverageMetricWhereInput[];
    qualityScanId?: Prisma.StringFilter<"CoverageMetric"> | string;
    moduleOrPackage?: Prisma.StringFilter<"CoverageMetric"> | string;
    coveragePercent?: Prisma.FloatFilter<"CoverageMetric"> | number;
    linesCovered?: Prisma.IntFilter<"CoverageMetric"> | number;
    linesTotal?: Prisma.IntFilter<"CoverageMetric"> | number;
    branchesPercent?: Prisma.FloatNullableFilter<"CoverageMetric"> | number | null;
    createdAt?: Prisma.DateTimeFilter<"CoverageMetric"> | Date | string;
    updatedAt?: Prisma.DateTimeFilter<"CoverageMetric"> | Date | string;
    qualityScan?: Prisma.XOR<Prisma.QualityScanScalarRelationFilter, Prisma.QualityScanWhereInput>;
  },
  "id"
>;

export type CoverageMetricOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  qualityScanId?: Prisma.SortOrder;
  moduleOrPackage?: Prisma.SortOrder;
  coveragePercent?: Prisma.SortOrder;
  linesCovered?: Prisma.SortOrder;
  linesTotal?: Prisma.SortOrder;
  branchesPercent?: Prisma.SortOrderInput | Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  _count?: Prisma.CoverageMetricCountOrderByAggregateInput;
  _avg?: Prisma.CoverageMetricAvgOrderByAggregateInput;
  _max?: Prisma.CoverageMetricMaxOrderByAggregateInput;
  _min?: Prisma.CoverageMetricMinOrderByAggregateInput;
  _sum?: Prisma.CoverageMetricSumOrderByAggregateInput;
};

export type CoverageMetricScalarWhereWithAggregatesInput = {
  AND?: Prisma.CoverageMetricScalarWhereWithAggregatesInput | Prisma.CoverageMetricScalarWhereWithAggregatesInput[];
  OR?: Prisma.CoverageMetricScalarWhereWithAggregatesInput[];
  NOT?: Prisma.CoverageMetricScalarWhereWithAggregatesInput | Prisma.CoverageMetricScalarWhereWithAggregatesInput[];
  id?: Prisma.StringWithAggregatesFilter<"CoverageMetric"> | string;
  qualityScanId?: Prisma.StringWithAggregatesFilter<"CoverageMetric"> | string;
  moduleOrPackage?: Prisma.StringWithAggregatesFilter<"CoverageMetric"> | string;
  coveragePercent?: Prisma.FloatWithAggregatesFilter<"CoverageMetric"> | number;
  linesCovered?: Prisma.IntWithAggregatesFilter<"CoverageMetric"> | number;
  linesTotal?: Prisma.IntWithAggregatesFilter<"CoverageMetric"> | number;
  branchesPercent?: Prisma.FloatNullableWithAggregatesFilter<"CoverageMetric"> | number | null;
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CoverageMetric"> | Date | string;
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CoverageMetric"> | Date | string;
};

export type CoverageMetricCreateInput = {
  id?: string;
  moduleOrPackage: string;
  coveragePercent: number;
  linesCovered: number;
  linesTotal: number;
  branchesPercent?: number | null;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  qualityScan: Prisma.QualityScanCreateNestedOneWithoutCoverageMetricsInput;
};

export type CoverageMetricUncheckedCreateInput = {
  id?: string;
  qualityScanId: string;
  moduleOrPackage: string;
  coveragePercent: number;
  linesCovered: number;
  linesTotal: number;
  branchesPercent?: number | null;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type CoverageMetricUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  moduleOrPackage?: Prisma.StringFieldUpdateOperationsInput | string;
  coveragePercent?: Prisma.FloatFieldUpdateOperationsInput | number;
  linesCovered?: Prisma.IntFieldUpdateOperationsInput | number;
  linesTotal?: Prisma.IntFieldUpdateOperationsInput | number;
  branchesPercent?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  qualityScan?: Prisma.QualityScanUpdateOneRequiredWithoutCoverageMetricsNestedInput;
};

export type CoverageMetricUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  qualityScanId?: Prisma.StringFieldUpdateOperationsInput | string;
  moduleOrPackage?: Prisma.StringFieldUpdateOperationsInput | string;
  coveragePercent?: Prisma.FloatFieldUpdateOperationsInput | number;
  linesCovered?: Prisma.IntFieldUpdateOperationsInput | number;
  linesTotal?: Prisma.IntFieldUpdateOperationsInput | number;
  branchesPercent?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type CoverageMetricCreateManyInput = {
  id?: string;
  qualityScanId: string;
  moduleOrPackage: string;
  coveragePercent: number;
  linesCovered: number;
  linesTotal: number;
  branchesPercent?: number | null;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type CoverageMetricUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  moduleOrPackage?: Prisma.StringFieldUpdateOperationsInput | string;
  coveragePercent?: Prisma.FloatFieldUpdateOperationsInput | number;
  linesCovered?: Prisma.IntFieldUpdateOperationsInput | number;
  linesTotal?: Prisma.IntFieldUpdateOperationsInput | number;
  branchesPercent?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type CoverageMetricUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  qualityScanId?: Prisma.StringFieldUpdateOperationsInput | string;
  moduleOrPackage?: Prisma.StringFieldUpdateOperationsInput | string;
  coveragePercent?: Prisma.FloatFieldUpdateOperationsInput | number;
  linesCovered?: Prisma.IntFieldUpdateOperationsInput | number;
  linesTotal?: Prisma.IntFieldUpdateOperationsInput | number;
  branchesPercent?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type CoverageMetricListRelationFilter = {
  every?: Prisma.CoverageMetricWhereInput;
  some?: Prisma.CoverageMetricWhereInput;
  none?: Prisma.CoverageMetricWhereInput;
};

export type CoverageMetricOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder;
};

export type CoverageMetricCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  qualityScanId?: Prisma.SortOrder;
  moduleOrPackage?: Prisma.SortOrder;
  coveragePercent?: Prisma.SortOrder;
  linesCovered?: Prisma.SortOrder;
  linesTotal?: Prisma.SortOrder;
  branchesPercent?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type CoverageMetricAvgOrderByAggregateInput = {
  coveragePercent?: Prisma.SortOrder;
  linesCovered?: Prisma.SortOrder;
  linesTotal?: Prisma.SortOrder;
  branchesPercent?: Prisma.SortOrder;
};

export type CoverageMetricMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  qualityScanId?: Prisma.SortOrder;
  moduleOrPackage?: Prisma.SortOrder;
  coveragePercent?: Prisma.SortOrder;
  linesCovered?: Prisma.SortOrder;
  linesTotal?: Prisma.SortOrder;
  branchesPercent?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type CoverageMetricMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  qualityScanId?: Prisma.SortOrder;
  moduleOrPackage?: Prisma.SortOrder;
  coveragePercent?: Prisma.SortOrder;
  linesCovered?: Prisma.SortOrder;
  linesTotal?: Prisma.SortOrder;
  branchesPercent?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type CoverageMetricSumOrderByAggregateInput = {
  coveragePercent?: Prisma.SortOrder;
  linesCovered?: Prisma.SortOrder;
  linesTotal?: Prisma.SortOrder;
  branchesPercent?: Prisma.SortOrder;
};

export type CoverageMetricCreateNestedManyWithoutQualityScanInput = {
  create?:
    | Prisma.XOR<Prisma.CoverageMetricCreateWithoutQualityScanInput, Prisma.CoverageMetricUncheckedCreateWithoutQualityScanInput>
    | Prisma.CoverageMetricCreateWithoutQualityScanInput[]
    | Prisma.CoverageMetricUncheckedCreateWithoutQualityScanInput[];
  connectOrCreate?: Prisma.CoverageMetricCreateOrConnectWithoutQualityScanInput | Prisma.CoverageMetricCreateOrConnectWithoutQualityScanInput[];
  createMany?: Prisma.CoverageMetricCreateManyQualityScanInputEnvelope;
  connect?: Prisma.CoverageMetricWhereUniqueInput | Prisma.CoverageMetricWhereUniqueInput[];
};

export type CoverageMetricUncheckedCreateNestedManyWithoutQualityScanInput = {
  create?:
    | Prisma.XOR<Prisma.CoverageMetricCreateWithoutQualityScanInput, Prisma.CoverageMetricUncheckedCreateWithoutQualityScanInput>
    | Prisma.CoverageMetricCreateWithoutQualityScanInput[]
    | Prisma.CoverageMetricUncheckedCreateWithoutQualityScanInput[];
  connectOrCreate?: Prisma.CoverageMetricCreateOrConnectWithoutQualityScanInput | Prisma.CoverageMetricCreateOrConnectWithoutQualityScanInput[];
  createMany?: Prisma.CoverageMetricCreateManyQualityScanInputEnvelope;
  connect?: Prisma.CoverageMetricWhereUniqueInput | Prisma.CoverageMetricWhereUniqueInput[];
};

export type CoverageMetricUpdateManyWithoutQualityScanNestedInput = {
  create?:
    | Prisma.XOR<Prisma.CoverageMetricCreateWithoutQualityScanInput, Prisma.CoverageMetricUncheckedCreateWithoutQualityScanInput>
    | Prisma.CoverageMetricCreateWithoutQualityScanInput[]
    | Prisma.CoverageMetricUncheckedCreateWithoutQualityScanInput[];
  connectOrCreate?: Prisma.CoverageMetricCreateOrConnectWithoutQualityScanInput | Prisma.CoverageMetricCreateOrConnectWithoutQualityScanInput[];
  upsert?: Prisma.CoverageMetricUpsertWithWhereUniqueWithoutQualityScanInput | Prisma.CoverageMetricUpsertWithWhereUniqueWithoutQualityScanInput[];
  createMany?: Prisma.CoverageMetricCreateManyQualityScanInputEnvelope;
  set?: Prisma.CoverageMetricWhereUniqueInput | Prisma.CoverageMetricWhereUniqueInput[];
  disconnect?: Prisma.CoverageMetricWhereUniqueInput | Prisma.CoverageMetricWhereUniqueInput[];
  delete?: Prisma.CoverageMetricWhereUniqueInput | Prisma.CoverageMetricWhereUniqueInput[];
  connect?: Prisma.CoverageMetricWhereUniqueInput | Prisma.CoverageMetricWhereUniqueInput[];
  update?: Prisma.CoverageMetricUpdateWithWhereUniqueWithoutQualityScanInput | Prisma.CoverageMetricUpdateWithWhereUniqueWithoutQualityScanInput[];
  updateMany?: Prisma.CoverageMetricUpdateManyWithWhereWithoutQualityScanInput | Prisma.CoverageMetricUpdateManyWithWhereWithoutQualityScanInput[];
  deleteMany?: Prisma.CoverageMetricScalarWhereInput | Prisma.CoverageMetricScalarWhereInput[];
};

export type CoverageMetricUncheckedUpdateManyWithoutQualityScanNestedInput = {
  create?:
    | Prisma.XOR<Prisma.CoverageMetricCreateWithoutQualityScanInput, Prisma.CoverageMetricUncheckedCreateWithoutQualityScanInput>
    | Prisma.CoverageMetricCreateWithoutQualityScanInput[]
    | Prisma.CoverageMetricUncheckedCreateWithoutQualityScanInput[];
  connectOrCreate?: Prisma.CoverageMetricCreateOrConnectWithoutQualityScanInput | Prisma.CoverageMetricCreateOrConnectWithoutQualityScanInput[];
  upsert?: Prisma.CoverageMetricUpsertWithWhereUniqueWithoutQualityScanInput | Prisma.CoverageMetricUpsertWithWhereUniqueWithoutQualityScanInput[];
  createMany?: Prisma.CoverageMetricCreateManyQualityScanInputEnvelope;
  set?: Prisma.CoverageMetricWhereUniqueInput | Prisma.CoverageMetricWhereUniqueInput[];
  disconnect?: Prisma.CoverageMetricWhereUniqueInput | Prisma.CoverageMetricWhereUniqueInput[];
  delete?: Prisma.CoverageMetricWhereUniqueInput | Prisma.CoverageMetricWhereUniqueInput[];
  connect?: Prisma.CoverageMetricWhereUniqueInput | Prisma.CoverageMetricWhereUniqueInput[];
  update?: Prisma.CoverageMetricUpdateWithWhereUniqueWithoutQualityScanInput | Prisma.CoverageMetricUpdateWithWhereUniqueWithoutQualityScanInput[];
  updateMany?: Prisma.CoverageMetricUpdateManyWithWhereWithoutQualityScanInput | Prisma.CoverageMetricUpdateManyWithWhereWithoutQualityScanInput[];
  deleteMany?: Prisma.CoverageMetricScalarWhereInput | Prisma.CoverageMetricScalarWhereInput[];
};

export type FloatFieldUpdateOperationsInput = {
  set?: number;
  increment?: number;
  decrement?: number;
  multiply?: number;
  divide?: number;
};

export type CoverageMetricCreateWithoutQualityScanInput = {
  id?: string;
  moduleOrPackage: string;
  coveragePercent: number;
  linesCovered: number;
  linesTotal: number;
  branchesPercent?: number | null;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type CoverageMetricUncheckedCreateWithoutQualityScanInput = {
  id?: string;
  moduleOrPackage: string;
  coveragePercent: number;
  linesCovered: number;
  linesTotal: number;
  branchesPercent?: number | null;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type CoverageMetricCreateOrConnectWithoutQualityScanInput = {
  where: Prisma.CoverageMetricWhereUniqueInput;
  create: Prisma.XOR<Prisma.CoverageMetricCreateWithoutQualityScanInput, Prisma.CoverageMetricUncheckedCreateWithoutQualityScanInput>;
};

export type CoverageMetricCreateManyQualityScanInputEnvelope = {
  data: Prisma.CoverageMetricCreateManyQualityScanInput | Prisma.CoverageMetricCreateManyQualityScanInput[];
  skipDuplicates?: boolean;
};

export type CoverageMetricUpsertWithWhereUniqueWithoutQualityScanInput = {
  where: Prisma.CoverageMetricWhereUniqueInput;
  update: Prisma.XOR<Prisma.CoverageMetricUpdateWithoutQualityScanInput, Prisma.CoverageMetricUncheckedUpdateWithoutQualityScanInput>;
  create: Prisma.XOR<Prisma.CoverageMetricCreateWithoutQualityScanInput, Prisma.CoverageMetricUncheckedCreateWithoutQualityScanInput>;
};

export type CoverageMetricUpdateWithWhereUniqueWithoutQualityScanInput = {
  where: Prisma.CoverageMetricWhereUniqueInput;
  data: Prisma.XOR<Prisma.CoverageMetricUpdateWithoutQualityScanInput, Prisma.CoverageMetricUncheckedUpdateWithoutQualityScanInput>;
};

export type CoverageMetricUpdateManyWithWhereWithoutQualityScanInput = {
  where: Prisma.CoverageMetricScalarWhereInput;
  data: Prisma.XOR<Prisma.CoverageMetricUpdateManyMutationInput, Prisma.CoverageMetricUncheckedUpdateManyWithoutQualityScanInput>;
};

export type CoverageMetricScalarWhereInput = {
  AND?: Prisma.CoverageMetricScalarWhereInput | Prisma.CoverageMetricScalarWhereInput[];
  OR?: Prisma.CoverageMetricScalarWhereInput[];
  NOT?: Prisma.CoverageMetricScalarWhereInput | Prisma.CoverageMetricScalarWhereInput[];
  id?: Prisma.StringFilter<"CoverageMetric"> | string;
  qualityScanId?: Prisma.StringFilter<"CoverageMetric"> | string;
  moduleOrPackage?: Prisma.StringFilter<"CoverageMetric"> | string;
  coveragePercent?: Prisma.FloatFilter<"CoverageMetric"> | number;
  linesCovered?: Prisma.IntFilter<"CoverageMetric"> | number;
  linesTotal?: Prisma.IntFilter<"CoverageMetric"> | number;
  branchesPercent?: Prisma.FloatNullableFilter<"CoverageMetric"> | number | null;
  createdAt?: Prisma.DateTimeFilter<"CoverageMetric"> | Date | string;
  updatedAt?: Prisma.DateTimeFilter<"CoverageMetric"> | Date | string;
};

export type CoverageMetricCreateManyQualityScanInput = {
  id?: string;
  moduleOrPackage: string;
  coveragePercent: number;
  linesCovered: number;
  linesTotal: number;
  branchesPercent?: number | null;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type CoverageMetricUpdateWithoutQualityScanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  moduleOrPackage?: Prisma.StringFieldUpdateOperationsInput | string;
  coveragePercent?: Prisma.FloatFieldUpdateOperationsInput | number;
  linesCovered?: Prisma.IntFieldUpdateOperationsInput | number;
  linesTotal?: Prisma.IntFieldUpdateOperationsInput | number;
  branchesPercent?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type CoverageMetricUncheckedUpdateWithoutQualityScanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  moduleOrPackage?: Prisma.StringFieldUpdateOperationsInput | string;
  coveragePercent?: Prisma.FloatFieldUpdateOperationsInput | number;
  linesCovered?: Prisma.IntFieldUpdateOperationsInput | number;
  linesTotal?: Prisma.IntFieldUpdateOperationsInput | number;
  branchesPercent?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type CoverageMetricUncheckedUpdateManyWithoutQualityScanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  moduleOrPackage?: Prisma.StringFieldUpdateOperationsInput | string;
  coveragePercent?: Prisma.FloatFieldUpdateOperationsInput | number;
  linesCovered?: Prisma.IntFieldUpdateOperationsInput | number;
  linesTotal?: Prisma.IntFieldUpdateOperationsInput | number;
  branchesPercent?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type CoverageMetricSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    qualityScanId?: boolean;
    moduleOrPackage?: boolean;
    coveragePercent?: boolean;
    linesCovered?: boolean;
    linesTotal?: boolean;
    branchesPercent?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
    qualityScan?: boolean | Prisma.QualityScanDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["coverageMetric"]
>;

export type CoverageMetricSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  runtime.Types.Extensions.GetSelect<
    {
      id?: boolean;
      qualityScanId?: boolean;
      moduleOrPackage?: boolean;
      coveragePercent?: boolean;
      linesCovered?: boolean;
      linesTotal?: boolean;
      branchesPercent?: boolean;
      createdAt?: boolean;
      updatedAt?: boolean;
      qualityScan?: boolean | Prisma.QualityScanDefaultArgs<ExtArgs>;
    },
    ExtArgs["result"]["coverageMetric"]
  >;

export type CoverageMetricSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  runtime.Types.Extensions.GetSelect<
    {
      id?: boolean;
      qualityScanId?: boolean;
      moduleOrPackage?: boolean;
      coveragePercent?: boolean;
      linesCovered?: boolean;
      linesTotal?: boolean;
      branchesPercent?: boolean;
      createdAt?: boolean;
      updatedAt?: boolean;
      qualityScan?: boolean | Prisma.QualityScanDefaultArgs<ExtArgs>;
    },
    ExtArgs["result"]["coverageMetric"]
  >;

export type CoverageMetricSelectScalar = {
  id?: boolean;
  qualityScanId?: boolean;
  moduleOrPackage?: boolean;
  coveragePercent?: boolean;
  linesCovered?: boolean;
  linesTotal?: boolean;
  branchesPercent?: boolean;
  createdAt?: boolean;
  updatedAt?: boolean;
};

export type CoverageMetricOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<
  "id" | "qualityScanId" | "moduleOrPackage" | "coveragePercent" | "linesCovered" | "linesTotal" | "branchesPercent" | "createdAt" | "updatedAt",
  ExtArgs["result"]["coverageMetric"]
>;
export type CoverageMetricInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  qualityScan?: boolean | Prisma.QualityScanDefaultArgs<ExtArgs>;
};
export type CoverageMetricIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  qualityScan?: boolean | Prisma.QualityScanDefaultArgs<ExtArgs>;
};
export type CoverageMetricIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  qualityScan?: boolean | Prisma.QualityScanDefaultArgs<ExtArgs>;
};

export type $CoverageMetricPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CoverageMetric";
  objects: {
    qualityScan: Prisma.$QualityScanPayload<ExtArgs>;
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string;
      qualityScanId: string;
      moduleOrPackage: string;
      coveragePercent: number;
      linesCovered: number;
      linesTotal: number;
      branchesPercent: number | null;
      createdAt: Date;
      updatedAt: Date;
    },
    ExtArgs["result"]["coverageMetric"]
  >;
  composites: {};
};

export type CoverageMetricGetPayload<S extends boolean | null | undefined | CoverageMetricDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CoverageMetricPayload, S>;

export type CoverageMetricCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = Omit<
  CoverageMetricFindManyArgs,
  "select" | "include" | "distinct" | "omit"
> & {
  select?: CoverageMetricCountAggregateInputType | true;
};

export interface CoverageMetricDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>["model"]["CoverageMetric"]; meta: { name: "CoverageMetric" } };
  /**
   * Find zero or one CoverageMetric that matches the filter.
   * @param {CoverageMetricFindUniqueArgs} args - Arguments to find a CoverageMetric
   * @example
   * // Get one CoverageMetric
   * const coverageMetric = await prisma.coverageMetric.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CoverageMetricFindUniqueArgs>(
    args: Prisma.SelectSubset<T, CoverageMetricFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__CoverageMetricClient<
    runtime.Types.Result.GetResult<Prisma.$CoverageMetricPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one CoverageMetric that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CoverageMetricFindUniqueOrThrowArgs} args - Arguments to find a CoverageMetric
   * @example
   * // Get one CoverageMetric
   * const coverageMetric = await prisma.coverageMetric.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CoverageMetricFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, CoverageMetricFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__CoverageMetricClient<
    runtime.Types.Result.GetResult<Prisma.$CoverageMetricPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first CoverageMetric that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CoverageMetricFindFirstArgs} args - Arguments to find a CoverageMetric
   * @example
   * // Get one CoverageMetric
   * const coverageMetric = await prisma.coverageMetric.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CoverageMetricFindFirstArgs>(
    args?: Prisma.SelectSubset<T, CoverageMetricFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__CoverageMetricClient<
    runtime.Types.Result.GetResult<Prisma.$CoverageMetricPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first CoverageMetric that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CoverageMetricFindFirstOrThrowArgs} args - Arguments to find a CoverageMetric
   * @example
   * // Get one CoverageMetric
   * const coverageMetric = await prisma.coverageMetric.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CoverageMetricFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, CoverageMetricFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__CoverageMetricClient<
    runtime.Types.Result.GetResult<Prisma.$CoverageMetricPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more CoverageMetrics that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CoverageMetricFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CoverageMetrics
   * const coverageMetrics = await prisma.coverageMetric.findMany()
   *
   * // Get first 10 CoverageMetrics
   * const coverageMetrics = await prisma.coverageMetric.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const coverageMetricWithIdOnly = await prisma.coverageMetric.findMany({ select: { id: true } })
   *
   */
  findMany<T extends CoverageMetricFindManyArgs>(
    args?: Prisma.SelectSubset<T, CoverageMetricFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CoverageMetricPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>;

  /**
   * Create a CoverageMetric.
   * @param {CoverageMetricCreateArgs} args - Arguments to create a CoverageMetric.
   * @example
   * // Create one CoverageMetric
   * const CoverageMetric = await prisma.coverageMetric.create({
   *   data: {
   *     // ... data to create a CoverageMetric
   *   }
   * })
   *
   */
  create<T extends CoverageMetricCreateArgs>(
    args: Prisma.SelectSubset<T, CoverageMetricCreateArgs<ExtArgs>>
  ): Prisma.Prisma__CoverageMetricClient<runtime.Types.Result.GetResult<Prisma.$CoverageMetricPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;

  /**
   * Create many CoverageMetrics.
   * @param {CoverageMetricCreateManyArgs} args - Arguments to create many CoverageMetrics.
   * @example
   * // Create many CoverageMetrics
   * const coverageMetric = await prisma.coverageMetric.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends CoverageMetricCreateManyArgs>(args?: Prisma.SelectSubset<T, CoverageMetricCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many CoverageMetrics and returns the data saved in the database.
   * @param {CoverageMetricCreateManyAndReturnArgs} args - Arguments to create many CoverageMetrics.
   * @example
   * // Create many CoverageMetrics
   * const coverageMetric = await prisma.coverageMetric.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many CoverageMetrics and only return the `id`
   * const coverageMetricWithIdOnly = await prisma.coverageMetric.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends CoverageMetricCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, CoverageMetricCreateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CoverageMetricPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>;

  /**
   * Delete a CoverageMetric.
   * @param {CoverageMetricDeleteArgs} args - Arguments to delete one CoverageMetric.
   * @example
   * // Delete one CoverageMetric
   * const CoverageMetric = await prisma.coverageMetric.delete({
   *   where: {
   *     // ... filter to delete one CoverageMetric
   *   }
   * })
   *
   */
  delete<T extends CoverageMetricDeleteArgs>(
    args: Prisma.SelectSubset<T, CoverageMetricDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__CoverageMetricClient<runtime.Types.Result.GetResult<Prisma.$CoverageMetricPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;

  /**
   * Update one CoverageMetric.
   * @param {CoverageMetricUpdateArgs} args - Arguments to update one CoverageMetric.
   * @example
   * // Update one CoverageMetric
   * const coverageMetric = await prisma.coverageMetric.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends CoverageMetricUpdateArgs>(
    args: Prisma.SelectSubset<T, CoverageMetricUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__CoverageMetricClient<runtime.Types.Result.GetResult<Prisma.$CoverageMetricPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;

  /**
   * Delete zero or more CoverageMetrics.
   * @param {CoverageMetricDeleteManyArgs} args - Arguments to filter CoverageMetrics to delete.
   * @example
   * // Delete a few CoverageMetrics
   * const { count } = await prisma.coverageMetric.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends CoverageMetricDeleteManyArgs>(args?: Prisma.SelectSubset<T, CoverageMetricDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more CoverageMetrics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CoverageMetricUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CoverageMetrics
   * const coverageMetric = await prisma.coverageMetric.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends CoverageMetricUpdateManyArgs>(args: Prisma.SelectSubset<T, CoverageMetricUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more CoverageMetrics and returns the data updated in the database.
   * @param {CoverageMetricUpdateManyAndReturnArgs} args - Arguments to update many CoverageMetrics.
   * @example
   * // Update many CoverageMetrics
   * const coverageMetric = await prisma.coverageMetric.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more CoverageMetrics and only return the `id`
   * const coverageMetricWithIdOnly = await prisma.coverageMetric.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends CoverageMetricUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, CoverageMetricUpdateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CoverageMetricPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>;

  /**
   * Create or update one CoverageMetric.
   * @param {CoverageMetricUpsertArgs} args - Arguments to update or create a CoverageMetric.
   * @example
   * // Update or create a CoverageMetric
   * const coverageMetric = await prisma.coverageMetric.upsert({
   *   create: {
   *     // ... data to create a CoverageMetric
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CoverageMetric we want to update
   *   }
   * })
   */
  upsert<T extends CoverageMetricUpsertArgs>(
    args: Prisma.SelectSubset<T, CoverageMetricUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__CoverageMetricClient<runtime.Types.Result.GetResult<Prisma.$CoverageMetricPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;

  /**
   * Count the number of CoverageMetrics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CoverageMetricCountArgs} args - Arguments to filter CoverageMetrics to count.
   * @example
   * // Count the number of CoverageMetrics
   * const count = await prisma.coverageMetric.count({
   *   where: {
   *     // ... the filter for the CoverageMetrics we want to count
   *   }
   * })
   **/
  count<T extends CoverageMetricCountArgs>(
    args?: Prisma.Subset<T, CoverageMetricCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<"select", any> ? (T["select"] extends true ? number : Prisma.GetScalarType<T["select"], CoverageMetricCountAggregateOutputType>) : number
  >;

  /**
   * Allows you to perform aggregations operations on a CoverageMetric.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CoverageMetricAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends CoverageMetricAggregateArgs>(args: Prisma.Subset<T, CoverageMetricAggregateArgs>): Prisma.PrismaPromise<GetCoverageMetricAggregateType<T>>;

  /**
   * Group by CoverageMetric.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CoverageMetricGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends CoverageMetricGroupByArgs,
    HasSelectOrTake extends Prisma.Or<Prisma.Extends<"skip", Prisma.Keys<T>>, Prisma.Extends<"take", Prisma.Keys<T>>>,
    OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: CoverageMetricGroupByArgs["orderBy"] } : { orderBy?: CoverageMetricGroupByArgs["orderBy"] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T["having"]>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, "Field ", P, ` in "having" needs to be provided in "by"`];
          }[HavingFields]
        : "take" extends Prisma.Keys<T>
          ? "orderBy" extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : "skip" extends Prisma.Keys<T>
            ? "orderBy" extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, CoverageMetricGroupByArgs, OrderByArg> & InputErrors
  ): {} extends InputErrors ? GetCoverageMetricGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the CoverageMetric model
   */
  readonly fields: CoverageMetricFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CoverageMetric.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CoverageMetricClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}>
  extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise";
  qualityScan<T extends Prisma.QualityScanDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.QualityScanDefaultArgs<ExtArgs>>
  ): Prisma.Prisma__QualityScanClient<
    runtime.Types.Result.GetResult<Prisma.$QualityScanPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the CoverageMetric model
 */
export interface CoverageMetricFieldRefs {
  readonly id: Prisma.FieldRef<"CoverageMetric", "String">;
  readonly qualityScanId: Prisma.FieldRef<"CoverageMetric", "String">;
  readonly moduleOrPackage: Prisma.FieldRef<"CoverageMetric", "String">;
  readonly coveragePercent: Prisma.FieldRef<"CoverageMetric", "Float">;
  readonly linesCovered: Prisma.FieldRef<"CoverageMetric", "Int">;
  readonly linesTotal: Prisma.FieldRef<"CoverageMetric", "Int">;
  readonly branchesPercent: Prisma.FieldRef<"CoverageMetric", "Float">;
  readonly createdAt: Prisma.FieldRef<"CoverageMetric", "DateTime">;
  readonly updatedAt: Prisma.FieldRef<"CoverageMetric", "DateTime">;
}

// Custom InputTypes
/**
 * CoverageMetric findUnique
 */
export type CoverageMetricFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CoverageMetric
   */
  select?: Prisma.CoverageMetricSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CoverageMetric
   */
  omit?: Prisma.CoverageMetricOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CoverageMetricInclude<ExtArgs> | null;
  /**
   * Filter, which CoverageMetric to fetch.
   */
  where: Prisma.CoverageMetricWhereUniqueInput;
};

/**
 * CoverageMetric findUniqueOrThrow
 */
export type CoverageMetricFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CoverageMetric
   */
  select?: Prisma.CoverageMetricSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CoverageMetric
   */
  omit?: Prisma.CoverageMetricOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CoverageMetricInclude<ExtArgs> | null;
  /**
   * Filter, which CoverageMetric to fetch.
   */
  where: Prisma.CoverageMetricWhereUniqueInput;
};

/**
 * CoverageMetric findFirst
 */
export type CoverageMetricFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CoverageMetric
   */
  select?: Prisma.CoverageMetricSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CoverageMetric
   */
  omit?: Prisma.CoverageMetricOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CoverageMetricInclude<ExtArgs> | null;
  /**
   * Filter, which CoverageMetric to fetch.
   */
  where?: Prisma.CoverageMetricWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of CoverageMetrics to fetch.
   */
  orderBy?: Prisma.CoverageMetricOrderByWithRelationInput | Prisma.CoverageMetricOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for CoverageMetrics.
   */
  cursor?: Prisma.CoverageMetricWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` CoverageMetrics from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` CoverageMetrics.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of CoverageMetrics.
   */
  distinct?: Prisma.CoverageMetricScalarFieldEnum | Prisma.CoverageMetricScalarFieldEnum[];
};

/**
 * CoverageMetric findFirstOrThrow
 */
export type CoverageMetricFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CoverageMetric
   */
  select?: Prisma.CoverageMetricSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CoverageMetric
   */
  omit?: Prisma.CoverageMetricOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CoverageMetricInclude<ExtArgs> | null;
  /**
   * Filter, which CoverageMetric to fetch.
   */
  where?: Prisma.CoverageMetricWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of CoverageMetrics to fetch.
   */
  orderBy?: Prisma.CoverageMetricOrderByWithRelationInput | Prisma.CoverageMetricOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for CoverageMetrics.
   */
  cursor?: Prisma.CoverageMetricWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` CoverageMetrics from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` CoverageMetrics.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of CoverageMetrics.
   */
  distinct?: Prisma.CoverageMetricScalarFieldEnum | Prisma.CoverageMetricScalarFieldEnum[];
};

/**
 * CoverageMetric findMany
 */
export type CoverageMetricFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CoverageMetric
   */
  select?: Prisma.CoverageMetricSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CoverageMetric
   */
  omit?: Prisma.CoverageMetricOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CoverageMetricInclude<ExtArgs> | null;
  /**
   * Filter, which CoverageMetrics to fetch.
   */
  where?: Prisma.CoverageMetricWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of CoverageMetrics to fetch.
   */
  orderBy?: Prisma.CoverageMetricOrderByWithRelationInput | Prisma.CoverageMetricOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing CoverageMetrics.
   */
  cursor?: Prisma.CoverageMetricWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` CoverageMetrics from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` CoverageMetrics.
   */
  skip?: number;
  distinct?: Prisma.CoverageMetricScalarFieldEnum | Prisma.CoverageMetricScalarFieldEnum[];
};

/**
 * CoverageMetric create
 */
export type CoverageMetricCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CoverageMetric
   */
  select?: Prisma.CoverageMetricSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CoverageMetric
   */
  omit?: Prisma.CoverageMetricOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CoverageMetricInclude<ExtArgs> | null;
  /**
   * The data needed to create a CoverageMetric.
   */
  data: Prisma.XOR<Prisma.CoverageMetricCreateInput, Prisma.CoverageMetricUncheckedCreateInput>;
};

/**
 * CoverageMetric createMany
 */
export type CoverageMetricCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CoverageMetrics.
   */
  data: Prisma.CoverageMetricCreateManyInput | Prisma.CoverageMetricCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * CoverageMetric createManyAndReturn
 */
export type CoverageMetricCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CoverageMetric
   */
  select?: Prisma.CoverageMetricSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the CoverageMetric
   */
  omit?: Prisma.CoverageMetricOmit<ExtArgs> | null;
  /**
   * The data used to create many CoverageMetrics.
   */
  data: Prisma.CoverageMetricCreateManyInput | Prisma.CoverageMetricCreateManyInput[];
  skipDuplicates?: boolean;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CoverageMetricIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * CoverageMetric update
 */
export type CoverageMetricUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CoverageMetric
   */
  select?: Prisma.CoverageMetricSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CoverageMetric
   */
  omit?: Prisma.CoverageMetricOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CoverageMetricInclude<ExtArgs> | null;
  /**
   * The data needed to update a CoverageMetric.
   */
  data: Prisma.XOR<Prisma.CoverageMetricUpdateInput, Prisma.CoverageMetricUncheckedUpdateInput>;
  /**
   * Choose, which CoverageMetric to update.
   */
  where: Prisma.CoverageMetricWhereUniqueInput;
};

/**
 * CoverageMetric updateMany
 */
export type CoverageMetricUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CoverageMetrics.
   */
  data: Prisma.XOR<Prisma.CoverageMetricUpdateManyMutationInput, Prisma.CoverageMetricUncheckedUpdateManyInput>;
  /**
   * Filter which CoverageMetrics to update
   */
  where?: Prisma.CoverageMetricWhereInput;
  /**
   * Limit how many CoverageMetrics to update.
   */
  limit?: number;
};

/**
 * CoverageMetric updateManyAndReturn
 */
export type CoverageMetricUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CoverageMetric
   */
  select?: Prisma.CoverageMetricSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the CoverageMetric
   */
  omit?: Prisma.CoverageMetricOmit<ExtArgs> | null;
  /**
   * The data used to update CoverageMetrics.
   */
  data: Prisma.XOR<Prisma.CoverageMetricUpdateManyMutationInput, Prisma.CoverageMetricUncheckedUpdateManyInput>;
  /**
   * Filter which CoverageMetrics to update
   */
  where?: Prisma.CoverageMetricWhereInput;
  /**
   * Limit how many CoverageMetrics to update.
   */
  limit?: number;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CoverageMetricIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * CoverageMetric upsert
 */
export type CoverageMetricUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CoverageMetric
   */
  select?: Prisma.CoverageMetricSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CoverageMetric
   */
  omit?: Prisma.CoverageMetricOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CoverageMetricInclude<ExtArgs> | null;
  /**
   * The filter to search for the CoverageMetric to update in case it exists.
   */
  where: Prisma.CoverageMetricWhereUniqueInput;
  /**
   * In case the CoverageMetric found by the `where` argument doesn't exist, create a new CoverageMetric with this data.
   */
  create: Prisma.XOR<Prisma.CoverageMetricCreateInput, Prisma.CoverageMetricUncheckedCreateInput>;
  /**
   * In case the CoverageMetric was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CoverageMetricUpdateInput, Prisma.CoverageMetricUncheckedUpdateInput>;
};

/**
 * CoverageMetric delete
 */
export type CoverageMetricDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CoverageMetric
   */
  select?: Prisma.CoverageMetricSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CoverageMetric
   */
  omit?: Prisma.CoverageMetricOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CoverageMetricInclude<ExtArgs> | null;
  /**
   * Filter which CoverageMetric to delete.
   */
  where: Prisma.CoverageMetricWhereUniqueInput;
};

/**
 * CoverageMetric deleteMany
 */
export type CoverageMetricDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CoverageMetrics to delete
   */
  where?: Prisma.CoverageMetricWhereInput;
  /**
   * Limit how many CoverageMetrics to delete.
   */
  limit?: number;
};

/**
 * CoverageMetric without action
 */
export type CoverageMetricDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CoverageMetric
   */
  select?: Prisma.CoverageMetricSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CoverageMetric
   */
  omit?: Prisma.CoverageMetricOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CoverageMetricInclude<ExtArgs> | null;
};
