
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DataSource` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model DataSource
 * 
 */
export type DataSourceModel = runtime.Types.Result.DefaultSelection<Prisma.$DataSourcePayload>

export type AggregateDataSource = {
  _count: DataSourceCountAggregateOutputType | null
  _avg: DataSourceAvgAggregateOutputType | null
  _sum: DataSourceSumAggregateOutputType | null
  _min: DataSourceMinAggregateOutputType | null
  _max: DataSourceMaxAggregateOutputType | null
}

export type DataSourceAvgAggregateOutputType = {
  syncIntervalMinutes: number | null
}

export type DataSourceSumAggregateOutputType = {
  syncIntervalMinutes: number | null
}

export type DataSourceMinAggregateOutputType = {
  id: string | null
  organizationId: string | null
  name: string | null
  provider: $Enums.DataSourceProvider | null
  description: string | null
  isEnabled: boolean | null
  syncIntervalMinutes: number | null
  lastSyncAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DataSourceMaxAggregateOutputType = {
  id: string | null
  organizationId: string | null
  name: string | null
  provider: $Enums.DataSourceProvider | null
  description: string | null
  isEnabled: boolean | null
  syncIntervalMinutes: number | null
  lastSyncAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DataSourceCountAggregateOutputType = {
  id: number
  organizationId: number
  name: number
  provider: number
  description: number
  isEnabled: number
  syncIntervalMinutes: number
  lastSyncAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type DataSourceAvgAggregateInputType = {
  syncIntervalMinutes?: true
}

export type DataSourceSumAggregateInputType = {
  syncIntervalMinutes?: true
}

export type DataSourceMinAggregateInputType = {
  id?: true
  organizationId?: true
  name?: true
  provider?: true
  description?: true
  isEnabled?: true
  syncIntervalMinutes?: true
  lastSyncAt?: true
  createdAt?: true
  updatedAt?: true
}

export type DataSourceMaxAggregateInputType = {
  id?: true
  organizationId?: true
  name?: true
  provider?: true
  description?: true
  isEnabled?: true
  syncIntervalMinutes?: true
  lastSyncAt?: true
  createdAt?: true
  updatedAt?: true
}

export type DataSourceCountAggregateInputType = {
  id?: true
  organizationId?: true
  name?: true
  provider?: true
  description?: true
  isEnabled?: true
  syncIntervalMinutes?: true
  lastSyncAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type DataSourceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DataSource to aggregate.
   */
  where?: Prisma.DataSourceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DataSources to fetch.
   */
  orderBy?: Prisma.DataSourceOrderByWithRelationInput | Prisma.DataSourceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DataSourceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DataSources from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DataSources.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DataSources
  **/
  _count?: true | DataSourceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DataSourceAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DataSourceSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DataSourceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DataSourceMaxAggregateInputType
}

export type GetDataSourceAggregateType<T extends DataSourceAggregateArgs> = {
      [P in keyof T & keyof AggregateDataSource]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDataSource[P]>
    : Prisma.GetScalarType<T[P], AggregateDataSource[P]>
}




export type DataSourceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DataSourceWhereInput
  orderBy?: Prisma.DataSourceOrderByWithAggregationInput | Prisma.DataSourceOrderByWithAggregationInput[]
  by: Prisma.DataSourceScalarFieldEnum[] | Prisma.DataSourceScalarFieldEnum
  having?: Prisma.DataSourceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DataSourceCountAggregateInputType | true
  _avg?: DataSourceAvgAggregateInputType
  _sum?: DataSourceSumAggregateInputType
  _min?: DataSourceMinAggregateInputType
  _max?: DataSourceMaxAggregateInputType
}

export type DataSourceGroupByOutputType = {
  id: string
  organizationId: string
  name: string
  provider: $Enums.DataSourceProvider
  description: string | null
  isEnabled: boolean
  syncIntervalMinutes: number | null
  lastSyncAt: Date | null
  createdAt: Date
  updatedAt: Date
  _count: DataSourceCountAggregateOutputType | null
  _avg: DataSourceAvgAggregateOutputType | null
  _sum: DataSourceSumAggregateOutputType | null
  _min: DataSourceMinAggregateOutputType | null
  _max: DataSourceMaxAggregateOutputType | null
}

type GetDataSourceGroupByPayload<T extends DataSourceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DataSourceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DataSourceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DataSourceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DataSourceGroupByOutputType[P]>
      }
    >
  >



export type DataSourceWhereInput = {
  AND?: Prisma.DataSourceWhereInput | Prisma.DataSourceWhereInput[]
  OR?: Prisma.DataSourceWhereInput[]
  NOT?: Prisma.DataSourceWhereInput | Prisma.DataSourceWhereInput[]
  id?: Prisma.StringFilter<"DataSource"> | string
  organizationId?: Prisma.StringFilter<"DataSource"> | string
  name?: Prisma.StringFilter<"DataSource"> | string
  provider?: Prisma.EnumDataSourceProviderFilter<"DataSource"> | $Enums.DataSourceProvider
  description?: Prisma.StringNullableFilter<"DataSource"> | string | null
  isEnabled?: Prisma.BoolFilter<"DataSource"> | boolean
  syncIntervalMinutes?: Prisma.IntNullableFilter<"DataSource"> | number | null
  lastSyncAt?: Prisma.DateTimeNullableFilter<"DataSource"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"DataSource"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DataSource"> | Date | string
  organization?: Prisma.XOR<Prisma.OrganizationScalarRelationFilter, Prisma.OrganizationWhereInput>
  configs?: Prisma.DataSourceConfigListRelationFilter
  runs?: Prisma.DataSourceRunListRelationFilter
}

export type DataSourceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  syncIntervalMinutes?: Prisma.SortOrderInput | Prisma.SortOrder
  lastSyncAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  organization?: Prisma.OrganizationOrderByWithRelationInput
  configs?: Prisma.DataSourceConfigOrderByRelationAggregateInput
  runs?: Prisma.DataSourceRunOrderByRelationAggregateInput
}

export type DataSourceWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.DataSourceWhereInput | Prisma.DataSourceWhereInput[]
  OR?: Prisma.DataSourceWhereInput[]
  NOT?: Prisma.DataSourceWhereInput | Prisma.DataSourceWhereInput[]
  organizationId?: Prisma.StringFilter<"DataSource"> | string
  name?: Prisma.StringFilter<"DataSource"> | string
  provider?: Prisma.EnumDataSourceProviderFilter<"DataSource"> | $Enums.DataSourceProvider
  description?: Prisma.StringNullableFilter<"DataSource"> | string | null
  isEnabled?: Prisma.BoolFilter<"DataSource"> | boolean
  syncIntervalMinutes?: Prisma.IntNullableFilter<"DataSource"> | number | null
  lastSyncAt?: Prisma.DateTimeNullableFilter<"DataSource"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"DataSource"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DataSource"> | Date | string
  organization?: Prisma.XOR<Prisma.OrganizationScalarRelationFilter, Prisma.OrganizationWhereInput>
  configs?: Prisma.DataSourceConfigListRelationFilter
  runs?: Prisma.DataSourceRunListRelationFilter
}, "id">

export type DataSourceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  syncIntervalMinutes?: Prisma.SortOrderInput | Prisma.SortOrder
  lastSyncAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.DataSourceCountOrderByAggregateInput
  _avg?: Prisma.DataSourceAvgOrderByAggregateInput
  _max?: Prisma.DataSourceMaxOrderByAggregateInput
  _min?: Prisma.DataSourceMinOrderByAggregateInput
  _sum?: Prisma.DataSourceSumOrderByAggregateInput
}

export type DataSourceScalarWhereWithAggregatesInput = {
  AND?: Prisma.DataSourceScalarWhereWithAggregatesInput | Prisma.DataSourceScalarWhereWithAggregatesInput[]
  OR?: Prisma.DataSourceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DataSourceScalarWhereWithAggregatesInput | Prisma.DataSourceScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DataSource"> | string
  organizationId?: Prisma.StringWithAggregatesFilter<"DataSource"> | string
  name?: Prisma.StringWithAggregatesFilter<"DataSource"> | string
  provider?: Prisma.EnumDataSourceProviderWithAggregatesFilter<"DataSource"> | $Enums.DataSourceProvider
  description?: Prisma.StringNullableWithAggregatesFilter<"DataSource"> | string | null
  isEnabled?: Prisma.BoolWithAggregatesFilter<"DataSource"> | boolean
  syncIntervalMinutes?: Prisma.IntNullableWithAggregatesFilter<"DataSource"> | number | null
  lastSyncAt?: Prisma.DateTimeNullableWithAggregatesFilter<"DataSource"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"DataSource"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"DataSource"> | Date | string
}

export type DataSourceCreateInput = {
  id?: string
  name: string
  provider: $Enums.DataSourceProvider
  description?: string | null
  isEnabled?: boolean
  syncIntervalMinutes?: number | null
  lastSyncAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  organization: Prisma.OrganizationCreateNestedOneWithoutDataSourcesInput
  configs?: Prisma.DataSourceConfigCreateNestedManyWithoutDataSourceInput
  runs?: Prisma.DataSourceRunCreateNestedManyWithoutDataSourceInput
}

export type DataSourceUncheckedCreateInput = {
  id?: string
  organizationId: string
  name: string
  provider: $Enums.DataSourceProvider
  description?: string | null
  isEnabled?: boolean
  syncIntervalMinutes?: number | null
  lastSyncAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  configs?: Prisma.DataSourceConfigUncheckedCreateNestedManyWithoutDataSourceInput
  runs?: Prisma.DataSourceRunUncheckedCreateNestedManyWithoutDataSourceInput
}

export type DataSourceUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumDataSourceProviderFieldUpdateOperationsInput | $Enums.DataSourceProvider
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  syncIntervalMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lastSyncAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutDataSourcesNestedInput
  configs?: Prisma.DataSourceConfigUpdateManyWithoutDataSourceNestedInput
  runs?: Prisma.DataSourceRunUpdateManyWithoutDataSourceNestedInput
}

export type DataSourceUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumDataSourceProviderFieldUpdateOperationsInput | $Enums.DataSourceProvider
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  syncIntervalMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lastSyncAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  configs?: Prisma.DataSourceConfigUncheckedUpdateManyWithoutDataSourceNestedInput
  runs?: Prisma.DataSourceRunUncheckedUpdateManyWithoutDataSourceNestedInput
}

export type DataSourceCreateManyInput = {
  id?: string
  organizationId: string
  name: string
  provider: $Enums.DataSourceProvider
  description?: string | null
  isEnabled?: boolean
  syncIntervalMinutes?: number | null
  lastSyncAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DataSourceUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumDataSourceProviderFieldUpdateOperationsInput | $Enums.DataSourceProvider
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  syncIntervalMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lastSyncAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DataSourceUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumDataSourceProviderFieldUpdateOperationsInput | $Enums.DataSourceProvider
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  syncIntervalMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lastSyncAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DataSourceListRelationFilter = {
  every?: Prisma.DataSourceWhereInput
  some?: Prisma.DataSourceWhereInput
  none?: Prisma.DataSourceWhereInput
}

export type DataSourceOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DataSourceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  syncIntervalMinutes?: Prisma.SortOrder
  lastSyncAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DataSourceAvgOrderByAggregateInput = {
  syncIntervalMinutes?: Prisma.SortOrder
}

export type DataSourceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  syncIntervalMinutes?: Prisma.SortOrder
  lastSyncAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DataSourceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  syncIntervalMinutes?: Prisma.SortOrder
  lastSyncAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DataSourceSumOrderByAggregateInput = {
  syncIntervalMinutes?: Prisma.SortOrder
}

export type DataSourceScalarRelationFilter = {
  is?: Prisma.DataSourceWhereInput
  isNot?: Prisma.DataSourceWhereInput
}

export type DataSourceCreateNestedManyWithoutOrganizationInput = {
  create?: Prisma.XOR<Prisma.DataSourceCreateWithoutOrganizationInput, Prisma.DataSourceUncheckedCreateWithoutOrganizationInput> | Prisma.DataSourceCreateWithoutOrganizationInput[] | Prisma.DataSourceUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.DataSourceCreateOrConnectWithoutOrganizationInput | Prisma.DataSourceCreateOrConnectWithoutOrganizationInput[]
  createMany?: Prisma.DataSourceCreateManyOrganizationInputEnvelope
  connect?: Prisma.DataSourceWhereUniqueInput | Prisma.DataSourceWhereUniqueInput[]
}

export type DataSourceUncheckedCreateNestedManyWithoutOrganizationInput = {
  create?: Prisma.XOR<Prisma.DataSourceCreateWithoutOrganizationInput, Prisma.DataSourceUncheckedCreateWithoutOrganizationInput> | Prisma.DataSourceCreateWithoutOrganizationInput[] | Prisma.DataSourceUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.DataSourceCreateOrConnectWithoutOrganizationInput | Prisma.DataSourceCreateOrConnectWithoutOrganizationInput[]
  createMany?: Prisma.DataSourceCreateManyOrganizationInputEnvelope
  connect?: Prisma.DataSourceWhereUniqueInput | Prisma.DataSourceWhereUniqueInput[]
}

export type DataSourceUpdateManyWithoutOrganizationNestedInput = {
  create?: Prisma.XOR<Prisma.DataSourceCreateWithoutOrganizationInput, Prisma.DataSourceUncheckedCreateWithoutOrganizationInput> | Prisma.DataSourceCreateWithoutOrganizationInput[] | Prisma.DataSourceUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.DataSourceCreateOrConnectWithoutOrganizationInput | Prisma.DataSourceCreateOrConnectWithoutOrganizationInput[]
  upsert?: Prisma.DataSourceUpsertWithWhereUniqueWithoutOrganizationInput | Prisma.DataSourceUpsertWithWhereUniqueWithoutOrganizationInput[]
  createMany?: Prisma.DataSourceCreateManyOrganizationInputEnvelope
  set?: Prisma.DataSourceWhereUniqueInput | Prisma.DataSourceWhereUniqueInput[]
  disconnect?: Prisma.DataSourceWhereUniqueInput | Prisma.DataSourceWhereUniqueInput[]
  delete?: Prisma.DataSourceWhereUniqueInput | Prisma.DataSourceWhereUniqueInput[]
  connect?: Prisma.DataSourceWhereUniqueInput | Prisma.DataSourceWhereUniqueInput[]
  update?: Prisma.DataSourceUpdateWithWhereUniqueWithoutOrganizationInput | Prisma.DataSourceUpdateWithWhereUniqueWithoutOrganizationInput[]
  updateMany?: Prisma.DataSourceUpdateManyWithWhereWithoutOrganizationInput | Prisma.DataSourceUpdateManyWithWhereWithoutOrganizationInput[]
  deleteMany?: Prisma.DataSourceScalarWhereInput | Prisma.DataSourceScalarWhereInput[]
}

export type DataSourceUncheckedUpdateManyWithoutOrganizationNestedInput = {
  create?: Prisma.XOR<Prisma.DataSourceCreateWithoutOrganizationInput, Prisma.DataSourceUncheckedCreateWithoutOrganizationInput> | Prisma.DataSourceCreateWithoutOrganizationInput[] | Prisma.DataSourceUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.DataSourceCreateOrConnectWithoutOrganizationInput | Prisma.DataSourceCreateOrConnectWithoutOrganizationInput[]
  upsert?: Prisma.DataSourceUpsertWithWhereUniqueWithoutOrganizationInput | Prisma.DataSourceUpsertWithWhereUniqueWithoutOrganizationInput[]
  createMany?: Prisma.DataSourceCreateManyOrganizationInputEnvelope
  set?: Prisma.DataSourceWhereUniqueInput | Prisma.DataSourceWhereUniqueInput[]
  disconnect?: Prisma.DataSourceWhereUniqueInput | Prisma.DataSourceWhereUniqueInput[]
  delete?: Prisma.DataSourceWhereUniqueInput | Prisma.DataSourceWhereUniqueInput[]
  connect?: Prisma.DataSourceWhereUniqueInput | Prisma.DataSourceWhereUniqueInput[]
  update?: Prisma.DataSourceUpdateWithWhereUniqueWithoutOrganizationInput | Prisma.DataSourceUpdateWithWhereUniqueWithoutOrganizationInput[]
  updateMany?: Prisma.DataSourceUpdateManyWithWhereWithoutOrganizationInput | Prisma.DataSourceUpdateManyWithWhereWithoutOrganizationInput[]
  deleteMany?: Prisma.DataSourceScalarWhereInput | Prisma.DataSourceScalarWhereInput[]
}

export type EnumDataSourceProviderFieldUpdateOperationsInput = {
  set?: $Enums.DataSourceProvider
}

export type DataSourceCreateNestedOneWithoutConfigsInput = {
  create?: Prisma.XOR<Prisma.DataSourceCreateWithoutConfigsInput, Prisma.DataSourceUncheckedCreateWithoutConfigsInput>
  connectOrCreate?: Prisma.DataSourceCreateOrConnectWithoutConfigsInput
  connect?: Prisma.DataSourceWhereUniqueInput
}

export type DataSourceUpdateOneRequiredWithoutConfigsNestedInput = {
  create?: Prisma.XOR<Prisma.DataSourceCreateWithoutConfigsInput, Prisma.DataSourceUncheckedCreateWithoutConfigsInput>
  connectOrCreate?: Prisma.DataSourceCreateOrConnectWithoutConfigsInput
  upsert?: Prisma.DataSourceUpsertWithoutConfigsInput
  connect?: Prisma.DataSourceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DataSourceUpdateToOneWithWhereWithoutConfigsInput, Prisma.DataSourceUpdateWithoutConfigsInput>, Prisma.DataSourceUncheckedUpdateWithoutConfigsInput>
}

export type DataSourceCreateNestedOneWithoutRunsInput = {
  create?: Prisma.XOR<Prisma.DataSourceCreateWithoutRunsInput, Prisma.DataSourceUncheckedCreateWithoutRunsInput>
  connectOrCreate?: Prisma.DataSourceCreateOrConnectWithoutRunsInput
  connect?: Prisma.DataSourceWhereUniqueInput
}

export type DataSourceUpdateOneRequiredWithoutRunsNestedInput = {
  create?: Prisma.XOR<Prisma.DataSourceCreateWithoutRunsInput, Prisma.DataSourceUncheckedCreateWithoutRunsInput>
  connectOrCreate?: Prisma.DataSourceCreateOrConnectWithoutRunsInput
  upsert?: Prisma.DataSourceUpsertWithoutRunsInput
  connect?: Prisma.DataSourceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DataSourceUpdateToOneWithWhereWithoutRunsInput, Prisma.DataSourceUpdateWithoutRunsInput>, Prisma.DataSourceUncheckedUpdateWithoutRunsInput>
}

export type DataSourceCreateWithoutOrganizationInput = {
  id?: string
  name: string
  provider: $Enums.DataSourceProvider
  description?: string | null
  isEnabled?: boolean
  syncIntervalMinutes?: number | null
  lastSyncAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  configs?: Prisma.DataSourceConfigCreateNestedManyWithoutDataSourceInput
  runs?: Prisma.DataSourceRunCreateNestedManyWithoutDataSourceInput
}

export type DataSourceUncheckedCreateWithoutOrganizationInput = {
  id?: string
  name: string
  provider: $Enums.DataSourceProvider
  description?: string | null
  isEnabled?: boolean
  syncIntervalMinutes?: number | null
  lastSyncAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  configs?: Prisma.DataSourceConfigUncheckedCreateNestedManyWithoutDataSourceInput
  runs?: Prisma.DataSourceRunUncheckedCreateNestedManyWithoutDataSourceInput
}

export type DataSourceCreateOrConnectWithoutOrganizationInput = {
  where: Prisma.DataSourceWhereUniqueInput
  create: Prisma.XOR<Prisma.DataSourceCreateWithoutOrganizationInput, Prisma.DataSourceUncheckedCreateWithoutOrganizationInput>
}

export type DataSourceCreateManyOrganizationInputEnvelope = {
  data: Prisma.DataSourceCreateManyOrganizationInput | Prisma.DataSourceCreateManyOrganizationInput[]
  skipDuplicates?: boolean
}

export type DataSourceUpsertWithWhereUniqueWithoutOrganizationInput = {
  where: Prisma.DataSourceWhereUniqueInput
  update: Prisma.XOR<Prisma.DataSourceUpdateWithoutOrganizationInput, Prisma.DataSourceUncheckedUpdateWithoutOrganizationInput>
  create: Prisma.XOR<Prisma.DataSourceCreateWithoutOrganizationInput, Prisma.DataSourceUncheckedCreateWithoutOrganizationInput>
}

export type DataSourceUpdateWithWhereUniqueWithoutOrganizationInput = {
  where: Prisma.DataSourceWhereUniqueInput
  data: Prisma.XOR<Prisma.DataSourceUpdateWithoutOrganizationInput, Prisma.DataSourceUncheckedUpdateWithoutOrganizationInput>
}

export type DataSourceUpdateManyWithWhereWithoutOrganizationInput = {
  where: Prisma.DataSourceScalarWhereInput
  data: Prisma.XOR<Prisma.DataSourceUpdateManyMutationInput, Prisma.DataSourceUncheckedUpdateManyWithoutOrganizationInput>
}

export type DataSourceScalarWhereInput = {
  AND?: Prisma.DataSourceScalarWhereInput | Prisma.DataSourceScalarWhereInput[]
  OR?: Prisma.DataSourceScalarWhereInput[]
  NOT?: Prisma.DataSourceScalarWhereInput | Prisma.DataSourceScalarWhereInput[]
  id?: Prisma.StringFilter<"DataSource"> | string
  organizationId?: Prisma.StringFilter<"DataSource"> | string
  name?: Prisma.StringFilter<"DataSource"> | string
  provider?: Prisma.EnumDataSourceProviderFilter<"DataSource"> | $Enums.DataSourceProvider
  description?: Prisma.StringNullableFilter<"DataSource"> | string | null
  isEnabled?: Prisma.BoolFilter<"DataSource"> | boolean
  syncIntervalMinutes?: Prisma.IntNullableFilter<"DataSource"> | number | null
  lastSyncAt?: Prisma.DateTimeNullableFilter<"DataSource"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"DataSource"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DataSource"> | Date | string
}

export type DataSourceCreateWithoutConfigsInput = {
  id?: string
  name: string
  provider: $Enums.DataSourceProvider
  description?: string | null
  isEnabled?: boolean
  syncIntervalMinutes?: number | null
  lastSyncAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  organization: Prisma.OrganizationCreateNestedOneWithoutDataSourcesInput
  runs?: Prisma.DataSourceRunCreateNestedManyWithoutDataSourceInput
}

export type DataSourceUncheckedCreateWithoutConfigsInput = {
  id?: string
  organizationId: string
  name: string
  provider: $Enums.DataSourceProvider
  description?: string | null
  isEnabled?: boolean
  syncIntervalMinutes?: number | null
  lastSyncAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  runs?: Prisma.DataSourceRunUncheckedCreateNestedManyWithoutDataSourceInput
}

export type DataSourceCreateOrConnectWithoutConfigsInput = {
  where: Prisma.DataSourceWhereUniqueInput
  create: Prisma.XOR<Prisma.DataSourceCreateWithoutConfigsInput, Prisma.DataSourceUncheckedCreateWithoutConfigsInput>
}

export type DataSourceUpsertWithoutConfigsInput = {
  update: Prisma.XOR<Prisma.DataSourceUpdateWithoutConfigsInput, Prisma.DataSourceUncheckedUpdateWithoutConfigsInput>
  create: Prisma.XOR<Prisma.DataSourceCreateWithoutConfigsInput, Prisma.DataSourceUncheckedCreateWithoutConfigsInput>
  where?: Prisma.DataSourceWhereInput
}

export type DataSourceUpdateToOneWithWhereWithoutConfigsInput = {
  where?: Prisma.DataSourceWhereInput
  data: Prisma.XOR<Prisma.DataSourceUpdateWithoutConfigsInput, Prisma.DataSourceUncheckedUpdateWithoutConfigsInput>
}

export type DataSourceUpdateWithoutConfigsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumDataSourceProviderFieldUpdateOperationsInput | $Enums.DataSourceProvider
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  syncIntervalMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lastSyncAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutDataSourcesNestedInput
  runs?: Prisma.DataSourceRunUpdateManyWithoutDataSourceNestedInput
}

export type DataSourceUncheckedUpdateWithoutConfigsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumDataSourceProviderFieldUpdateOperationsInput | $Enums.DataSourceProvider
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  syncIntervalMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lastSyncAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  runs?: Prisma.DataSourceRunUncheckedUpdateManyWithoutDataSourceNestedInput
}

export type DataSourceCreateWithoutRunsInput = {
  id?: string
  name: string
  provider: $Enums.DataSourceProvider
  description?: string | null
  isEnabled?: boolean
  syncIntervalMinutes?: number | null
  lastSyncAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  organization: Prisma.OrganizationCreateNestedOneWithoutDataSourcesInput
  configs?: Prisma.DataSourceConfigCreateNestedManyWithoutDataSourceInput
}

export type DataSourceUncheckedCreateWithoutRunsInput = {
  id?: string
  organizationId: string
  name: string
  provider: $Enums.DataSourceProvider
  description?: string | null
  isEnabled?: boolean
  syncIntervalMinutes?: number | null
  lastSyncAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  configs?: Prisma.DataSourceConfigUncheckedCreateNestedManyWithoutDataSourceInput
}

export type DataSourceCreateOrConnectWithoutRunsInput = {
  where: Prisma.DataSourceWhereUniqueInput
  create: Prisma.XOR<Prisma.DataSourceCreateWithoutRunsInput, Prisma.DataSourceUncheckedCreateWithoutRunsInput>
}

export type DataSourceUpsertWithoutRunsInput = {
  update: Prisma.XOR<Prisma.DataSourceUpdateWithoutRunsInput, Prisma.DataSourceUncheckedUpdateWithoutRunsInput>
  create: Prisma.XOR<Prisma.DataSourceCreateWithoutRunsInput, Prisma.DataSourceUncheckedCreateWithoutRunsInput>
  where?: Prisma.DataSourceWhereInput
}

export type DataSourceUpdateToOneWithWhereWithoutRunsInput = {
  where?: Prisma.DataSourceWhereInput
  data: Prisma.XOR<Prisma.DataSourceUpdateWithoutRunsInput, Prisma.DataSourceUncheckedUpdateWithoutRunsInput>
}

export type DataSourceUpdateWithoutRunsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumDataSourceProviderFieldUpdateOperationsInput | $Enums.DataSourceProvider
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  syncIntervalMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lastSyncAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutDataSourcesNestedInput
  configs?: Prisma.DataSourceConfigUpdateManyWithoutDataSourceNestedInput
}

export type DataSourceUncheckedUpdateWithoutRunsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumDataSourceProviderFieldUpdateOperationsInput | $Enums.DataSourceProvider
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  syncIntervalMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lastSyncAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  configs?: Prisma.DataSourceConfigUncheckedUpdateManyWithoutDataSourceNestedInput
}

export type DataSourceCreateManyOrganizationInput = {
  id?: string
  name: string
  provider: $Enums.DataSourceProvider
  description?: string | null
  isEnabled?: boolean
  syncIntervalMinutes?: number | null
  lastSyncAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DataSourceUpdateWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumDataSourceProviderFieldUpdateOperationsInput | $Enums.DataSourceProvider
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  syncIntervalMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lastSyncAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  configs?: Prisma.DataSourceConfigUpdateManyWithoutDataSourceNestedInput
  runs?: Prisma.DataSourceRunUpdateManyWithoutDataSourceNestedInput
}

export type DataSourceUncheckedUpdateWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumDataSourceProviderFieldUpdateOperationsInput | $Enums.DataSourceProvider
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  syncIntervalMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lastSyncAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  configs?: Prisma.DataSourceConfigUncheckedUpdateManyWithoutDataSourceNestedInput
  runs?: Prisma.DataSourceRunUncheckedUpdateManyWithoutDataSourceNestedInput
}

export type DataSourceUncheckedUpdateManyWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.EnumDataSourceProviderFieldUpdateOperationsInput | $Enums.DataSourceProvider
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  syncIntervalMinutes?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lastSyncAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type DataSourceCountOutputType
 */

export type DataSourceCountOutputType = {
  configs: number
  runs: number
}

export type DataSourceCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  configs?: boolean | DataSourceCountOutputTypeCountConfigsArgs
  runs?: boolean | DataSourceCountOutputTypeCountRunsArgs
}

/**
 * DataSourceCountOutputType without action
 */
export type DataSourceCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DataSourceCountOutputType
   */
  select?: Prisma.DataSourceCountOutputTypeSelect<ExtArgs> | null
}

/**
 * DataSourceCountOutputType without action
 */
export type DataSourceCountOutputTypeCountConfigsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DataSourceConfigWhereInput
}

/**
 * DataSourceCountOutputType without action
 */
export type DataSourceCountOutputTypeCountRunsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DataSourceRunWhereInput
}


export type DataSourceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  organizationId?: boolean
  name?: boolean
  provider?: boolean
  description?: boolean
  isEnabled?: boolean
  syncIntervalMinutes?: boolean
  lastSyncAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  configs?: boolean | Prisma.DataSource$configsArgs<ExtArgs>
  runs?: boolean | Prisma.DataSource$runsArgs<ExtArgs>
  _count?: boolean | Prisma.DataSourceCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dataSource"]>

export type DataSourceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  organizationId?: boolean
  name?: boolean
  provider?: boolean
  description?: boolean
  isEnabled?: boolean
  syncIntervalMinutes?: boolean
  lastSyncAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dataSource"]>

export type DataSourceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  organizationId?: boolean
  name?: boolean
  provider?: boolean
  description?: boolean
  isEnabled?: boolean
  syncIntervalMinutes?: boolean
  lastSyncAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dataSource"]>

export type DataSourceSelectScalar = {
  id?: boolean
  organizationId?: boolean
  name?: boolean
  provider?: boolean
  description?: boolean
  isEnabled?: boolean
  syncIntervalMinutes?: boolean
  lastSyncAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type DataSourceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "organizationId" | "name" | "provider" | "description" | "isEnabled" | "syncIntervalMinutes" | "lastSyncAt" | "createdAt" | "updatedAt", ExtArgs["result"]["dataSource"]>
export type DataSourceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  configs?: boolean | Prisma.DataSource$configsArgs<ExtArgs>
  runs?: boolean | Prisma.DataSource$runsArgs<ExtArgs>
  _count?: boolean | Prisma.DataSourceCountOutputTypeDefaultArgs<ExtArgs>
}
export type DataSourceIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
}
export type DataSourceIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
}

export type $DataSourcePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DataSource"
  objects: {
    organization: Prisma.$OrganizationPayload<ExtArgs>
    configs: Prisma.$DataSourceConfigPayload<ExtArgs>[]
    runs: Prisma.$DataSourceRunPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    organizationId: string
    name: string
    provider: $Enums.DataSourceProvider
    description: string | null
    isEnabled: boolean
    syncIntervalMinutes: number | null
    lastSyncAt: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["dataSource"]>
  composites: {}
}

export type DataSourceGetPayload<S extends boolean | null | undefined | DataSourceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DataSourcePayload, S>

export type DataSourceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DataSourceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DataSourceCountAggregateInputType | true
  }

export interface DataSourceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DataSource'], meta: { name: 'DataSource' } }
  /**
   * Find zero or one DataSource that matches the filter.
   * @param {DataSourceFindUniqueArgs} args - Arguments to find a DataSource
   * @example
   * // Get one DataSource
   * const dataSource = await prisma.dataSource.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DataSourceFindUniqueArgs>(args: Prisma.SelectSubset<T, DataSourceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DataSourceClient<runtime.Types.Result.GetResult<Prisma.$DataSourcePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DataSource that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DataSourceFindUniqueOrThrowArgs} args - Arguments to find a DataSource
   * @example
   * // Get one DataSource
   * const dataSource = await prisma.dataSource.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DataSourceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DataSourceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DataSourceClient<runtime.Types.Result.GetResult<Prisma.$DataSourcePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DataSource that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DataSourceFindFirstArgs} args - Arguments to find a DataSource
   * @example
   * // Get one DataSource
   * const dataSource = await prisma.dataSource.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DataSourceFindFirstArgs>(args?: Prisma.SelectSubset<T, DataSourceFindFirstArgs<ExtArgs>>): Prisma.Prisma__DataSourceClient<runtime.Types.Result.GetResult<Prisma.$DataSourcePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DataSource that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DataSourceFindFirstOrThrowArgs} args - Arguments to find a DataSource
   * @example
   * // Get one DataSource
   * const dataSource = await prisma.dataSource.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DataSourceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DataSourceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DataSourceClient<runtime.Types.Result.GetResult<Prisma.$DataSourcePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DataSources that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DataSourceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DataSources
   * const dataSources = await prisma.dataSource.findMany()
   * 
   * // Get first 10 DataSources
   * const dataSources = await prisma.dataSource.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dataSourceWithIdOnly = await prisma.dataSource.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DataSourceFindManyArgs>(args?: Prisma.SelectSubset<T, DataSourceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DataSourcePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DataSource.
   * @param {DataSourceCreateArgs} args - Arguments to create a DataSource.
   * @example
   * // Create one DataSource
   * const DataSource = await prisma.dataSource.create({
   *   data: {
   *     // ... data to create a DataSource
   *   }
   * })
   * 
   */
  create<T extends DataSourceCreateArgs>(args: Prisma.SelectSubset<T, DataSourceCreateArgs<ExtArgs>>): Prisma.Prisma__DataSourceClient<runtime.Types.Result.GetResult<Prisma.$DataSourcePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DataSources.
   * @param {DataSourceCreateManyArgs} args - Arguments to create many DataSources.
   * @example
   * // Create many DataSources
   * const dataSource = await prisma.dataSource.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DataSourceCreateManyArgs>(args?: Prisma.SelectSubset<T, DataSourceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DataSources and returns the data saved in the database.
   * @param {DataSourceCreateManyAndReturnArgs} args - Arguments to create many DataSources.
   * @example
   * // Create many DataSources
   * const dataSource = await prisma.dataSource.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DataSources and only return the `id`
   * const dataSourceWithIdOnly = await prisma.dataSource.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DataSourceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DataSourceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DataSourcePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DataSource.
   * @param {DataSourceDeleteArgs} args - Arguments to delete one DataSource.
   * @example
   * // Delete one DataSource
   * const DataSource = await prisma.dataSource.delete({
   *   where: {
   *     // ... filter to delete one DataSource
   *   }
   * })
   * 
   */
  delete<T extends DataSourceDeleteArgs>(args: Prisma.SelectSubset<T, DataSourceDeleteArgs<ExtArgs>>): Prisma.Prisma__DataSourceClient<runtime.Types.Result.GetResult<Prisma.$DataSourcePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DataSource.
   * @param {DataSourceUpdateArgs} args - Arguments to update one DataSource.
   * @example
   * // Update one DataSource
   * const dataSource = await prisma.dataSource.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DataSourceUpdateArgs>(args: Prisma.SelectSubset<T, DataSourceUpdateArgs<ExtArgs>>): Prisma.Prisma__DataSourceClient<runtime.Types.Result.GetResult<Prisma.$DataSourcePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DataSources.
   * @param {DataSourceDeleteManyArgs} args - Arguments to filter DataSources to delete.
   * @example
   * // Delete a few DataSources
   * const { count } = await prisma.dataSource.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DataSourceDeleteManyArgs>(args?: Prisma.SelectSubset<T, DataSourceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DataSources.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DataSourceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DataSources
   * const dataSource = await prisma.dataSource.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DataSourceUpdateManyArgs>(args: Prisma.SelectSubset<T, DataSourceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DataSources and returns the data updated in the database.
   * @param {DataSourceUpdateManyAndReturnArgs} args - Arguments to update many DataSources.
   * @example
   * // Update many DataSources
   * const dataSource = await prisma.dataSource.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DataSources and only return the `id`
   * const dataSourceWithIdOnly = await prisma.dataSource.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DataSourceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DataSourceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DataSourcePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DataSource.
   * @param {DataSourceUpsertArgs} args - Arguments to update or create a DataSource.
   * @example
   * // Update or create a DataSource
   * const dataSource = await prisma.dataSource.upsert({
   *   create: {
   *     // ... data to create a DataSource
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DataSource we want to update
   *   }
   * })
   */
  upsert<T extends DataSourceUpsertArgs>(args: Prisma.SelectSubset<T, DataSourceUpsertArgs<ExtArgs>>): Prisma.Prisma__DataSourceClient<runtime.Types.Result.GetResult<Prisma.$DataSourcePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DataSources.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DataSourceCountArgs} args - Arguments to filter DataSources to count.
   * @example
   * // Count the number of DataSources
   * const count = await prisma.dataSource.count({
   *   where: {
   *     // ... the filter for the DataSources we want to count
   *   }
   * })
  **/
  count<T extends DataSourceCountArgs>(
    args?: Prisma.Subset<T, DataSourceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DataSourceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DataSource.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DataSourceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DataSourceAggregateArgs>(args: Prisma.Subset<T, DataSourceAggregateArgs>): Prisma.PrismaPromise<GetDataSourceAggregateType<T>>

  /**
   * Group by DataSource.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DataSourceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DataSourceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DataSourceGroupByArgs['orderBy'] }
      : { orderBy?: DataSourceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DataSourceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDataSourceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DataSource model
 */
readonly fields: DataSourceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DataSource.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DataSourceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  organization<T extends Prisma.OrganizationDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrganizationDefaultArgs<ExtArgs>>): Prisma.Prisma__OrganizationClient<runtime.Types.Result.GetResult<Prisma.$OrganizationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  configs<T extends Prisma.DataSource$configsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DataSource$configsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DataSourceConfigPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  runs<T extends Prisma.DataSource$runsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DataSource$runsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DataSourceRunPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DataSource model
 */
export interface DataSourceFieldRefs {
  readonly id: Prisma.FieldRef<"DataSource", 'String'>
  readonly organizationId: Prisma.FieldRef<"DataSource", 'String'>
  readonly name: Prisma.FieldRef<"DataSource", 'String'>
  readonly provider: Prisma.FieldRef<"DataSource", 'DataSourceProvider'>
  readonly description: Prisma.FieldRef<"DataSource", 'String'>
  readonly isEnabled: Prisma.FieldRef<"DataSource", 'Boolean'>
  readonly syncIntervalMinutes: Prisma.FieldRef<"DataSource", 'Int'>
  readonly lastSyncAt: Prisma.FieldRef<"DataSource", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"DataSource", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"DataSource", 'DateTime'>
}
    

// Custom InputTypes
/**
 * DataSource findUnique
 */
export type DataSourceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DataSource
   */
  select?: Prisma.DataSourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DataSource
   */
  omit?: Prisma.DataSourceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DataSourceInclude<ExtArgs> | null
  /**
   * Filter, which DataSource to fetch.
   */
  where: Prisma.DataSourceWhereUniqueInput
}

/**
 * DataSource findUniqueOrThrow
 */
export type DataSourceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DataSource
   */
  select?: Prisma.DataSourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DataSource
   */
  omit?: Prisma.DataSourceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DataSourceInclude<ExtArgs> | null
  /**
   * Filter, which DataSource to fetch.
   */
  where: Prisma.DataSourceWhereUniqueInput
}

/**
 * DataSource findFirst
 */
export type DataSourceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DataSource
   */
  select?: Prisma.DataSourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DataSource
   */
  omit?: Prisma.DataSourceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DataSourceInclude<ExtArgs> | null
  /**
   * Filter, which DataSource to fetch.
   */
  where?: Prisma.DataSourceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DataSources to fetch.
   */
  orderBy?: Prisma.DataSourceOrderByWithRelationInput | Prisma.DataSourceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DataSources.
   */
  cursor?: Prisma.DataSourceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DataSources from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DataSources.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DataSources.
   */
  distinct?: Prisma.DataSourceScalarFieldEnum | Prisma.DataSourceScalarFieldEnum[]
}

/**
 * DataSource findFirstOrThrow
 */
export type DataSourceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DataSource
   */
  select?: Prisma.DataSourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DataSource
   */
  omit?: Prisma.DataSourceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DataSourceInclude<ExtArgs> | null
  /**
   * Filter, which DataSource to fetch.
   */
  where?: Prisma.DataSourceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DataSources to fetch.
   */
  orderBy?: Prisma.DataSourceOrderByWithRelationInput | Prisma.DataSourceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DataSources.
   */
  cursor?: Prisma.DataSourceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DataSources from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DataSources.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DataSources.
   */
  distinct?: Prisma.DataSourceScalarFieldEnum | Prisma.DataSourceScalarFieldEnum[]
}

/**
 * DataSource findMany
 */
export type DataSourceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DataSource
   */
  select?: Prisma.DataSourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DataSource
   */
  omit?: Prisma.DataSourceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DataSourceInclude<ExtArgs> | null
  /**
   * Filter, which DataSources to fetch.
   */
  where?: Prisma.DataSourceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DataSources to fetch.
   */
  orderBy?: Prisma.DataSourceOrderByWithRelationInput | Prisma.DataSourceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DataSources.
   */
  cursor?: Prisma.DataSourceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DataSources from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DataSources.
   */
  skip?: number
  distinct?: Prisma.DataSourceScalarFieldEnum | Prisma.DataSourceScalarFieldEnum[]
}

/**
 * DataSource create
 */
export type DataSourceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DataSource
   */
  select?: Prisma.DataSourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DataSource
   */
  omit?: Prisma.DataSourceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DataSourceInclude<ExtArgs> | null
  /**
   * The data needed to create a DataSource.
   */
  data: Prisma.XOR<Prisma.DataSourceCreateInput, Prisma.DataSourceUncheckedCreateInput>
}

/**
 * DataSource createMany
 */
export type DataSourceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DataSources.
   */
  data: Prisma.DataSourceCreateManyInput | Prisma.DataSourceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DataSource createManyAndReturn
 */
export type DataSourceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DataSource
   */
  select?: Prisma.DataSourceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DataSource
   */
  omit?: Prisma.DataSourceOmit<ExtArgs> | null
  /**
   * The data used to create many DataSources.
   */
  data: Prisma.DataSourceCreateManyInput | Prisma.DataSourceCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DataSourceIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DataSource update
 */
export type DataSourceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DataSource
   */
  select?: Prisma.DataSourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DataSource
   */
  omit?: Prisma.DataSourceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DataSourceInclude<ExtArgs> | null
  /**
   * The data needed to update a DataSource.
   */
  data: Prisma.XOR<Prisma.DataSourceUpdateInput, Prisma.DataSourceUncheckedUpdateInput>
  /**
   * Choose, which DataSource to update.
   */
  where: Prisma.DataSourceWhereUniqueInput
}

/**
 * DataSource updateMany
 */
export type DataSourceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DataSources.
   */
  data: Prisma.XOR<Prisma.DataSourceUpdateManyMutationInput, Prisma.DataSourceUncheckedUpdateManyInput>
  /**
   * Filter which DataSources to update
   */
  where?: Prisma.DataSourceWhereInput
  /**
   * Limit how many DataSources to update.
   */
  limit?: number
}

/**
 * DataSource updateManyAndReturn
 */
export type DataSourceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DataSource
   */
  select?: Prisma.DataSourceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DataSource
   */
  omit?: Prisma.DataSourceOmit<ExtArgs> | null
  /**
   * The data used to update DataSources.
   */
  data: Prisma.XOR<Prisma.DataSourceUpdateManyMutationInput, Prisma.DataSourceUncheckedUpdateManyInput>
  /**
   * Filter which DataSources to update
   */
  where?: Prisma.DataSourceWhereInput
  /**
   * Limit how many DataSources to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DataSourceIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DataSource upsert
 */
export type DataSourceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DataSource
   */
  select?: Prisma.DataSourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DataSource
   */
  omit?: Prisma.DataSourceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DataSourceInclude<ExtArgs> | null
  /**
   * The filter to search for the DataSource to update in case it exists.
   */
  where: Prisma.DataSourceWhereUniqueInput
  /**
   * In case the DataSource found by the `where` argument doesn't exist, create a new DataSource with this data.
   */
  create: Prisma.XOR<Prisma.DataSourceCreateInput, Prisma.DataSourceUncheckedCreateInput>
  /**
   * In case the DataSource was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DataSourceUpdateInput, Prisma.DataSourceUncheckedUpdateInput>
}

/**
 * DataSource delete
 */
export type DataSourceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DataSource
   */
  select?: Prisma.DataSourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DataSource
   */
  omit?: Prisma.DataSourceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DataSourceInclude<ExtArgs> | null
  /**
   * Filter which DataSource to delete.
   */
  where: Prisma.DataSourceWhereUniqueInput
}

/**
 * DataSource deleteMany
 */
export type DataSourceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DataSources to delete
   */
  where?: Prisma.DataSourceWhereInput
  /**
   * Limit how many DataSources to delete.
   */
  limit?: number
}

/**
 * DataSource.configs
 */
export type DataSource$configsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DataSourceConfig
   */
  select?: Prisma.DataSourceConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DataSourceConfig
   */
  omit?: Prisma.DataSourceConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DataSourceConfigInclude<ExtArgs> | null
  where?: Prisma.DataSourceConfigWhereInput
  orderBy?: Prisma.DataSourceConfigOrderByWithRelationInput | Prisma.DataSourceConfigOrderByWithRelationInput[]
  cursor?: Prisma.DataSourceConfigWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DataSourceConfigScalarFieldEnum | Prisma.DataSourceConfigScalarFieldEnum[]
}

/**
 * DataSource.runs
 */
export type DataSource$runsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DataSourceRun
   */
  select?: Prisma.DataSourceRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DataSourceRun
   */
  omit?: Prisma.DataSourceRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DataSourceRunInclude<ExtArgs> | null
  where?: Prisma.DataSourceRunWhereInput
  orderBy?: Prisma.DataSourceRunOrderByWithRelationInput | Prisma.DataSourceRunOrderByWithRelationInput[]
  cursor?: Prisma.DataSourceRunWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DataSourceRunScalarFieldEnum | Prisma.DataSourceRunScalarFieldEnum[]
}

/**
 * DataSource without action
 */
export type DataSourceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DataSource
   */
  select?: Prisma.DataSourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DataSource
   */
  omit?: Prisma.DataSourceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DataSourceInclude<ExtArgs> | null
}
