/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `ImportLog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums";
import type * as Prisma from "../internal/prismaNamespace";

/**
 * Model ImportLog
 *
 */
export type ImportLogModel = runtime.Types.Result.DefaultSelection<Prisma.$ImportLogPayload>;

export type AggregateImportLog = {
  _count: ImportLogCountAggregateOutputType | null;
  _min: ImportLogMinAggregateOutputType | null;
  _max: ImportLogMaxAggregateOutputType | null;
};

export type ImportLogMinAggregateOutputType = {
  id: string | null;
  dataSourceRunId: string | null;
  level: $Enums.ImportLogLevel | null;
  message: string | null;
  details: string | null;
  recordId: string | null;
  createdAt: Date | null;
};

export type ImportLogMaxAggregateOutputType = {
  id: string | null;
  dataSourceRunId: string | null;
  level: $Enums.ImportLogLevel | null;
  message: string | null;
  details: string | null;
  recordId: string | null;
  createdAt: Date | null;
};

export type ImportLogCountAggregateOutputType = {
  id: number;
  dataSourceRunId: number;
  level: number;
  message: number;
  details: number;
  recordId: number;
  createdAt: number;
  _all: number;
};

export type ImportLogMinAggregateInputType = {
  id?: true;
  dataSourceRunId?: true;
  level?: true;
  message?: true;
  details?: true;
  recordId?: true;
  createdAt?: true;
};

export type ImportLogMaxAggregateInputType = {
  id?: true;
  dataSourceRunId?: true;
  level?: true;
  message?: true;
  details?: true;
  recordId?: true;
  createdAt?: true;
};

export type ImportLogCountAggregateInputType = {
  id?: true;
  dataSourceRunId?: true;
  level?: true;
  message?: true;
  details?: true;
  recordId?: true;
  createdAt?: true;
  _all?: true;
};

export type ImportLogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ImportLog to aggregate.
   */
  where?: Prisma.ImportLogWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ImportLogs to fetch.
   */
  orderBy?: Prisma.ImportLogOrderByWithRelationInput | Prisma.ImportLogOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.ImportLogWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ImportLogs from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ImportLogs.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned ImportLogs
   **/
  _count?: true | ImportLogCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: ImportLogMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: ImportLogMaxAggregateInputType;
};

export type GetImportLogAggregateType<T extends ImportLogAggregateArgs> = {
  [P in keyof T & keyof AggregateImportLog]: P extends "_count" | "count"
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateImportLog[P]>
    : Prisma.GetScalarType<T[P], AggregateImportLog[P]>;
};

export type ImportLogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ImportLogWhereInput;
  orderBy?: Prisma.ImportLogOrderByWithAggregationInput | Prisma.ImportLogOrderByWithAggregationInput[];
  by: Prisma.ImportLogScalarFieldEnum[] | Prisma.ImportLogScalarFieldEnum;
  having?: Prisma.ImportLogScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: ImportLogCountAggregateInputType | true;
  _min?: ImportLogMinAggregateInputType;
  _max?: ImportLogMaxAggregateInputType;
};

export type ImportLogGroupByOutputType = {
  id: string;
  dataSourceRunId: string;
  level: $Enums.ImportLogLevel;
  message: string;
  details: string | null;
  recordId: string | null;
  createdAt: Date;
  _count: ImportLogCountAggregateOutputType | null;
  _min: ImportLogMinAggregateOutputType | null;
  _max: ImportLogMaxAggregateOutputType | null;
};

type GetImportLogGroupByPayload<T extends ImportLogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ImportLogGroupByOutputType, T["by"]> & {
      [P in keyof T & keyof ImportLogGroupByOutputType]: P extends "_count"
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<T[P], ImportLogGroupByOutputType[P]>
        : Prisma.GetScalarType<T[P], ImportLogGroupByOutputType[P]>;
    }
  >
>;

export type ImportLogWhereInput = {
  AND?: Prisma.ImportLogWhereInput | Prisma.ImportLogWhereInput[];
  OR?: Prisma.ImportLogWhereInput[];
  NOT?: Prisma.ImportLogWhereInput | Prisma.ImportLogWhereInput[];
  id?: Prisma.StringFilter<"ImportLog"> | string;
  dataSourceRunId?: Prisma.StringFilter<"ImportLog"> | string;
  level?: Prisma.EnumImportLogLevelFilter<"ImportLog"> | $Enums.ImportLogLevel;
  message?: Prisma.StringFilter<"ImportLog"> | string;
  details?: Prisma.StringNullableFilter<"ImportLog"> | string | null;
  recordId?: Prisma.StringNullableFilter<"ImportLog"> | string | null;
  createdAt?: Prisma.DateTimeFilter<"ImportLog"> | Date | string;
  dataSourceRun?: Prisma.XOR<Prisma.DataSourceRunScalarRelationFilter, Prisma.DataSourceRunWhereInput>;
};

export type ImportLogOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  dataSourceRunId?: Prisma.SortOrder;
  level?: Prisma.SortOrder;
  message?: Prisma.SortOrder;
  details?: Prisma.SortOrderInput | Prisma.SortOrder;
  recordId?: Prisma.SortOrderInput | Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  dataSourceRun?: Prisma.DataSourceRunOrderByWithRelationInput;
};

export type ImportLogWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string;
    AND?: Prisma.ImportLogWhereInput | Prisma.ImportLogWhereInput[];
    OR?: Prisma.ImportLogWhereInput[];
    NOT?: Prisma.ImportLogWhereInput | Prisma.ImportLogWhereInput[];
    dataSourceRunId?: Prisma.StringFilter<"ImportLog"> | string;
    level?: Prisma.EnumImportLogLevelFilter<"ImportLog"> | $Enums.ImportLogLevel;
    message?: Prisma.StringFilter<"ImportLog"> | string;
    details?: Prisma.StringNullableFilter<"ImportLog"> | string | null;
    recordId?: Prisma.StringNullableFilter<"ImportLog"> | string | null;
    createdAt?: Prisma.DateTimeFilter<"ImportLog"> | Date | string;
    dataSourceRun?: Prisma.XOR<Prisma.DataSourceRunScalarRelationFilter, Prisma.DataSourceRunWhereInput>;
  },
  "id"
>;

export type ImportLogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  dataSourceRunId?: Prisma.SortOrder;
  level?: Prisma.SortOrder;
  message?: Prisma.SortOrder;
  details?: Prisma.SortOrderInput | Prisma.SortOrder;
  recordId?: Prisma.SortOrderInput | Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  _count?: Prisma.ImportLogCountOrderByAggregateInput;
  _max?: Prisma.ImportLogMaxOrderByAggregateInput;
  _min?: Prisma.ImportLogMinOrderByAggregateInput;
};

export type ImportLogScalarWhereWithAggregatesInput = {
  AND?: Prisma.ImportLogScalarWhereWithAggregatesInput | Prisma.ImportLogScalarWhereWithAggregatesInput[];
  OR?: Prisma.ImportLogScalarWhereWithAggregatesInput[];
  NOT?: Prisma.ImportLogScalarWhereWithAggregatesInput | Prisma.ImportLogScalarWhereWithAggregatesInput[];
  id?: Prisma.StringWithAggregatesFilter<"ImportLog"> | string;
  dataSourceRunId?: Prisma.StringWithAggregatesFilter<"ImportLog"> | string;
  level?: Prisma.EnumImportLogLevelWithAggregatesFilter<"ImportLog"> | $Enums.ImportLogLevel;
  message?: Prisma.StringWithAggregatesFilter<"ImportLog"> | string;
  details?: Prisma.StringNullableWithAggregatesFilter<"ImportLog"> | string | null;
  recordId?: Prisma.StringNullableWithAggregatesFilter<"ImportLog"> | string | null;
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ImportLog"> | Date | string;
};

export type ImportLogCreateInput = {
  id?: string;
  level: $Enums.ImportLogLevel;
  message: string;
  details?: string | null;
  recordId?: string | null;
  createdAt?: Date | string;
  dataSourceRun: Prisma.DataSourceRunCreateNestedOneWithoutLogsInput;
};

export type ImportLogUncheckedCreateInput = {
  id?: string;
  dataSourceRunId: string;
  level: $Enums.ImportLogLevel;
  message: string;
  details?: string | null;
  recordId?: string | null;
  createdAt?: Date | string;
};

export type ImportLogUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  level?: Prisma.EnumImportLogLevelFieldUpdateOperationsInput | $Enums.ImportLogLevel;
  message?: Prisma.StringFieldUpdateOperationsInput | string;
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  recordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  dataSourceRun?: Prisma.DataSourceRunUpdateOneRequiredWithoutLogsNestedInput;
};

export type ImportLogUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  dataSourceRunId?: Prisma.StringFieldUpdateOperationsInput | string;
  level?: Prisma.EnumImportLogLevelFieldUpdateOperationsInput | $Enums.ImportLogLevel;
  message?: Prisma.StringFieldUpdateOperationsInput | string;
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  recordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type ImportLogCreateManyInput = {
  id?: string;
  dataSourceRunId: string;
  level: $Enums.ImportLogLevel;
  message: string;
  details?: string | null;
  recordId?: string | null;
  createdAt?: Date | string;
};

export type ImportLogUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  level?: Prisma.EnumImportLogLevelFieldUpdateOperationsInput | $Enums.ImportLogLevel;
  message?: Prisma.StringFieldUpdateOperationsInput | string;
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  recordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type ImportLogUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  dataSourceRunId?: Prisma.StringFieldUpdateOperationsInput | string;
  level?: Prisma.EnumImportLogLevelFieldUpdateOperationsInput | $Enums.ImportLogLevel;
  message?: Prisma.StringFieldUpdateOperationsInput | string;
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  recordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type ImportLogListRelationFilter = {
  every?: Prisma.ImportLogWhereInput;
  some?: Prisma.ImportLogWhereInput;
  none?: Prisma.ImportLogWhereInput;
};

export type ImportLogOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder;
};

export type ImportLogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  dataSourceRunId?: Prisma.SortOrder;
  level?: Prisma.SortOrder;
  message?: Prisma.SortOrder;
  details?: Prisma.SortOrder;
  recordId?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
};

export type ImportLogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  dataSourceRunId?: Prisma.SortOrder;
  level?: Prisma.SortOrder;
  message?: Prisma.SortOrder;
  details?: Prisma.SortOrder;
  recordId?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
};

export type ImportLogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  dataSourceRunId?: Prisma.SortOrder;
  level?: Prisma.SortOrder;
  message?: Prisma.SortOrder;
  details?: Prisma.SortOrder;
  recordId?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
};

export type ImportLogCreateNestedManyWithoutDataSourceRunInput = {
  create?:
    | Prisma.XOR<Prisma.ImportLogCreateWithoutDataSourceRunInput, Prisma.ImportLogUncheckedCreateWithoutDataSourceRunInput>
    | Prisma.ImportLogCreateWithoutDataSourceRunInput[]
    | Prisma.ImportLogUncheckedCreateWithoutDataSourceRunInput[];
  connectOrCreate?: Prisma.ImportLogCreateOrConnectWithoutDataSourceRunInput | Prisma.ImportLogCreateOrConnectWithoutDataSourceRunInput[];
  createMany?: Prisma.ImportLogCreateManyDataSourceRunInputEnvelope;
  connect?: Prisma.ImportLogWhereUniqueInput | Prisma.ImportLogWhereUniqueInput[];
};

export type ImportLogUncheckedCreateNestedManyWithoutDataSourceRunInput = {
  create?:
    | Prisma.XOR<Prisma.ImportLogCreateWithoutDataSourceRunInput, Prisma.ImportLogUncheckedCreateWithoutDataSourceRunInput>
    | Prisma.ImportLogCreateWithoutDataSourceRunInput[]
    | Prisma.ImportLogUncheckedCreateWithoutDataSourceRunInput[];
  connectOrCreate?: Prisma.ImportLogCreateOrConnectWithoutDataSourceRunInput | Prisma.ImportLogCreateOrConnectWithoutDataSourceRunInput[];
  createMany?: Prisma.ImportLogCreateManyDataSourceRunInputEnvelope;
  connect?: Prisma.ImportLogWhereUniqueInput | Prisma.ImportLogWhereUniqueInput[];
};

export type ImportLogUpdateManyWithoutDataSourceRunNestedInput = {
  create?:
    | Prisma.XOR<Prisma.ImportLogCreateWithoutDataSourceRunInput, Prisma.ImportLogUncheckedCreateWithoutDataSourceRunInput>
    | Prisma.ImportLogCreateWithoutDataSourceRunInput[]
    | Prisma.ImportLogUncheckedCreateWithoutDataSourceRunInput[];
  connectOrCreate?: Prisma.ImportLogCreateOrConnectWithoutDataSourceRunInput | Prisma.ImportLogCreateOrConnectWithoutDataSourceRunInput[];
  upsert?: Prisma.ImportLogUpsertWithWhereUniqueWithoutDataSourceRunInput | Prisma.ImportLogUpsertWithWhereUniqueWithoutDataSourceRunInput[];
  createMany?: Prisma.ImportLogCreateManyDataSourceRunInputEnvelope;
  set?: Prisma.ImportLogWhereUniqueInput | Prisma.ImportLogWhereUniqueInput[];
  disconnect?: Prisma.ImportLogWhereUniqueInput | Prisma.ImportLogWhereUniqueInput[];
  delete?: Prisma.ImportLogWhereUniqueInput | Prisma.ImportLogWhereUniqueInput[];
  connect?: Prisma.ImportLogWhereUniqueInput | Prisma.ImportLogWhereUniqueInput[];
  update?: Prisma.ImportLogUpdateWithWhereUniqueWithoutDataSourceRunInput | Prisma.ImportLogUpdateWithWhereUniqueWithoutDataSourceRunInput[];
  updateMany?: Prisma.ImportLogUpdateManyWithWhereWithoutDataSourceRunInput | Prisma.ImportLogUpdateManyWithWhereWithoutDataSourceRunInput[];
  deleteMany?: Prisma.ImportLogScalarWhereInput | Prisma.ImportLogScalarWhereInput[];
};

export type ImportLogUncheckedUpdateManyWithoutDataSourceRunNestedInput = {
  create?:
    | Prisma.XOR<Prisma.ImportLogCreateWithoutDataSourceRunInput, Prisma.ImportLogUncheckedCreateWithoutDataSourceRunInput>
    | Prisma.ImportLogCreateWithoutDataSourceRunInput[]
    | Prisma.ImportLogUncheckedCreateWithoutDataSourceRunInput[];
  connectOrCreate?: Prisma.ImportLogCreateOrConnectWithoutDataSourceRunInput | Prisma.ImportLogCreateOrConnectWithoutDataSourceRunInput[];
  upsert?: Prisma.ImportLogUpsertWithWhereUniqueWithoutDataSourceRunInput | Prisma.ImportLogUpsertWithWhereUniqueWithoutDataSourceRunInput[];
  createMany?: Prisma.ImportLogCreateManyDataSourceRunInputEnvelope;
  set?: Prisma.ImportLogWhereUniqueInput | Prisma.ImportLogWhereUniqueInput[];
  disconnect?: Prisma.ImportLogWhereUniqueInput | Prisma.ImportLogWhereUniqueInput[];
  delete?: Prisma.ImportLogWhereUniqueInput | Prisma.ImportLogWhereUniqueInput[];
  connect?: Prisma.ImportLogWhereUniqueInput | Prisma.ImportLogWhereUniqueInput[];
  update?: Prisma.ImportLogUpdateWithWhereUniqueWithoutDataSourceRunInput | Prisma.ImportLogUpdateWithWhereUniqueWithoutDataSourceRunInput[];
  updateMany?: Prisma.ImportLogUpdateManyWithWhereWithoutDataSourceRunInput | Prisma.ImportLogUpdateManyWithWhereWithoutDataSourceRunInput[];
  deleteMany?: Prisma.ImportLogScalarWhereInput | Prisma.ImportLogScalarWhereInput[];
};

export type EnumImportLogLevelFieldUpdateOperationsInput = {
  set?: $Enums.ImportLogLevel;
};

export type ImportLogCreateWithoutDataSourceRunInput = {
  id?: string;
  level: $Enums.ImportLogLevel;
  message: string;
  details?: string | null;
  recordId?: string | null;
  createdAt?: Date | string;
};

export type ImportLogUncheckedCreateWithoutDataSourceRunInput = {
  id?: string;
  level: $Enums.ImportLogLevel;
  message: string;
  details?: string | null;
  recordId?: string | null;
  createdAt?: Date | string;
};

export type ImportLogCreateOrConnectWithoutDataSourceRunInput = {
  where: Prisma.ImportLogWhereUniqueInput;
  create: Prisma.XOR<Prisma.ImportLogCreateWithoutDataSourceRunInput, Prisma.ImportLogUncheckedCreateWithoutDataSourceRunInput>;
};

export type ImportLogCreateManyDataSourceRunInputEnvelope = {
  data: Prisma.ImportLogCreateManyDataSourceRunInput | Prisma.ImportLogCreateManyDataSourceRunInput[];
  skipDuplicates?: boolean;
};

export type ImportLogUpsertWithWhereUniqueWithoutDataSourceRunInput = {
  where: Prisma.ImportLogWhereUniqueInput;
  update: Prisma.XOR<Prisma.ImportLogUpdateWithoutDataSourceRunInput, Prisma.ImportLogUncheckedUpdateWithoutDataSourceRunInput>;
  create: Prisma.XOR<Prisma.ImportLogCreateWithoutDataSourceRunInput, Prisma.ImportLogUncheckedCreateWithoutDataSourceRunInput>;
};

export type ImportLogUpdateWithWhereUniqueWithoutDataSourceRunInput = {
  where: Prisma.ImportLogWhereUniqueInput;
  data: Prisma.XOR<Prisma.ImportLogUpdateWithoutDataSourceRunInput, Prisma.ImportLogUncheckedUpdateWithoutDataSourceRunInput>;
};

export type ImportLogUpdateManyWithWhereWithoutDataSourceRunInput = {
  where: Prisma.ImportLogScalarWhereInput;
  data: Prisma.XOR<Prisma.ImportLogUpdateManyMutationInput, Prisma.ImportLogUncheckedUpdateManyWithoutDataSourceRunInput>;
};

export type ImportLogScalarWhereInput = {
  AND?: Prisma.ImportLogScalarWhereInput | Prisma.ImportLogScalarWhereInput[];
  OR?: Prisma.ImportLogScalarWhereInput[];
  NOT?: Prisma.ImportLogScalarWhereInput | Prisma.ImportLogScalarWhereInput[];
  id?: Prisma.StringFilter<"ImportLog"> | string;
  dataSourceRunId?: Prisma.StringFilter<"ImportLog"> | string;
  level?: Prisma.EnumImportLogLevelFilter<"ImportLog"> | $Enums.ImportLogLevel;
  message?: Prisma.StringFilter<"ImportLog"> | string;
  details?: Prisma.StringNullableFilter<"ImportLog"> | string | null;
  recordId?: Prisma.StringNullableFilter<"ImportLog"> | string | null;
  createdAt?: Prisma.DateTimeFilter<"ImportLog"> | Date | string;
};

export type ImportLogCreateManyDataSourceRunInput = {
  id?: string;
  level: $Enums.ImportLogLevel;
  message: string;
  details?: string | null;
  recordId?: string | null;
  createdAt?: Date | string;
};

export type ImportLogUpdateWithoutDataSourceRunInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  level?: Prisma.EnumImportLogLevelFieldUpdateOperationsInput | $Enums.ImportLogLevel;
  message?: Prisma.StringFieldUpdateOperationsInput | string;
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  recordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type ImportLogUncheckedUpdateWithoutDataSourceRunInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  level?: Prisma.EnumImportLogLevelFieldUpdateOperationsInput | $Enums.ImportLogLevel;
  message?: Prisma.StringFieldUpdateOperationsInput | string;
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  recordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type ImportLogUncheckedUpdateManyWithoutDataSourceRunInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  level?: Prisma.EnumImportLogLevelFieldUpdateOperationsInput | $Enums.ImportLogLevel;
  message?: Prisma.StringFieldUpdateOperationsInput | string;
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  recordId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type ImportLogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    dataSourceRunId?: boolean;
    level?: boolean;
    message?: boolean;
    details?: boolean;
    recordId?: boolean;
    createdAt?: boolean;
    dataSourceRun?: boolean | Prisma.DataSourceRunDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["importLog"]
>;

export type ImportLogSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    dataSourceRunId?: boolean;
    level?: boolean;
    message?: boolean;
    details?: boolean;
    recordId?: boolean;
    createdAt?: boolean;
    dataSourceRun?: boolean | Prisma.DataSourceRunDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["importLog"]
>;

export type ImportLogSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    dataSourceRunId?: boolean;
    level?: boolean;
    message?: boolean;
    details?: boolean;
    recordId?: boolean;
    createdAt?: boolean;
    dataSourceRun?: boolean | Prisma.DataSourceRunDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["importLog"]
>;

export type ImportLogSelectScalar = {
  id?: boolean;
  dataSourceRunId?: boolean;
  level?: boolean;
  message?: boolean;
  details?: boolean;
  recordId?: boolean;
  createdAt?: boolean;
};

export type ImportLogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<
  "id" | "dataSourceRunId" | "level" | "message" | "details" | "recordId" | "createdAt",
  ExtArgs["result"]["importLog"]
>;
export type ImportLogInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dataSourceRun?: boolean | Prisma.DataSourceRunDefaultArgs<ExtArgs>;
};
export type ImportLogIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dataSourceRun?: boolean | Prisma.DataSourceRunDefaultArgs<ExtArgs>;
};
export type ImportLogIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dataSourceRun?: boolean | Prisma.DataSourceRunDefaultArgs<ExtArgs>;
};

export type $ImportLogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ImportLog";
  objects: {
    dataSourceRun: Prisma.$DataSourceRunPayload<ExtArgs>;
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string;
      dataSourceRunId: string;
      level: $Enums.ImportLogLevel;
      message: string;
      details: string | null;
      recordId: string | null;
      createdAt: Date;
    },
    ExtArgs["result"]["importLog"]
  >;
  composites: {};
};

export type ImportLogGetPayload<S extends boolean | null | undefined | ImportLogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ImportLogPayload, S>;

export type ImportLogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = Omit<
  ImportLogFindManyArgs,
  "select" | "include" | "distinct" | "omit"
> & {
  select?: ImportLogCountAggregateInputType | true;
};

export interface ImportLogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>["model"]["ImportLog"]; meta: { name: "ImportLog" } };
  /**
   * Find zero or one ImportLog that matches the filter.
   * @param {ImportLogFindUniqueArgs} args - Arguments to find a ImportLog
   * @example
   * // Get one ImportLog
   * const importLog = await prisma.importLog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ImportLogFindUniqueArgs>(
    args: Prisma.SelectSubset<T, ImportLogFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__ImportLogClient<runtime.Types.Result.GetResult<Prisma.$ImportLogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>;

  /**
   * Find one ImportLog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ImportLogFindUniqueOrThrowArgs} args - Arguments to find a ImportLog
   * @example
   * // Get one ImportLog
   * const importLog = await prisma.importLog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ImportLogFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, ImportLogFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__ImportLogClient<
    runtime.Types.Result.GetResult<Prisma.$ImportLogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first ImportLog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImportLogFindFirstArgs} args - Arguments to find a ImportLog
   * @example
   * // Get one ImportLog
   * const importLog = await prisma.importLog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ImportLogFindFirstArgs>(
    args?: Prisma.SelectSubset<T, ImportLogFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__ImportLogClient<runtime.Types.Result.GetResult<Prisma.$ImportLogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>;

  /**
   * Find the first ImportLog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImportLogFindFirstOrThrowArgs} args - Arguments to find a ImportLog
   * @example
   * // Get one ImportLog
   * const importLog = await prisma.importLog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ImportLogFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, ImportLogFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__ImportLogClient<runtime.Types.Result.GetResult<Prisma.$ImportLogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;

  /**
   * Find zero or more ImportLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImportLogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ImportLogs
   * const importLogs = await prisma.importLog.findMany()
   *
   * // Get first 10 ImportLogs
   * const importLogs = await prisma.importLog.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const importLogWithIdOnly = await prisma.importLog.findMany({ select: { id: true } })
   *
   */
  findMany<T extends ImportLogFindManyArgs>(
    args?: Prisma.SelectSubset<T, ImportLogFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ImportLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>;

  /**
   * Create a ImportLog.
   * @param {ImportLogCreateArgs} args - Arguments to create a ImportLog.
   * @example
   * // Create one ImportLog
   * const ImportLog = await prisma.importLog.create({
   *   data: {
   *     // ... data to create a ImportLog
   *   }
   * })
   *
   */
  create<T extends ImportLogCreateArgs>(
    args: Prisma.SelectSubset<T, ImportLogCreateArgs<ExtArgs>>
  ): Prisma.Prisma__ImportLogClient<runtime.Types.Result.GetResult<Prisma.$ImportLogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;

  /**
   * Create many ImportLogs.
   * @param {ImportLogCreateManyArgs} args - Arguments to create many ImportLogs.
   * @example
   * // Create many ImportLogs
   * const importLog = await prisma.importLog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends ImportLogCreateManyArgs>(args?: Prisma.SelectSubset<T, ImportLogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many ImportLogs and returns the data saved in the database.
   * @param {ImportLogCreateManyAndReturnArgs} args - Arguments to create many ImportLogs.
   * @example
   * // Create many ImportLogs
   * const importLog = await prisma.importLog.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many ImportLogs and only return the `id`
   * const importLogWithIdOnly = await prisma.importLog.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends ImportLogCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, ImportLogCreateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ImportLogPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>;

  /**
   * Delete a ImportLog.
   * @param {ImportLogDeleteArgs} args - Arguments to delete one ImportLog.
   * @example
   * // Delete one ImportLog
   * const ImportLog = await prisma.importLog.delete({
   *   where: {
   *     // ... filter to delete one ImportLog
   *   }
   * })
   *
   */
  delete<T extends ImportLogDeleteArgs>(
    args: Prisma.SelectSubset<T, ImportLogDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__ImportLogClient<runtime.Types.Result.GetResult<Prisma.$ImportLogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;

  /**
   * Update one ImportLog.
   * @param {ImportLogUpdateArgs} args - Arguments to update one ImportLog.
   * @example
   * // Update one ImportLog
   * const importLog = await prisma.importLog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends ImportLogUpdateArgs>(
    args: Prisma.SelectSubset<T, ImportLogUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__ImportLogClient<runtime.Types.Result.GetResult<Prisma.$ImportLogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;

  /**
   * Delete zero or more ImportLogs.
   * @param {ImportLogDeleteManyArgs} args - Arguments to filter ImportLogs to delete.
   * @example
   * // Delete a few ImportLogs
   * const { count } = await prisma.importLog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends ImportLogDeleteManyArgs>(args?: Prisma.SelectSubset<T, ImportLogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more ImportLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImportLogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ImportLogs
   * const importLog = await prisma.importLog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends ImportLogUpdateManyArgs>(args: Prisma.SelectSubset<T, ImportLogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more ImportLogs and returns the data updated in the database.
   * @param {ImportLogUpdateManyAndReturnArgs} args - Arguments to update many ImportLogs.
   * @example
   * // Update many ImportLogs
   * const importLog = await prisma.importLog.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more ImportLogs and only return the `id`
   * const importLogWithIdOnly = await prisma.importLog.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends ImportLogUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, ImportLogUpdateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ImportLogPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>;

  /**
   * Create or update one ImportLog.
   * @param {ImportLogUpsertArgs} args - Arguments to update or create a ImportLog.
   * @example
   * // Update or create a ImportLog
   * const importLog = await prisma.importLog.upsert({
   *   create: {
   *     // ... data to create a ImportLog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ImportLog we want to update
   *   }
   * })
   */
  upsert<T extends ImportLogUpsertArgs>(
    args: Prisma.SelectSubset<T, ImportLogUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__ImportLogClient<runtime.Types.Result.GetResult<Prisma.$ImportLogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;

  /**
   * Count the number of ImportLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImportLogCountArgs} args - Arguments to filter ImportLogs to count.
   * @example
   * // Count the number of ImportLogs
   * const count = await prisma.importLog.count({
   *   where: {
   *     // ... the filter for the ImportLogs we want to count
   *   }
   * })
   **/
  count<T extends ImportLogCountArgs>(
    args?: Prisma.Subset<T, ImportLogCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<"select", any> ? (T["select"] extends true ? number : Prisma.GetScalarType<T["select"], ImportLogCountAggregateOutputType>) : number
  >;

  /**
   * Allows you to perform aggregations operations on a ImportLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImportLogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends ImportLogAggregateArgs>(args: Prisma.Subset<T, ImportLogAggregateArgs>): Prisma.PrismaPromise<GetImportLogAggregateType<T>>;

  /**
   * Group by ImportLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImportLogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends ImportLogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<Prisma.Extends<"skip", Prisma.Keys<T>>, Prisma.Extends<"take", Prisma.Keys<T>>>,
    OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: ImportLogGroupByArgs["orderBy"] } : { orderBy?: ImportLogGroupByArgs["orderBy"] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T["having"]>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, "Field ", P, ` in "having" needs to be provided in "by"`];
          }[HavingFields]
        : "take" extends Prisma.Keys<T>
          ? "orderBy" extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : "skip" extends Prisma.Keys<T>
            ? "orderBy" extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields ? never : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(args: Prisma.SubsetIntersection<T, ImportLogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetImportLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the ImportLog model
   */
  readonly fields: ImportLogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ImportLog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ImportLogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}>
  extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise";
  dataSourceRun<T extends Prisma.DataSourceRunDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.DataSourceRunDefaultArgs<ExtArgs>>
  ): Prisma.Prisma__DataSourceRunClient<
    runtime.Types.Result.GetResult<Prisma.$DataSourceRunPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the ImportLog model
 */
export interface ImportLogFieldRefs {
  readonly id: Prisma.FieldRef<"ImportLog", "String">;
  readonly dataSourceRunId: Prisma.FieldRef<"ImportLog", "String">;
  readonly level: Prisma.FieldRef<"ImportLog", "ImportLogLevel">;
  readonly message: Prisma.FieldRef<"ImportLog", "String">;
  readonly details: Prisma.FieldRef<"ImportLog", "String">;
  readonly recordId: Prisma.FieldRef<"ImportLog", "String">;
  readonly createdAt: Prisma.FieldRef<"ImportLog", "DateTime">;
}

// Custom InputTypes
/**
 * ImportLog findUnique
 */
export type ImportLogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImportLog
   */
  select?: Prisma.ImportLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ImportLog
   */
  omit?: Prisma.ImportLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImportLogInclude<ExtArgs> | null;
  /**
   * Filter, which ImportLog to fetch.
   */
  where: Prisma.ImportLogWhereUniqueInput;
};

/**
 * ImportLog findUniqueOrThrow
 */
export type ImportLogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImportLog
   */
  select?: Prisma.ImportLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ImportLog
   */
  omit?: Prisma.ImportLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImportLogInclude<ExtArgs> | null;
  /**
   * Filter, which ImportLog to fetch.
   */
  where: Prisma.ImportLogWhereUniqueInput;
};

/**
 * ImportLog findFirst
 */
export type ImportLogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImportLog
   */
  select?: Prisma.ImportLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ImportLog
   */
  omit?: Prisma.ImportLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImportLogInclude<ExtArgs> | null;
  /**
   * Filter, which ImportLog to fetch.
   */
  where?: Prisma.ImportLogWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ImportLogs to fetch.
   */
  orderBy?: Prisma.ImportLogOrderByWithRelationInput | Prisma.ImportLogOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for ImportLogs.
   */
  cursor?: Prisma.ImportLogWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ImportLogs from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ImportLogs.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ImportLogs.
   */
  distinct?: Prisma.ImportLogScalarFieldEnum | Prisma.ImportLogScalarFieldEnum[];
};

/**
 * ImportLog findFirstOrThrow
 */
export type ImportLogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImportLog
   */
  select?: Prisma.ImportLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ImportLog
   */
  omit?: Prisma.ImportLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImportLogInclude<ExtArgs> | null;
  /**
   * Filter, which ImportLog to fetch.
   */
  where?: Prisma.ImportLogWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ImportLogs to fetch.
   */
  orderBy?: Prisma.ImportLogOrderByWithRelationInput | Prisma.ImportLogOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for ImportLogs.
   */
  cursor?: Prisma.ImportLogWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ImportLogs from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ImportLogs.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ImportLogs.
   */
  distinct?: Prisma.ImportLogScalarFieldEnum | Prisma.ImportLogScalarFieldEnum[];
};

/**
 * ImportLog findMany
 */
export type ImportLogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImportLog
   */
  select?: Prisma.ImportLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ImportLog
   */
  omit?: Prisma.ImportLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImportLogInclude<ExtArgs> | null;
  /**
   * Filter, which ImportLogs to fetch.
   */
  where?: Prisma.ImportLogWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ImportLogs to fetch.
   */
  orderBy?: Prisma.ImportLogOrderByWithRelationInput | Prisma.ImportLogOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing ImportLogs.
   */
  cursor?: Prisma.ImportLogWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ImportLogs from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ImportLogs.
   */
  skip?: number;
  distinct?: Prisma.ImportLogScalarFieldEnum | Prisma.ImportLogScalarFieldEnum[];
};

/**
 * ImportLog create
 */
export type ImportLogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImportLog
   */
  select?: Prisma.ImportLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ImportLog
   */
  omit?: Prisma.ImportLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImportLogInclude<ExtArgs> | null;
  /**
   * The data needed to create a ImportLog.
   */
  data: Prisma.XOR<Prisma.ImportLogCreateInput, Prisma.ImportLogUncheckedCreateInput>;
};

/**
 * ImportLog createMany
 */
export type ImportLogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ImportLogs.
   */
  data: Prisma.ImportLogCreateManyInput | Prisma.ImportLogCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * ImportLog createManyAndReturn
 */
export type ImportLogCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImportLog
   */
  select?: Prisma.ImportLogSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the ImportLog
   */
  omit?: Prisma.ImportLogOmit<ExtArgs> | null;
  /**
   * The data used to create many ImportLogs.
   */
  data: Prisma.ImportLogCreateManyInput | Prisma.ImportLogCreateManyInput[];
  skipDuplicates?: boolean;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImportLogIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * ImportLog update
 */
export type ImportLogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImportLog
   */
  select?: Prisma.ImportLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ImportLog
   */
  omit?: Prisma.ImportLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImportLogInclude<ExtArgs> | null;
  /**
   * The data needed to update a ImportLog.
   */
  data: Prisma.XOR<Prisma.ImportLogUpdateInput, Prisma.ImportLogUncheckedUpdateInput>;
  /**
   * Choose, which ImportLog to update.
   */
  where: Prisma.ImportLogWhereUniqueInput;
};

/**
 * ImportLog updateMany
 */
export type ImportLogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ImportLogs.
   */
  data: Prisma.XOR<Prisma.ImportLogUpdateManyMutationInput, Prisma.ImportLogUncheckedUpdateManyInput>;
  /**
   * Filter which ImportLogs to update
   */
  where?: Prisma.ImportLogWhereInput;
  /**
   * Limit how many ImportLogs to update.
   */
  limit?: number;
};

/**
 * ImportLog updateManyAndReturn
 */
export type ImportLogUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImportLog
   */
  select?: Prisma.ImportLogSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the ImportLog
   */
  omit?: Prisma.ImportLogOmit<ExtArgs> | null;
  /**
   * The data used to update ImportLogs.
   */
  data: Prisma.XOR<Prisma.ImportLogUpdateManyMutationInput, Prisma.ImportLogUncheckedUpdateManyInput>;
  /**
   * Filter which ImportLogs to update
   */
  where?: Prisma.ImportLogWhereInput;
  /**
   * Limit how many ImportLogs to update.
   */
  limit?: number;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImportLogIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * ImportLog upsert
 */
export type ImportLogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImportLog
   */
  select?: Prisma.ImportLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ImportLog
   */
  omit?: Prisma.ImportLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImportLogInclude<ExtArgs> | null;
  /**
   * The filter to search for the ImportLog to update in case it exists.
   */
  where: Prisma.ImportLogWhereUniqueInput;
  /**
   * In case the ImportLog found by the `where` argument doesn't exist, create a new ImportLog with this data.
   */
  create: Prisma.XOR<Prisma.ImportLogCreateInput, Prisma.ImportLogUncheckedCreateInput>;
  /**
   * In case the ImportLog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ImportLogUpdateInput, Prisma.ImportLogUncheckedUpdateInput>;
};

/**
 * ImportLog delete
 */
export type ImportLogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImportLog
   */
  select?: Prisma.ImportLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ImportLog
   */
  omit?: Prisma.ImportLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImportLogInclude<ExtArgs> | null;
  /**
   * Filter which ImportLog to delete.
   */
  where: Prisma.ImportLogWhereUniqueInput;
};

/**
 * ImportLog deleteMany
 */
export type ImportLogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ImportLogs to delete
   */
  where?: Prisma.ImportLogWhereInput;
  /**
   * Limit how many ImportLogs to delete.
   */
  limit?: number;
};

/**
 * ImportLog without action
 */
export type ImportLogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImportLog
   */
  select?: Prisma.ImportLogSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ImportLog
   */
  omit?: Prisma.ImportLogOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImportLogInclude<ExtArgs> | null;
};
