
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SonarQubeProjectMapping` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SonarQubeProjectMapping
 * 
 */
export type SonarQubeProjectMappingModel = runtime.Types.Result.DefaultSelection<Prisma.$SonarQubeProjectMappingPayload>

export type AggregateSonarQubeProjectMapping = {
  _count: SonarQubeProjectMappingCountAggregateOutputType | null
  _min: SonarQubeProjectMappingMinAggregateOutputType | null
  _max: SonarQubeProjectMappingMaxAggregateOutputType | null
}

export type SonarQubeProjectMappingMinAggregateOutputType = {
  id: string | null
  dataSourceId: string | null
  projectKey: string | null
  projectName: string | null
  repositoryId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SonarQubeProjectMappingMaxAggregateOutputType = {
  id: string | null
  dataSourceId: string | null
  projectKey: string | null
  projectName: string | null
  repositoryId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SonarQubeProjectMappingCountAggregateOutputType = {
  id: number
  dataSourceId: number
  projectKey: number
  projectName: number
  repositoryId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type SonarQubeProjectMappingMinAggregateInputType = {
  id?: true
  dataSourceId?: true
  projectKey?: true
  projectName?: true
  repositoryId?: true
  createdAt?: true
  updatedAt?: true
}

export type SonarQubeProjectMappingMaxAggregateInputType = {
  id?: true
  dataSourceId?: true
  projectKey?: true
  projectName?: true
  repositoryId?: true
  createdAt?: true
  updatedAt?: true
}

export type SonarQubeProjectMappingCountAggregateInputType = {
  id?: true
  dataSourceId?: true
  projectKey?: true
  projectName?: true
  repositoryId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type SonarQubeProjectMappingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SonarQubeProjectMapping to aggregate.
   */
  where?: Prisma.SonarQubeProjectMappingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SonarQubeProjectMappings to fetch.
   */
  orderBy?: Prisma.SonarQubeProjectMappingOrderByWithRelationInput | Prisma.SonarQubeProjectMappingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SonarQubeProjectMappingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SonarQubeProjectMappings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SonarQubeProjectMappings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SonarQubeProjectMappings
  **/
  _count?: true | SonarQubeProjectMappingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SonarQubeProjectMappingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SonarQubeProjectMappingMaxAggregateInputType
}

export type GetSonarQubeProjectMappingAggregateType<T extends SonarQubeProjectMappingAggregateArgs> = {
      [P in keyof T & keyof AggregateSonarQubeProjectMapping]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSonarQubeProjectMapping[P]>
    : Prisma.GetScalarType<T[P], AggregateSonarQubeProjectMapping[P]>
}




export type SonarQubeProjectMappingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SonarQubeProjectMappingWhereInput
  orderBy?: Prisma.SonarQubeProjectMappingOrderByWithAggregationInput | Prisma.SonarQubeProjectMappingOrderByWithAggregationInput[]
  by: Prisma.SonarQubeProjectMappingScalarFieldEnum[] | Prisma.SonarQubeProjectMappingScalarFieldEnum
  having?: Prisma.SonarQubeProjectMappingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SonarQubeProjectMappingCountAggregateInputType | true
  _min?: SonarQubeProjectMappingMinAggregateInputType
  _max?: SonarQubeProjectMappingMaxAggregateInputType
}

export type SonarQubeProjectMappingGroupByOutputType = {
  id: string
  dataSourceId: string
  projectKey: string
  projectName: string
  repositoryId: string | null
  createdAt: Date
  updatedAt: Date
  _count: SonarQubeProjectMappingCountAggregateOutputType | null
  _min: SonarQubeProjectMappingMinAggregateOutputType | null
  _max: SonarQubeProjectMappingMaxAggregateOutputType | null
}

type GetSonarQubeProjectMappingGroupByPayload<T extends SonarQubeProjectMappingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SonarQubeProjectMappingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SonarQubeProjectMappingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SonarQubeProjectMappingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SonarQubeProjectMappingGroupByOutputType[P]>
      }
    >
  >



export type SonarQubeProjectMappingWhereInput = {
  AND?: Prisma.SonarQubeProjectMappingWhereInput | Prisma.SonarQubeProjectMappingWhereInput[]
  OR?: Prisma.SonarQubeProjectMappingWhereInput[]
  NOT?: Prisma.SonarQubeProjectMappingWhereInput | Prisma.SonarQubeProjectMappingWhereInput[]
  id?: Prisma.StringFilter<"SonarQubeProjectMapping"> | string
  dataSourceId?: Prisma.StringFilter<"SonarQubeProjectMapping"> | string
  projectKey?: Prisma.StringFilter<"SonarQubeProjectMapping"> | string
  projectName?: Prisma.StringFilter<"SonarQubeProjectMapping"> | string
  repositoryId?: Prisma.StringNullableFilter<"SonarQubeProjectMapping"> | string | null
  createdAt?: Prisma.DateTimeFilter<"SonarQubeProjectMapping"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SonarQubeProjectMapping"> | Date | string
  repository?: Prisma.XOR<Prisma.RepositoryNullableScalarRelationFilter, Prisma.RepositoryWhereInput> | null
}

export type SonarQubeProjectMappingOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  dataSourceId?: Prisma.SortOrder
  projectKey?: Prisma.SortOrder
  projectName?: Prisma.SortOrder
  repositoryId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  repository?: Prisma.RepositoryOrderByWithRelationInput
}

export type SonarQubeProjectMappingWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  dataSourceId_projectKey?: Prisma.SonarQubeProjectMappingDataSourceIdProjectKeyCompoundUniqueInput
  AND?: Prisma.SonarQubeProjectMappingWhereInput | Prisma.SonarQubeProjectMappingWhereInput[]
  OR?: Prisma.SonarQubeProjectMappingWhereInput[]
  NOT?: Prisma.SonarQubeProjectMappingWhereInput | Prisma.SonarQubeProjectMappingWhereInput[]
  dataSourceId?: Prisma.StringFilter<"SonarQubeProjectMapping"> | string
  projectKey?: Prisma.StringFilter<"SonarQubeProjectMapping"> | string
  projectName?: Prisma.StringFilter<"SonarQubeProjectMapping"> | string
  repositoryId?: Prisma.StringNullableFilter<"SonarQubeProjectMapping"> | string | null
  createdAt?: Prisma.DateTimeFilter<"SonarQubeProjectMapping"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SonarQubeProjectMapping"> | Date | string
  repository?: Prisma.XOR<Prisma.RepositoryNullableScalarRelationFilter, Prisma.RepositoryWhereInput> | null
}, "id" | "dataSourceId_projectKey">

export type SonarQubeProjectMappingOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  dataSourceId?: Prisma.SortOrder
  projectKey?: Prisma.SortOrder
  projectName?: Prisma.SortOrder
  repositoryId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.SonarQubeProjectMappingCountOrderByAggregateInput
  _max?: Prisma.SonarQubeProjectMappingMaxOrderByAggregateInput
  _min?: Prisma.SonarQubeProjectMappingMinOrderByAggregateInput
}

export type SonarQubeProjectMappingScalarWhereWithAggregatesInput = {
  AND?: Prisma.SonarQubeProjectMappingScalarWhereWithAggregatesInput | Prisma.SonarQubeProjectMappingScalarWhereWithAggregatesInput[]
  OR?: Prisma.SonarQubeProjectMappingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SonarQubeProjectMappingScalarWhereWithAggregatesInput | Prisma.SonarQubeProjectMappingScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SonarQubeProjectMapping"> | string
  dataSourceId?: Prisma.StringWithAggregatesFilter<"SonarQubeProjectMapping"> | string
  projectKey?: Prisma.StringWithAggregatesFilter<"SonarQubeProjectMapping"> | string
  projectName?: Prisma.StringWithAggregatesFilter<"SonarQubeProjectMapping"> | string
  repositoryId?: Prisma.StringNullableWithAggregatesFilter<"SonarQubeProjectMapping"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SonarQubeProjectMapping"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"SonarQubeProjectMapping"> | Date | string
}

export type SonarQubeProjectMappingCreateInput = {
  id?: string
  dataSourceId: string
  projectKey: string
  projectName: string
  createdAt?: Date | string
  updatedAt?: Date | string
  repository?: Prisma.RepositoryCreateNestedOneWithoutSonarQubeProjectMappingsInput
}

export type SonarQubeProjectMappingUncheckedCreateInput = {
  id?: string
  dataSourceId: string
  projectKey: string
  projectName: string
  repositoryId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SonarQubeProjectMappingUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dataSourceId?: Prisma.StringFieldUpdateOperationsInput | string
  projectKey?: Prisma.StringFieldUpdateOperationsInput | string
  projectName?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  repository?: Prisma.RepositoryUpdateOneWithoutSonarQubeProjectMappingsNestedInput
}

export type SonarQubeProjectMappingUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dataSourceId?: Prisma.StringFieldUpdateOperationsInput | string
  projectKey?: Prisma.StringFieldUpdateOperationsInput | string
  projectName?: Prisma.StringFieldUpdateOperationsInput | string
  repositoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SonarQubeProjectMappingCreateManyInput = {
  id?: string
  dataSourceId: string
  projectKey: string
  projectName: string
  repositoryId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SonarQubeProjectMappingUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dataSourceId?: Prisma.StringFieldUpdateOperationsInput | string
  projectKey?: Prisma.StringFieldUpdateOperationsInput | string
  projectName?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SonarQubeProjectMappingUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dataSourceId?: Prisma.StringFieldUpdateOperationsInput | string
  projectKey?: Prisma.StringFieldUpdateOperationsInput | string
  projectName?: Prisma.StringFieldUpdateOperationsInput | string
  repositoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SonarQubeProjectMappingListRelationFilter = {
  every?: Prisma.SonarQubeProjectMappingWhereInput
  some?: Prisma.SonarQubeProjectMappingWhereInput
  none?: Prisma.SonarQubeProjectMappingWhereInput
}

export type SonarQubeProjectMappingOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SonarQubeProjectMappingDataSourceIdProjectKeyCompoundUniqueInput = {
  dataSourceId: string
  projectKey: string
}

export type SonarQubeProjectMappingCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  dataSourceId?: Prisma.SortOrder
  projectKey?: Prisma.SortOrder
  projectName?: Prisma.SortOrder
  repositoryId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SonarQubeProjectMappingMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  dataSourceId?: Prisma.SortOrder
  projectKey?: Prisma.SortOrder
  projectName?: Prisma.SortOrder
  repositoryId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SonarQubeProjectMappingMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  dataSourceId?: Prisma.SortOrder
  projectKey?: Prisma.SortOrder
  projectName?: Prisma.SortOrder
  repositoryId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SonarQubeProjectMappingCreateNestedManyWithoutRepositoryInput = {
  create?: Prisma.XOR<Prisma.SonarQubeProjectMappingCreateWithoutRepositoryInput, Prisma.SonarQubeProjectMappingUncheckedCreateWithoutRepositoryInput> | Prisma.SonarQubeProjectMappingCreateWithoutRepositoryInput[] | Prisma.SonarQubeProjectMappingUncheckedCreateWithoutRepositoryInput[]
  connectOrCreate?: Prisma.SonarQubeProjectMappingCreateOrConnectWithoutRepositoryInput | Prisma.SonarQubeProjectMappingCreateOrConnectWithoutRepositoryInput[]
  createMany?: Prisma.SonarQubeProjectMappingCreateManyRepositoryInputEnvelope
  connect?: Prisma.SonarQubeProjectMappingWhereUniqueInput | Prisma.SonarQubeProjectMappingWhereUniqueInput[]
}

export type SonarQubeProjectMappingUncheckedCreateNestedManyWithoutRepositoryInput = {
  create?: Prisma.XOR<Prisma.SonarQubeProjectMappingCreateWithoutRepositoryInput, Prisma.SonarQubeProjectMappingUncheckedCreateWithoutRepositoryInput> | Prisma.SonarQubeProjectMappingCreateWithoutRepositoryInput[] | Prisma.SonarQubeProjectMappingUncheckedCreateWithoutRepositoryInput[]
  connectOrCreate?: Prisma.SonarQubeProjectMappingCreateOrConnectWithoutRepositoryInput | Prisma.SonarQubeProjectMappingCreateOrConnectWithoutRepositoryInput[]
  createMany?: Prisma.SonarQubeProjectMappingCreateManyRepositoryInputEnvelope
  connect?: Prisma.SonarQubeProjectMappingWhereUniqueInput | Prisma.SonarQubeProjectMappingWhereUniqueInput[]
}

export type SonarQubeProjectMappingUpdateManyWithoutRepositoryNestedInput = {
  create?: Prisma.XOR<Prisma.SonarQubeProjectMappingCreateWithoutRepositoryInput, Prisma.SonarQubeProjectMappingUncheckedCreateWithoutRepositoryInput> | Prisma.SonarQubeProjectMappingCreateWithoutRepositoryInput[] | Prisma.SonarQubeProjectMappingUncheckedCreateWithoutRepositoryInput[]
  connectOrCreate?: Prisma.SonarQubeProjectMappingCreateOrConnectWithoutRepositoryInput | Prisma.SonarQubeProjectMappingCreateOrConnectWithoutRepositoryInput[]
  upsert?: Prisma.SonarQubeProjectMappingUpsertWithWhereUniqueWithoutRepositoryInput | Prisma.SonarQubeProjectMappingUpsertWithWhereUniqueWithoutRepositoryInput[]
  createMany?: Prisma.SonarQubeProjectMappingCreateManyRepositoryInputEnvelope
  set?: Prisma.SonarQubeProjectMappingWhereUniqueInput | Prisma.SonarQubeProjectMappingWhereUniqueInput[]
  disconnect?: Prisma.SonarQubeProjectMappingWhereUniqueInput | Prisma.SonarQubeProjectMappingWhereUniqueInput[]
  delete?: Prisma.SonarQubeProjectMappingWhereUniqueInput | Prisma.SonarQubeProjectMappingWhereUniqueInput[]
  connect?: Prisma.SonarQubeProjectMappingWhereUniqueInput | Prisma.SonarQubeProjectMappingWhereUniqueInput[]
  update?: Prisma.SonarQubeProjectMappingUpdateWithWhereUniqueWithoutRepositoryInput | Prisma.SonarQubeProjectMappingUpdateWithWhereUniqueWithoutRepositoryInput[]
  updateMany?: Prisma.SonarQubeProjectMappingUpdateManyWithWhereWithoutRepositoryInput | Prisma.SonarQubeProjectMappingUpdateManyWithWhereWithoutRepositoryInput[]
  deleteMany?: Prisma.SonarQubeProjectMappingScalarWhereInput | Prisma.SonarQubeProjectMappingScalarWhereInput[]
}

export type SonarQubeProjectMappingUncheckedUpdateManyWithoutRepositoryNestedInput = {
  create?: Prisma.XOR<Prisma.SonarQubeProjectMappingCreateWithoutRepositoryInput, Prisma.SonarQubeProjectMappingUncheckedCreateWithoutRepositoryInput> | Prisma.SonarQubeProjectMappingCreateWithoutRepositoryInput[] | Prisma.SonarQubeProjectMappingUncheckedCreateWithoutRepositoryInput[]
  connectOrCreate?: Prisma.SonarQubeProjectMappingCreateOrConnectWithoutRepositoryInput | Prisma.SonarQubeProjectMappingCreateOrConnectWithoutRepositoryInput[]
  upsert?: Prisma.SonarQubeProjectMappingUpsertWithWhereUniqueWithoutRepositoryInput | Prisma.SonarQubeProjectMappingUpsertWithWhereUniqueWithoutRepositoryInput[]
  createMany?: Prisma.SonarQubeProjectMappingCreateManyRepositoryInputEnvelope
  set?: Prisma.SonarQubeProjectMappingWhereUniqueInput | Prisma.SonarQubeProjectMappingWhereUniqueInput[]
  disconnect?: Prisma.SonarQubeProjectMappingWhereUniqueInput | Prisma.SonarQubeProjectMappingWhereUniqueInput[]
  delete?: Prisma.SonarQubeProjectMappingWhereUniqueInput | Prisma.SonarQubeProjectMappingWhereUniqueInput[]
  connect?: Prisma.SonarQubeProjectMappingWhereUniqueInput | Prisma.SonarQubeProjectMappingWhereUniqueInput[]
  update?: Prisma.SonarQubeProjectMappingUpdateWithWhereUniqueWithoutRepositoryInput | Prisma.SonarQubeProjectMappingUpdateWithWhereUniqueWithoutRepositoryInput[]
  updateMany?: Prisma.SonarQubeProjectMappingUpdateManyWithWhereWithoutRepositoryInput | Prisma.SonarQubeProjectMappingUpdateManyWithWhereWithoutRepositoryInput[]
  deleteMany?: Prisma.SonarQubeProjectMappingScalarWhereInput | Prisma.SonarQubeProjectMappingScalarWhereInput[]
}

export type SonarQubeProjectMappingCreateWithoutRepositoryInput = {
  id?: string
  dataSourceId: string
  projectKey: string
  projectName: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SonarQubeProjectMappingUncheckedCreateWithoutRepositoryInput = {
  id?: string
  dataSourceId: string
  projectKey: string
  projectName: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SonarQubeProjectMappingCreateOrConnectWithoutRepositoryInput = {
  where: Prisma.SonarQubeProjectMappingWhereUniqueInput
  create: Prisma.XOR<Prisma.SonarQubeProjectMappingCreateWithoutRepositoryInput, Prisma.SonarQubeProjectMappingUncheckedCreateWithoutRepositoryInput>
}

export type SonarQubeProjectMappingCreateManyRepositoryInputEnvelope = {
  data: Prisma.SonarQubeProjectMappingCreateManyRepositoryInput | Prisma.SonarQubeProjectMappingCreateManyRepositoryInput[]
  skipDuplicates?: boolean
}

export type SonarQubeProjectMappingUpsertWithWhereUniqueWithoutRepositoryInput = {
  where: Prisma.SonarQubeProjectMappingWhereUniqueInput
  update: Prisma.XOR<Prisma.SonarQubeProjectMappingUpdateWithoutRepositoryInput, Prisma.SonarQubeProjectMappingUncheckedUpdateWithoutRepositoryInput>
  create: Prisma.XOR<Prisma.SonarQubeProjectMappingCreateWithoutRepositoryInput, Prisma.SonarQubeProjectMappingUncheckedCreateWithoutRepositoryInput>
}

export type SonarQubeProjectMappingUpdateWithWhereUniqueWithoutRepositoryInput = {
  where: Prisma.SonarQubeProjectMappingWhereUniqueInput
  data: Prisma.XOR<Prisma.SonarQubeProjectMappingUpdateWithoutRepositoryInput, Prisma.SonarQubeProjectMappingUncheckedUpdateWithoutRepositoryInput>
}

export type SonarQubeProjectMappingUpdateManyWithWhereWithoutRepositoryInput = {
  where: Prisma.SonarQubeProjectMappingScalarWhereInput
  data: Prisma.XOR<Prisma.SonarQubeProjectMappingUpdateManyMutationInput, Prisma.SonarQubeProjectMappingUncheckedUpdateManyWithoutRepositoryInput>
}

export type SonarQubeProjectMappingScalarWhereInput = {
  AND?: Prisma.SonarQubeProjectMappingScalarWhereInput | Prisma.SonarQubeProjectMappingScalarWhereInput[]
  OR?: Prisma.SonarQubeProjectMappingScalarWhereInput[]
  NOT?: Prisma.SonarQubeProjectMappingScalarWhereInput | Prisma.SonarQubeProjectMappingScalarWhereInput[]
  id?: Prisma.StringFilter<"SonarQubeProjectMapping"> | string
  dataSourceId?: Prisma.StringFilter<"SonarQubeProjectMapping"> | string
  projectKey?: Prisma.StringFilter<"SonarQubeProjectMapping"> | string
  projectName?: Prisma.StringFilter<"SonarQubeProjectMapping"> | string
  repositoryId?: Prisma.StringNullableFilter<"SonarQubeProjectMapping"> | string | null
  createdAt?: Prisma.DateTimeFilter<"SonarQubeProjectMapping"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SonarQubeProjectMapping"> | Date | string
}

export type SonarQubeProjectMappingCreateManyRepositoryInput = {
  id?: string
  dataSourceId: string
  projectKey: string
  projectName: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SonarQubeProjectMappingUpdateWithoutRepositoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dataSourceId?: Prisma.StringFieldUpdateOperationsInput | string
  projectKey?: Prisma.StringFieldUpdateOperationsInput | string
  projectName?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SonarQubeProjectMappingUncheckedUpdateWithoutRepositoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dataSourceId?: Prisma.StringFieldUpdateOperationsInput | string
  projectKey?: Prisma.StringFieldUpdateOperationsInput | string
  projectName?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SonarQubeProjectMappingUncheckedUpdateManyWithoutRepositoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dataSourceId?: Prisma.StringFieldUpdateOperationsInput | string
  projectKey?: Prisma.StringFieldUpdateOperationsInput | string
  projectName?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type SonarQubeProjectMappingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  dataSourceId?: boolean
  projectKey?: boolean
  projectName?: boolean
  repositoryId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  repository?: boolean | Prisma.SonarQubeProjectMapping$repositoryArgs<ExtArgs>
}, ExtArgs["result"]["sonarQubeProjectMapping"]>

export type SonarQubeProjectMappingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  dataSourceId?: boolean
  projectKey?: boolean
  projectName?: boolean
  repositoryId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  repository?: boolean | Prisma.SonarQubeProjectMapping$repositoryArgs<ExtArgs>
}, ExtArgs["result"]["sonarQubeProjectMapping"]>

export type SonarQubeProjectMappingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  dataSourceId?: boolean
  projectKey?: boolean
  projectName?: boolean
  repositoryId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  repository?: boolean | Prisma.SonarQubeProjectMapping$repositoryArgs<ExtArgs>
}, ExtArgs["result"]["sonarQubeProjectMapping"]>

export type SonarQubeProjectMappingSelectScalar = {
  id?: boolean
  dataSourceId?: boolean
  projectKey?: boolean
  projectName?: boolean
  repositoryId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type SonarQubeProjectMappingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "dataSourceId" | "projectKey" | "projectName" | "repositoryId" | "createdAt" | "updatedAt", ExtArgs["result"]["sonarQubeProjectMapping"]>
export type SonarQubeProjectMappingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  repository?: boolean | Prisma.SonarQubeProjectMapping$repositoryArgs<ExtArgs>
}
export type SonarQubeProjectMappingIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  repository?: boolean | Prisma.SonarQubeProjectMapping$repositoryArgs<ExtArgs>
}
export type SonarQubeProjectMappingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  repository?: boolean | Prisma.SonarQubeProjectMapping$repositoryArgs<ExtArgs>
}

export type $SonarQubeProjectMappingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SonarQubeProjectMapping"
  objects: {
    repository: Prisma.$RepositoryPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    dataSourceId: string
    projectKey: string
    projectName: string
    repositoryId: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["sonarQubeProjectMapping"]>
  composites: {}
}

export type SonarQubeProjectMappingGetPayload<S extends boolean | null | undefined | SonarQubeProjectMappingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SonarQubeProjectMappingPayload, S>

export type SonarQubeProjectMappingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SonarQubeProjectMappingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SonarQubeProjectMappingCountAggregateInputType | true
  }

export interface SonarQubeProjectMappingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SonarQubeProjectMapping'], meta: { name: 'SonarQubeProjectMapping' } }
  /**
   * Find zero or one SonarQubeProjectMapping that matches the filter.
   * @param {SonarQubeProjectMappingFindUniqueArgs} args - Arguments to find a SonarQubeProjectMapping
   * @example
   * // Get one SonarQubeProjectMapping
   * const sonarQubeProjectMapping = await prisma.sonarQubeProjectMapping.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SonarQubeProjectMappingFindUniqueArgs>(args: Prisma.SelectSubset<T, SonarQubeProjectMappingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SonarQubeProjectMappingClient<runtime.Types.Result.GetResult<Prisma.$SonarQubeProjectMappingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SonarQubeProjectMapping that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SonarQubeProjectMappingFindUniqueOrThrowArgs} args - Arguments to find a SonarQubeProjectMapping
   * @example
   * // Get one SonarQubeProjectMapping
   * const sonarQubeProjectMapping = await prisma.sonarQubeProjectMapping.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SonarQubeProjectMappingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SonarQubeProjectMappingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SonarQubeProjectMappingClient<runtime.Types.Result.GetResult<Prisma.$SonarQubeProjectMappingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SonarQubeProjectMapping that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SonarQubeProjectMappingFindFirstArgs} args - Arguments to find a SonarQubeProjectMapping
   * @example
   * // Get one SonarQubeProjectMapping
   * const sonarQubeProjectMapping = await prisma.sonarQubeProjectMapping.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SonarQubeProjectMappingFindFirstArgs>(args?: Prisma.SelectSubset<T, SonarQubeProjectMappingFindFirstArgs<ExtArgs>>): Prisma.Prisma__SonarQubeProjectMappingClient<runtime.Types.Result.GetResult<Prisma.$SonarQubeProjectMappingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SonarQubeProjectMapping that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SonarQubeProjectMappingFindFirstOrThrowArgs} args - Arguments to find a SonarQubeProjectMapping
   * @example
   * // Get one SonarQubeProjectMapping
   * const sonarQubeProjectMapping = await prisma.sonarQubeProjectMapping.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SonarQubeProjectMappingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SonarQubeProjectMappingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SonarQubeProjectMappingClient<runtime.Types.Result.GetResult<Prisma.$SonarQubeProjectMappingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SonarQubeProjectMappings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SonarQubeProjectMappingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SonarQubeProjectMappings
   * const sonarQubeProjectMappings = await prisma.sonarQubeProjectMapping.findMany()
   * 
   * // Get first 10 SonarQubeProjectMappings
   * const sonarQubeProjectMappings = await prisma.sonarQubeProjectMapping.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sonarQubeProjectMappingWithIdOnly = await prisma.sonarQubeProjectMapping.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SonarQubeProjectMappingFindManyArgs>(args?: Prisma.SelectSubset<T, SonarQubeProjectMappingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SonarQubeProjectMappingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SonarQubeProjectMapping.
   * @param {SonarQubeProjectMappingCreateArgs} args - Arguments to create a SonarQubeProjectMapping.
   * @example
   * // Create one SonarQubeProjectMapping
   * const SonarQubeProjectMapping = await prisma.sonarQubeProjectMapping.create({
   *   data: {
   *     // ... data to create a SonarQubeProjectMapping
   *   }
   * })
   * 
   */
  create<T extends SonarQubeProjectMappingCreateArgs>(args: Prisma.SelectSubset<T, SonarQubeProjectMappingCreateArgs<ExtArgs>>): Prisma.Prisma__SonarQubeProjectMappingClient<runtime.Types.Result.GetResult<Prisma.$SonarQubeProjectMappingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SonarQubeProjectMappings.
   * @param {SonarQubeProjectMappingCreateManyArgs} args - Arguments to create many SonarQubeProjectMappings.
   * @example
   * // Create many SonarQubeProjectMappings
   * const sonarQubeProjectMapping = await prisma.sonarQubeProjectMapping.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SonarQubeProjectMappingCreateManyArgs>(args?: Prisma.SelectSubset<T, SonarQubeProjectMappingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SonarQubeProjectMappings and returns the data saved in the database.
   * @param {SonarQubeProjectMappingCreateManyAndReturnArgs} args - Arguments to create many SonarQubeProjectMappings.
   * @example
   * // Create many SonarQubeProjectMappings
   * const sonarQubeProjectMapping = await prisma.sonarQubeProjectMapping.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SonarQubeProjectMappings and only return the `id`
   * const sonarQubeProjectMappingWithIdOnly = await prisma.sonarQubeProjectMapping.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SonarQubeProjectMappingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SonarQubeProjectMappingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SonarQubeProjectMappingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SonarQubeProjectMapping.
   * @param {SonarQubeProjectMappingDeleteArgs} args - Arguments to delete one SonarQubeProjectMapping.
   * @example
   * // Delete one SonarQubeProjectMapping
   * const SonarQubeProjectMapping = await prisma.sonarQubeProjectMapping.delete({
   *   where: {
   *     // ... filter to delete one SonarQubeProjectMapping
   *   }
   * })
   * 
   */
  delete<T extends SonarQubeProjectMappingDeleteArgs>(args: Prisma.SelectSubset<T, SonarQubeProjectMappingDeleteArgs<ExtArgs>>): Prisma.Prisma__SonarQubeProjectMappingClient<runtime.Types.Result.GetResult<Prisma.$SonarQubeProjectMappingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SonarQubeProjectMapping.
   * @param {SonarQubeProjectMappingUpdateArgs} args - Arguments to update one SonarQubeProjectMapping.
   * @example
   * // Update one SonarQubeProjectMapping
   * const sonarQubeProjectMapping = await prisma.sonarQubeProjectMapping.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SonarQubeProjectMappingUpdateArgs>(args: Prisma.SelectSubset<T, SonarQubeProjectMappingUpdateArgs<ExtArgs>>): Prisma.Prisma__SonarQubeProjectMappingClient<runtime.Types.Result.GetResult<Prisma.$SonarQubeProjectMappingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SonarQubeProjectMappings.
   * @param {SonarQubeProjectMappingDeleteManyArgs} args - Arguments to filter SonarQubeProjectMappings to delete.
   * @example
   * // Delete a few SonarQubeProjectMappings
   * const { count } = await prisma.sonarQubeProjectMapping.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SonarQubeProjectMappingDeleteManyArgs>(args?: Prisma.SelectSubset<T, SonarQubeProjectMappingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SonarQubeProjectMappings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SonarQubeProjectMappingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SonarQubeProjectMappings
   * const sonarQubeProjectMapping = await prisma.sonarQubeProjectMapping.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SonarQubeProjectMappingUpdateManyArgs>(args: Prisma.SelectSubset<T, SonarQubeProjectMappingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SonarQubeProjectMappings and returns the data updated in the database.
   * @param {SonarQubeProjectMappingUpdateManyAndReturnArgs} args - Arguments to update many SonarQubeProjectMappings.
   * @example
   * // Update many SonarQubeProjectMappings
   * const sonarQubeProjectMapping = await prisma.sonarQubeProjectMapping.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SonarQubeProjectMappings and only return the `id`
   * const sonarQubeProjectMappingWithIdOnly = await prisma.sonarQubeProjectMapping.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SonarQubeProjectMappingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SonarQubeProjectMappingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SonarQubeProjectMappingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SonarQubeProjectMapping.
   * @param {SonarQubeProjectMappingUpsertArgs} args - Arguments to update or create a SonarQubeProjectMapping.
   * @example
   * // Update or create a SonarQubeProjectMapping
   * const sonarQubeProjectMapping = await prisma.sonarQubeProjectMapping.upsert({
   *   create: {
   *     // ... data to create a SonarQubeProjectMapping
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SonarQubeProjectMapping we want to update
   *   }
   * })
   */
  upsert<T extends SonarQubeProjectMappingUpsertArgs>(args: Prisma.SelectSubset<T, SonarQubeProjectMappingUpsertArgs<ExtArgs>>): Prisma.Prisma__SonarQubeProjectMappingClient<runtime.Types.Result.GetResult<Prisma.$SonarQubeProjectMappingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SonarQubeProjectMappings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SonarQubeProjectMappingCountArgs} args - Arguments to filter SonarQubeProjectMappings to count.
   * @example
   * // Count the number of SonarQubeProjectMappings
   * const count = await prisma.sonarQubeProjectMapping.count({
   *   where: {
   *     // ... the filter for the SonarQubeProjectMappings we want to count
   *   }
   * })
  **/
  count<T extends SonarQubeProjectMappingCountArgs>(
    args?: Prisma.Subset<T, SonarQubeProjectMappingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SonarQubeProjectMappingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SonarQubeProjectMapping.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SonarQubeProjectMappingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SonarQubeProjectMappingAggregateArgs>(args: Prisma.Subset<T, SonarQubeProjectMappingAggregateArgs>): Prisma.PrismaPromise<GetSonarQubeProjectMappingAggregateType<T>>

  /**
   * Group by SonarQubeProjectMapping.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SonarQubeProjectMappingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SonarQubeProjectMappingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SonarQubeProjectMappingGroupByArgs['orderBy'] }
      : { orderBy?: SonarQubeProjectMappingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SonarQubeProjectMappingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSonarQubeProjectMappingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SonarQubeProjectMapping model
 */
readonly fields: SonarQubeProjectMappingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SonarQubeProjectMapping.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SonarQubeProjectMappingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  repository<T extends Prisma.SonarQubeProjectMapping$repositoryArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SonarQubeProjectMapping$repositoryArgs<ExtArgs>>): Prisma.Prisma__RepositoryClient<runtime.Types.Result.GetResult<Prisma.$RepositoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SonarQubeProjectMapping model
 */
export interface SonarQubeProjectMappingFieldRefs {
  readonly id: Prisma.FieldRef<"SonarQubeProjectMapping", 'String'>
  readonly dataSourceId: Prisma.FieldRef<"SonarQubeProjectMapping", 'String'>
  readonly projectKey: Prisma.FieldRef<"SonarQubeProjectMapping", 'String'>
  readonly projectName: Prisma.FieldRef<"SonarQubeProjectMapping", 'String'>
  readonly repositoryId: Prisma.FieldRef<"SonarQubeProjectMapping", 'String'>
  readonly createdAt: Prisma.FieldRef<"SonarQubeProjectMapping", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"SonarQubeProjectMapping", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SonarQubeProjectMapping findUnique
 */
export type SonarQubeProjectMappingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SonarQubeProjectMapping
   */
  select?: Prisma.SonarQubeProjectMappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SonarQubeProjectMapping
   */
  omit?: Prisma.SonarQubeProjectMappingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SonarQubeProjectMappingInclude<ExtArgs> | null
  /**
   * Filter, which SonarQubeProjectMapping to fetch.
   */
  where: Prisma.SonarQubeProjectMappingWhereUniqueInput
}

/**
 * SonarQubeProjectMapping findUniqueOrThrow
 */
export type SonarQubeProjectMappingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SonarQubeProjectMapping
   */
  select?: Prisma.SonarQubeProjectMappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SonarQubeProjectMapping
   */
  omit?: Prisma.SonarQubeProjectMappingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SonarQubeProjectMappingInclude<ExtArgs> | null
  /**
   * Filter, which SonarQubeProjectMapping to fetch.
   */
  where: Prisma.SonarQubeProjectMappingWhereUniqueInput
}

/**
 * SonarQubeProjectMapping findFirst
 */
export type SonarQubeProjectMappingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SonarQubeProjectMapping
   */
  select?: Prisma.SonarQubeProjectMappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SonarQubeProjectMapping
   */
  omit?: Prisma.SonarQubeProjectMappingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SonarQubeProjectMappingInclude<ExtArgs> | null
  /**
   * Filter, which SonarQubeProjectMapping to fetch.
   */
  where?: Prisma.SonarQubeProjectMappingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SonarQubeProjectMappings to fetch.
   */
  orderBy?: Prisma.SonarQubeProjectMappingOrderByWithRelationInput | Prisma.SonarQubeProjectMappingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SonarQubeProjectMappings.
   */
  cursor?: Prisma.SonarQubeProjectMappingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SonarQubeProjectMappings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SonarQubeProjectMappings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SonarQubeProjectMappings.
   */
  distinct?: Prisma.SonarQubeProjectMappingScalarFieldEnum | Prisma.SonarQubeProjectMappingScalarFieldEnum[]
}

/**
 * SonarQubeProjectMapping findFirstOrThrow
 */
export type SonarQubeProjectMappingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SonarQubeProjectMapping
   */
  select?: Prisma.SonarQubeProjectMappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SonarQubeProjectMapping
   */
  omit?: Prisma.SonarQubeProjectMappingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SonarQubeProjectMappingInclude<ExtArgs> | null
  /**
   * Filter, which SonarQubeProjectMapping to fetch.
   */
  where?: Prisma.SonarQubeProjectMappingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SonarQubeProjectMappings to fetch.
   */
  orderBy?: Prisma.SonarQubeProjectMappingOrderByWithRelationInput | Prisma.SonarQubeProjectMappingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SonarQubeProjectMappings.
   */
  cursor?: Prisma.SonarQubeProjectMappingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SonarQubeProjectMappings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SonarQubeProjectMappings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SonarQubeProjectMappings.
   */
  distinct?: Prisma.SonarQubeProjectMappingScalarFieldEnum | Prisma.SonarQubeProjectMappingScalarFieldEnum[]
}

/**
 * SonarQubeProjectMapping findMany
 */
export type SonarQubeProjectMappingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SonarQubeProjectMapping
   */
  select?: Prisma.SonarQubeProjectMappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SonarQubeProjectMapping
   */
  omit?: Prisma.SonarQubeProjectMappingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SonarQubeProjectMappingInclude<ExtArgs> | null
  /**
   * Filter, which SonarQubeProjectMappings to fetch.
   */
  where?: Prisma.SonarQubeProjectMappingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SonarQubeProjectMappings to fetch.
   */
  orderBy?: Prisma.SonarQubeProjectMappingOrderByWithRelationInput | Prisma.SonarQubeProjectMappingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SonarQubeProjectMappings.
   */
  cursor?: Prisma.SonarQubeProjectMappingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SonarQubeProjectMappings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SonarQubeProjectMappings.
   */
  skip?: number
  distinct?: Prisma.SonarQubeProjectMappingScalarFieldEnum | Prisma.SonarQubeProjectMappingScalarFieldEnum[]
}

/**
 * SonarQubeProjectMapping create
 */
export type SonarQubeProjectMappingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SonarQubeProjectMapping
   */
  select?: Prisma.SonarQubeProjectMappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SonarQubeProjectMapping
   */
  omit?: Prisma.SonarQubeProjectMappingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SonarQubeProjectMappingInclude<ExtArgs> | null
  /**
   * The data needed to create a SonarQubeProjectMapping.
   */
  data: Prisma.XOR<Prisma.SonarQubeProjectMappingCreateInput, Prisma.SonarQubeProjectMappingUncheckedCreateInput>
}

/**
 * SonarQubeProjectMapping createMany
 */
export type SonarQubeProjectMappingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SonarQubeProjectMappings.
   */
  data: Prisma.SonarQubeProjectMappingCreateManyInput | Prisma.SonarQubeProjectMappingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SonarQubeProjectMapping createManyAndReturn
 */
export type SonarQubeProjectMappingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SonarQubeProjectMapping
   */
  select?: Prisma.SonarQubeProjectMappingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SonarQubeProjectMapping
   */
  omit?: Prisma.SonarQubeProjectMappingOmit<ExtArgs> | null
  /**
   * The data used to create many SonarQubeProjectMappings.
   */
  data: Prisma.SonarQubeProjectMappingCreateManyInput | Prisma.SonarQubeProjectMappingCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SonarQubeProjectMappingIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SonarQubeProjectMapping update
 */
export type SonarQubeProjectMappingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SonarQubeProjectMapping
   */
  select?: Prisma.SonarQubeProjectMappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SonarQubeProjectMapping
   */
  omit?: Prisma.SonarQubeProjectMappingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SonarQubeProjectMappingInclude<ExtArgs> | null
  /**
   * The data needed to update a SonarQubeProjectMapping.
   */
  data: Prisma.XOR<Prisma.SonarQubeProjectMappingUpdateInput, Prisma.SonarQubeProjectMappingUncheckedUpdateInput>
  /**
   * Choose, which SonarQubeProjectMapping to update.
   */
  where: Prisma.SonarQubeProjectMappingWhereUniqueInput
}

/**
 * SonarQubeProjectMapping updateMany
 */
export type SonarQubeProjectMappingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SonarQubeProjectMappings.
   */
  data: Prisma.XOR<Prisma.SonarQubeProjectMappingUpdateManyMutationInput, Prisma.SonarQubeProjectMappingUncheckedUpdateManyInput>
  /**
   * Filter which SonarQubeProjectMappings to update
   */
  where?: Prisma.SonarQubeProjectMappingWhereInput
  /**
   * Limit how many SonarQubeProjectMappings to update.
   */
  limit?: number
}

/**
 * SonarQubeProjectMapping updateManyAndReturn
 */
export type SonarQubeProjectMappingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SonarQubeProjectMapping
   */
  select?: Prisma.SonarQubeProjectMappingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SonarQubeProjectMapping
   */
  omit?: Prisma.SonarQubeProjectMappingOmit<ExtArgs> | null
  /**
   * The data used to update SonarQubeProjectMappings.
   */
  data: Prisma.XOR<Prisma.SonarQubeProjectMappingUpdateManyMutationInput, Prisma.SonarQubeProjectMappingUncheckedUpdateManyInput>
  /**
   * Filter which SonarQubeProjectMappings to update
   */
  where?: Prisma.SonarQubeProjectMappingWhereInput
  /**
   * Limit how many SonarQubeProjectMappings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SonarQubeProjectMappingIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SonarQubeProjectMapping upsert
 */
export type SonarQubeProjectMappingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SonarQubeProjectMapping
   */
  select?: Prisma.SonarQubeProjectMappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SonarQubeProjectMapping
   */
  omit?: Prisma.SonarQubeProjectMappingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SonarQubeProjectMappingInclude<ExtArgs> | null
  /**
   * The filter to search for the SonarQubeProjectMapping to update in case it exists.
   */
  where: Prisma.SonarQubeProjectMappingWhereUniqueInput
  /**
   * In case the SonarQubeProjectMapping found by the `where` argument doesn't exist, create a new SonarQubeProjectMapping with this data.
   */
  create: Prisma.XOR<Prisma.SonarQubeProjectMappingCreateInput, Prisma.SonarQubeProjectMappingUncheckedCreateInput>
  /**
   * In case the SonarQubeProjectMapping was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SonarQubeProjectMappingUpdateInput, Prisma.SonarQubeProjectMappingUncheckedUpdateInput>
}

/**
 * SonarQubeProjectMapping delete
 */
export type SonarQubeProjectMappingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SonarQubeProjectMapping
   */
  select?: Prisma.SonarQubeProjectMappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SonarQubeProjectMapping
   */
  omit?: Prisma.SonarQubeProjectMappingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SonarQubeProjectMappingInclude<ExtArgs> | null
  /**
   * Filter which SonarQubeProjectMapping to delete.
   */
  where: Prisma.SonarQubeProjectMappingWhereUniqueInput
}

/**
 * SonarQubeProjectMapping deleteMany
 */
export type SonarQubeProjectMappingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SonarQubeProjectMappings to delete
   */
  where?: Prisma.SonarQubeProjectMappingWhereInput
  /**
   * Limit how many SonarQubeProjectMappings to delete.
   */
  limit?: number
}

/**
 * SonarQubeProjectMapping.repository
 */
export type SonarQubeProjectMapping$repositoryArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Repository
   */
  select?: Prisma.RepositorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Repository
   */
  omit?: Prisma.RepositoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RepositoryInclude<ExtArgs> | null
  where?: Prisma.RepositoryWhereInput
}

/**
 * SonarQubeProjectMapping without action
 */
export type SonarQubeProjectMappingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SonarQubeProjectMapping
   */
  select?: Prisma.SonarQubeProjectMappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SonarQubeProjectMapping
   */
  omit?: Prisma.SonarQubeProjectMappingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SonarQubeProjectMappingInclude<ExtArgs> | null
}
